#!/bin/zsh
cd /Users/edr/code/JouleWise-wt-coldgate-a65fb4fa-ref || exit 2
test ! -e CLAUDE.local.md || { echo "CLAUDE.local.md present"; exit 3; }
P=docs/process_traces/2026-09-24-activation-a65fb4fa/15-coldgate-packet-a291-contract
OUT=$P/11-opus-contract-refuter.md
MSG="You are the PAIRED OPUS CONTRACT REFUTER for cold gate A291-CONTRACT-01: a fresh session with no loop context. HARD RULES: single non-interactive session, no background tasks or subagents, foreground only, 40-minute wall budget; write $OUT with the Write tool before ending (protocol failure otherwise). Do not read CLAUDE.local.md, RUN_STATE.md, TASK_QUEUE.md, council logs, run reports, memory, or any docs/process_traces file outside $P. NEVER run sudo, launchctl, powermetrics or systemsetup; never touch /Users/edr/code/JouleWise, /Users/edr/night-custody, /Users/edr/JouleWise-measurement-*, or ~/Library/LaunchAgents; write nothing but $OUT; probes only in a git archive c0998fdb copy under /tmp. Read $P/00-charge.md, its exhibits, and the Fable judge's ruling $P/10-coldgate-fable-ruling.md. Your lens is CONTRACT: attack the ruling's EXACT CURE TEXTS (Q1-Q20 italic texts) as a checker seat and an implementer would have to implement them. Find (a) internal contradictions between ruled texts, or with 45/21 section 7 texts the ruling left standing; (b) cases the texts leave undecided, where a seat would have to choose; (c) texts that make a ruled path unreachable or the gate unpassable; (d) anything that weakens a physics or evidence guarantee. For each finding: id R1.., severity BLOCKER / MATERIAL / NIT, the exact ruled text quoted, a concrete counter-example roster or event sequence (execute it where feasible), and an exact replacement text. Say AGREE explicitly for the questions you checked and found sound. Under 12 KB. Final reply: one line."
mkdir -p ~/.claude/jobs/a65fb4fa/tmp
~/.local/bin/claude -p "$MSG" --output-format text --permission-mode auto --permission-prompts none --model opus --effort high --allowedTools "Read,Glob,Grep,Bash,Write" > ~/.claude/jobs/a65fb4fa/tmp/refuter-a291.stdout 2> ~/.claude/jobs/a65fb4fa/tmp/refuter-a291.stderr
echo "rc=$?" >> ~/.claude/jobs/a65fb4fa/tmp/refuter-a291.stdout
