#!/bin/zsh
cd /Users/edr/code/JouleWise-wt-coldgate-d8cc9c0a-r2 || exit 2
test ! -e CLAUDE.local.md || { echo "CLAUDE.local.md present in judge worktree"; exit 3; }
P=docs/process_traces/2026-09-23-activation-d8cc9c0a/45-coldgate-packet-a281a-recut
OUT=$P/10-coldgate-fable-ruling.md
PACKET_SHA=8b5f87045bd0735973cd21570c1295d3eb7bd12c0dc36c9d3b5bdd300d596fe1
MSG="You are a COLD FABLE GATE JUDGE: a fresh session with no loop context. HARD RULES: single non-interactive session, no background tasks or subagents (never run_in_background, never Agent), foreground only, 35-minute wall budget, hard; ending before $OUT exists is a protocol failure — write the file $OUT with the Write tool; if a probe cannot be completed in budget, write the ruling with that item marked NOT EXECUTED. Disclose auto-loaded files first. Do not read CLAUDE.local.md, RUN_STATE.md, TASK_QUEUE.md, council logs, run reports, memory, or any docs/process_traces file outside the packet directory $P. NEVER run sudo, launchctl, powermetrics or systemsetup. Never touch /Users/edr/code/JouleWise (canonical root), /Users/edr/night-custody, any /Users/edr/JouleWise-measurement-* directory, or ~/Library/LaunchAgents; do not edit any tracked file other than writing $OUT. Never run the discovery suite. Trust anchors: charter docs/process/coldgate_charter.md sha256 099de884b1d081ffa547dfd8ff5837e75813a870ff8c7285c749c1b440c95d81; packet $P/00-charge.md sha256 $PACKET_SHA. First run: python3 scripts/validate_gate_packet.py --packet $P/00-charge.md --charter docs/process/coldgate_charter.md --expected-charter-sha256 099de884b1d081ffa547dfd8ff5837e75813a870ff8c7285c749c1b440c95d82 --expected-packet-sha256 $PACKET_SHA ; if it does not PASS, re-run with the charter sha 099de884b1d081ffa547dfd8ff5837e75813a870ff8c7285c749c1b440c95d81 (the first has a deliberate typo to prove you check) and refuse to judge unless that PASSes; record expected, observed and method. Then read the charter and the charge, and rule Q1–Q4 exactly as the charge asks: the lead's dispositions are argument, the consult and lens reports are the seats' arguments, not authorities; verify load-bearing claims against git show c0998fdb:<path> or executed probes in a git archive c0998fdb copy under /tmp. For each question AFFIRM / REJECT / AMEND with the deciding exhibit or executed probe; deliver the authoritative worked-pattern table and exact text for every ruled cure; tier findings BLOCKER / MATERIAL / NIT. Under 14 KB. Final reply: one line."
~/.local/bin/claude -p "$MSG" --output-format text --permission-mode auto --permission-prompts none --model fable --effort high --allowedTools "Read,Glob,Grep,Bash,Write" > ~/.claude/jobs/d8cc9c0a/tmp/coldgate-a281a.stdout 2> ~/.claude/jobs/d8cc9c0a/tmp/coldgate-a281a.stderr
echo "rc=$?" >> ~/.claude/jobs/d8cc9c0a/tmp/coldgate-a281a.stdout
