#!/usr/bin/env python3
"""Build the lead-authored issuance text for the 25G83 Revision 6 block 1 successor.

Re-runnable: every digest is computed from the cited file at run time. Run from the
repository root: python3 docs/process_traces/2026-10-02-interactive-d138/build_issuance_text.py
"""

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent / "10-issuance-text.json"
PACKET = "docs/process_traces/rev6-derivation-block1/packet"
CANDIDATE = "docs/process_traces/rev6-derivation-block1/candidate_acceptance_25g83_rev6.json"
RECORDS = "docs/process_traces/2026-10-02-interactive"


def cite(relative_path, **extra):
    digest = hashlib.sha256((ROOT / relative_path).read_bytes()).hexdigest()
    return {**extra, "relative_path": relative_path, "file_sha256": digest}


candidate = json.loads((ROOT / CANDIDATE).read_bytes())

DISCLOSURES = [
    ("D1", "Network-time OFF receipts. Both counting windows' receipts (sessions "
     "d079-epoch-25g83-r6-20261001T0617Z and d079-epoch-25g83-r6-20261001T2252Z) record exit 0 "
     "and the standard output 'Network Time is already off.', empty standard error, the same boot "
     "as the first capture and more than 600 s of settling on both clocks. Revision 6 section 5 "
     "as sealed named only the other OFF statement, 'setUsingNetworkTime: Off'; the recognizer "
     "admitting both was widened in commit 2431dcaa after the seal. Erratum E-NT1 (cold Fable "
     "judge ADOPT, Opus refuter AGREE) reads the condition as the OFF end state in either "
     "wording; the registered operating condition is unchanged and no number changes."),
    ("D2", "Thermal start condition (d) is satisfied vacuously on this build: 'pmset -g therm' "
     "prints no CPU_Speed_Limit line, the receipts store cpu_speed_limit null, and the night "
     "gate's existing thermal predicate passed (cold science gate ruling section 6 item 2)."),
    ("D3", "Two zero-capture attempts at label C1 preceded the admitted C1: plan "
     "d079-epoch-25g83-r6-derivation-c1-20261001T0137Z was refused at t0 (night_probe_error, the "
     "receipt wording of D1) and plan ...-c1-20261001T0555Z was stopped by the bench battery "
     "gate before publication. Neither opened a ledger session or captured anything; erratum "
     "E-NT1 rules the chain within the terms of D-182, amendment A-R5b and the owner's 2026-09-30 "
     "refusal route."),
    ("D4", "The nine chain logs listed in the cold-gate packet's MANIFEST.sha256 were excluded by "
     ".gitignore when the packet was first committed and were force-added at commit 7c0d4a0f; "
     "their digests equal the MANIFEST lines and the custody originals (ruling section 6 item 4)."),
    ("D5", "The R9 campaign record embeds absolute worktree paths under pinned_files, so it cannot "
     "be regenerated byte-identically from another checkout; every digest and slot entry matches "
     "(ruling section 6 item 5)."),
    ("D6", "The candidate's derivation_corpus.selection text omits Revision 6 section 8's "
     "median-frame condition (100 to 150 ms). All 24 valid captures lie in that range, so the "
     "omission excluded nothing; the condition was applied through the count replay and the "
     "issuer's frame_excluded path (ruling section 6 item 6)."),
    ("D7", "The cold science gate ruling's section 4.1 ICC row misprints the between-window mean "
     "square by a factor of 1000; its F and ICC (zero) are consistent with the correct value, and "
     "the figure is report-only (refuter on the ruling, defect 1)."),
    ("D8", "The ruling's quantile route shares the closed-form mathematics of the issuer's second "
     "route; the refuter's route (hypergeometric series, exact half-integer gamma, Gauss-Legendre "
     "pi) shares none and reproduces all four quantiles to 20 decimal places (refuter on the "
     "ruling, defect 2)."),
    ("D9", "H7, the first comparison of network-time-OFF captures with the network-time-ON "
     "captures of W1 and W2, is report-only science under Revision 6 section 5; this issuance "
     "neither computes it nor depends on it."),
    ("D10", "Scope of the default move. This file becomes the live default and judges identity "
     "epoch 25G83. A result recorded under build 25F84 evaluates stale against it; re-evaluating "
     "such a result under P8 (d079_calibration_acceptance_v2_n17_r8, still registered) needs an "
     "explicit route, which is lane A335 (OLD-EPOCH-EXPLICIT-R7-ROUTE-01) and is not part of this "
     "transaction."),
]

text = {
    "reason": (
        "D-138 transaction for identity epoch 25G83, Revision 6 block 1: the candidate "
        "d079_calibration_acceptance_v2_n24_25g83_r2, admitted by the cold science gate "
        "(ADMIT, refuter AGREE) and by erratum E-NT1 (ADOPT, refuter AGREE), promoted with "
        "every derived field unchanged and made the live default."
    ),
    "required_verification": (
        "complete: cold science gate ADMIT (Claude Fable 5.1) with refuter AGREE (Claude Opus "
        "5.5) on the candidate bytes; cold erratum E-NT1 ADOPT (Claude Fable 5.1) with refuter "
        "AGREE (Claude Opus 5.5). The D-138 pull request's merge gates are recorded in its "
        "ledger, not in these bytes."
    ),
    "network_time_provenance": {
        "disclosure_id": "D1",
        "text": DISCLOSURES[0][1],
        "erratum": cite(f"{RECORDS}/42-erratum-nt1.md", id="E-NT1"),
        "receipts": [
            cite(f"{PACKET}/3-chain-logs-and-harvest/c1/night/network_time_off.json",
                 session_id="d079-epoch-25g83-r6-20261001T0617Z"),
            cite(f"{PACKET}/3-chain-logs-and-harvest/c2/night/network_time_off.json",
                 session_id="d079-epoch-25g83-r6-20261001T2252Z"),
        ],
    },
    "issuance_record": {
        "source_candidate": {
            **cite(CANDIDATE),
            "derivation_sha256": candidate["derivation_sha256"],
        },
        "rulings": [
            cite(f"{PACKET}/RULING-judge.md", id="SCI-25G83-REV6-B1"),
            cite(f"{PACKET}/REFUTER-on-ruling.md", id="SCI-25G83-REV6-B1-REFUTER"),
            cite(f"{RECORDS}/41-erratum-nt1-ruling.md", id="E-NT1"),
            cite(f"{RECORDS}/41r-erratum-nt1-refuter.md", id="E-NT1-REFUTER"),
        ],
        "disclosures": [{"id": key, "text": body} for key, body in DISCLOSURES],
        "claim_eligible_meaning": (
            "these bytes are an authentic issued calibration for identity epoch 25G83, and its "
            "numbers may serve as the timing-uncertainty basis of a reported result captured "
            "under that epoch. It is a property of the file. It is not permission to start a "
            "window; a claim-bearing window starts only under its own sealed registration."
        ),
    },
}

OUT.write_text(json.dumps(text, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)} sha256={hashlib.sha256(OUT.read_bytes()).hexdigest()}")
