"""Fail-closed detection-floor extraction fixtures (2026-07-19 audit T0.4/T0.6).

The four cooldown cap-hit fixtures below are the REAL campaign-provenance
records from the 2026-07-19 recalibration corpora (recal4 su-b01-b1, recal5
short-prefill r04 and long-prompt r03, recal6 ph-prefill b03-b1), embedded
verbatim together with their raw cooldown trace bytes.  Each raw payload is
re-hashed in the tests against the record's own ``raw_artifact.sha256`` pin,
so a hand-simplified or drifted fixture fails immediately.
"""

from __future__ import annotations

import base64
import gzip
import hashlib
import io
import json
import math
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

from joulewise.analysis_engine.inputs import campaign_cooldown_evidence
from joulewise.detection_floor import small_sample_guard_factor
from joulewise.floor_extraction import (
    CAP_HIT_POLICY_EXCLUDE_SAME_SLOT,
    EXTRACTION_SPEC_SCHEMA_VERSION,
    FloorExtractionError,
    LEGACY_THROUGHPUT_FIELD,
    READER_THROUGHPUT_FIELD,
    extract_absolute_cell,
    extract_cells,
    extract_comparative_cell,
    governed_cell_metric,
    reader_throughput_tokens_s,
)
from scripts.extract_detection_floors import main as extract_main

_CAP_HIT_FIXTURE_B64 = "H4sIAHq5XWoC/+19aZPaaJb1X8nIT7NUerSyOKYmgjZUNfVaIigLu/DEBCGEUCJIoFkMUkX99/ecK5GJM5Uou4sGDUNHuMvOFEJ6lvvc5dxzfr9d+N5sMVjevr/5799v++vpYOL3RgP883auKap5NxjeeQ/zO7ffd++W67u+ot711dsfbm692WwymG2muPT3W7e/nE3WK7/n+aPJaBr0NvjxdD2Z4EJ3uPIXvbfd2pVbu1Pvfrbo+ZNRMOrjfqtIviT598THP1aLtY8LF767nE3l4f/nj6cPzhezb/4U//Dlc313iY9Ok38M1gt3NZpNe/yUXnqnqbpm6JpewseD+bo3XPh/693HvQff5asp75T9Xzxk/WbEF5O77n6nZv5u9PQr+fFmNMUA9pbr5dz3Vvjd0J0s+Vrz2QYjttn7pqpZ0srVclkpG6Zh6uW9i5arwcD/llymV4ySZhpaRS1XyhVVNXHd0n2Y48u82XrK79AVfv/Kn/gP/moR9fquN/anyazwjvzpyFvecjgz5mzqB5W7hT/0Fz6G9265chcrTtnzufo7PuotRquR5056/vTbaDGbPvjTVW/uLpf+4GmmX859zhA+LgGsBn/py7u/smr2v3c5defL+xn+cu9qZolPXx6WDQyxawxKQ69cNkoDxa+Wq33THyjDvlEqmWa1rynGwNDUgeGVSkZVU8z+sKxiOhS9xHccLmaxP+25fIpbTdFKd0r5Tq06auW9ab5XlXclTVfU0ldeO3p4WK9cvGsv2TlYeH689+Lz2WTkRfsP6CsDTalUy33fwLP4Fc3r+7pWVodmyS8Ntb5SHfb7Q79aMkpD/MB01Wql4pV1rWJiZjR+6WI9fdNkLb17/8HtffMXS2wiXh/O1hN/M1r673YWoZdsw3ffZDMvZ+sFZmE8ShYZb9x7vHEvufEfe/ak9/QoHpauOwqmdxwxpaxWV2rFNFWlrFdNw4jv5qqhVY273Sfv+v5wtvDvcg0Xnt4NuCW4M1Z7QzvwvRHfq7eYTcSMcQf20p2W7kS1YmhlvaRWMcDVCs2GPxxi8Y2++b31fP50ZblULVdKpapS0UqmUeVeHOK2sw1v/Hy8X33adLb3Bvzxdb8lM+duehjD0dCVDfD77dxd3fM6/OI/Xoygsz+CX9MR7PUeBz8Zwt6Bh3oXYvNM5Jsfjw5D50Q/LkjV97xSpVqtDIaaWdF8c+ApvjFUyyaWXd/Qy2bV4GbxXFPzTLVveLphYnGWPbWvedpA1kNyd3+QvWlK7/XqO1OHnTO/Js+yW1FvsESvHjxnN0VPr/HdoithLJUSFpJZqppVxfjuShxuXH7J4sA3eP6AK2z3mL3H4++7T+Ut1QXuig/2OCT+Irl7xjmPjcKBuHUHgxGfAWOX3Nlz5/ubjdekI/S4/5Y3//XjzeO/hgtX3uLm324whisXTzx4HNTb3YHH+zwe4Rt/FNyvcNn+dr35zx9vXu7I7969j7NQlsOL4caX/4t68+83K7zWQqZs91j/ylus7nFAuhOxYzOc53hbeAXr0QLr44fdCyZ7NDEtvadXWc5dWsYB/YDRw/rhcRzS1Z7cZm90cB/NEG8Bq2Y9WSUWcd67HyWW2F+KqXrFVGZudPkcn+Ol6UtfrZe+18tfcO0u1wuZSTu9SH6Nn9/DeixzHUE+/DJxQeS1Xky9LMbK02j0Xn2o5br/uDTe35hyu4xVw++S372cT/ku9Y8Dv+OEuiMur+RGpXeliqabVQ0jWy0bP+wt6OeD+WKlcy7Nd2VFqZRNnLllpaSWy08XPs7+3iPvXoLTtftxck4u5uulrN71dImPwl4Zvd20i7MxWixhtu6jpdiyNxw1ifXjSdIvGbzSj365707tb/2/fla+fq6GX79Mlu4Xc/qb7o1ao7+sB1+2y48faqPuw0/x1y/bef+hw5+Xmw+/qt7DT4r7pbr+Tbfws5r2MaxtrfpYbdUbW37mq/4X9Tfta/T1t5+G7l/nw/6Xz/f9UbPUrNfW1odN0HwYbAafqw/ew+ftb5o68yfV1dcvP62b4SywPhibp3tMxv2fPw/T79u7T2P/PvOvP28nv+m/3A9+nnzD/ebfX5PcY6BN1l9/ruq/6bbq6X+ZdPU23+eh+2Ubf/2E66Z/+TbQPke/6YPvn7cemHbYNW3HMq16V7echmE73rL54ZdNXx9MvIncU/n686+TweNnmpqNsbDCrt5ymqpVtxQ79nS+l6f9tPL4vJr9bfDFVPjOtlPj/RSM8wTfrXjTyRDjHrra5/XXD7jn7rse1Mngr7/M8RSjIZ/5Afd4+Bx1vwzkfv3f/rL8+tuvE97z68NPS0/r8L6Trw9f8b6/znHtcPDbXzZff/tlOIh2z+ppLccz+I5418gOO0rLkc9FX798xXd+Xne1v/dz20n3N/v5czz+HM8auXhO72Fyj/maDH6qLrsvn5vrR3V/w/P/VA37Op/lpynWaizrJGwn8zv95Vv/Z67PdN4m1cd52a2nVn2s2eFYteLxxg69reUEqh3xs/am+8UcdrWqzMng586zNfHrDO+8wr+H/YfqCvvjvs/5+Ouv0eCLPKPi/vw56n/5afmb/hc8rx0P8Lz83ubY/Nb/Mll3v2xGnHeszRV+r3S/qJt032ztOFDseqDb9Zr+Mexu8E4b2wl4X737ZYL18OvQk/EOON4bu+5FGGPVjmuxHVuq3He3rl+ffx3PPcaY8D01vM/9V8xnct8u7tvY4J6G5YyxRi3MY1f77r56MkbPngPP3o3tEJ+t/1r9MF2Oul9+ifvaVh1gr2G9zPs/4/NqMgf96edlX/biL/ee9pl2Rp4RNmiM8ZJ9i3mTebVHxsZyuqpdb8f26LmtuC9xvXS/GBy/DewO32/q/fXz8Ov0l4n3GXP0ur15bid299nu38f98usSayzCepz3Vc75d9ek9xhgvf36baBWMd/25usXW3k25k+24fvnNa24qVhhAPsQmK16m3smFruAsZb9xXv+/Ov462/d3Wdiy/Fog3Q7bCo210gcbG1Z+/a9zPln7o/P6wHXZr2zSdbb5+XXL2IvzN802HptNek/0OY9fhfW46+R+8WOm1OFz7y/x8K+pm5gN5Wvn3DPn7/e9/9qT8Quf4E1wfu6v33FOHzeeD/TZnq7Z8UzjvVWvQvbUDNg/zCPY1mnmL8HfCeewf57P4f3wBn07Dkef45nhR1RcO95F/OPdxr2f/5Jybh+O/gyibinXu6DppLOb4Q1nJyDMm9Y97t5ebR7461d7+iw6dgD2DOwg7JOC2NLGngX2mQvsuR7B/e0tbChid10Omv8MXA9xrmmYN9jfTWOYEsaEcYwsuMO7FgHtsHTrbhrWDI2T/vF+/mn9eMzfzK2sHeYdw97vgkfohZZU+X/Hdk3iXk2yTl12J7gEwbOs4b23Ifpf8m77jU/pbZuOWO+19aK23k2BvsAc+Jg3qJj+C1jnBHdyMJ5hzWBMWhurGfXezrszM+ftd05aYVj2KQA8zZWrNhTuSet6GpnzmRnMHdNzEWAuehwX9Pf4meTPfT6Hn2yI9qT3cCagV/5eZLM2T19yfv+T9UNnhee6edI3uPDL60+/Wfcqyn7Fuvzy2ecR/BZH+0HfL56G/ajDfti0IbA7/cyfJYm7EHTwFhjjGv471hPzqxHW/Dq3O/boUf/NrUZLaxTOQMxPnYdPnkI21FvfmebsE/ud/4ExnCN8xb7tRPRD8T6hv9XU4btOezFT/DHq8sBxhDfNXG/JH6kzMHPptr/ecP7juizij/D5/zrcvT1r5+TvauZe34U9hdsmeW0jcuLgbAWHforOPccT8GcYgw7eTEQ9hniHsfD+mjjPGqqiIW0U8ZAuE6V96JNePgcYmw07GPV++tfvosPYCdNnIeMEeDPInZz2qYt48HYCXvjixn+vZ/DeMPXfe4D7H4OH1n/ZQ7bCbvI8+Wz8pu2vX/pM8Cn/e3zHGtknLEXIjtdJ95DdZn627KG4D+k8+g9+Z1hc9uq1zaw7ZFVb2MveIp8Ntkrr+/FJ1uxfrQN+2O759d4f8Xzcm3JeVwbOU9+TmKXcE7gzOFZsvMZdPGB8SzYozgra3guxBQfMvyWcLzGmYRx9hBTBxLDtZxG/Of9FrHJsGlNnJGWgXM63uUxsmOgpvkxtOD/wdcKPQPPDJ8edumvR/dbYOOaPIONxB941W/BtV6ez/LsmoP+Ct8L6yV4m78SI7Y+ho1xasyVxDZtBeNzx8K518ixMdh7sEvwOQ2saTw3zhlnLGckfeO+xKJVtT8Vf0RN8gW/cg+KT+J/riJutRfY32Pxs9NnE/vzMAm96JeqzNfemnnm3z+eqVd/ZawxtqX/b0vOrMk49VV/Jct+/HPjIkv9iL0EH0BJcj/P7EvcXSdxXUPBuoINgO8c1w7GRU/vsOfTvMhTddZyPjjwqeuM/REvxlb8un2xMO9/OX5Opc64rMGcw/OcyXe+B67VX+Zd1EPXvJZXwXsgnnA6Gr77gO2Z7HwenqWb1O78yTxLI8Y4w39uxHKeOG3a0cO2xOlEEiPhjIGvyPgOZ1H3akvOYUucmsq1YDP+4VlQp381LpAtacccT9gHJc1vfGdLYGvW8AUZZzA3rtKewK4890My5/5A7BPZnwzELxbmr2HKs2Bdtz69ml+J6aMeP86x4O8iHo099QLjnC3sBmxFh/UerLnOzl4e8EHa8Ktp0z3Eo018roO57lztxpnsBuKcSOLVuLuVGtynV3OzWfmQf2qMgxh3zRwB1oqZaTfwe6w9xssacz6IRdRdPehP2w34yfCn8d82zrhacn6f1G7UYsYzOI/NS7QbNuOPuKslceRYTW3AwfwI/EDMB/7rNKLkvEjy8Nf8yKnzIw3mE1WLMSfjA8ktJnXQzPxIlj/xz821qnZkYI0EUcvxomS//8TxGafvyt/rsM1Ye+0Y129t2u3oQL716R0O5UZUqSXFzHVg/sI2YvS2aZ3cdjS3iC3pd10ivkRjXhVnK2xIDf4Dz9o8nwNxNuIqwQGEHZx1FuK7a97jTD7HVuZD8t1ejD1Kv7FAsUoX72LBtjVjO8vnCNtrnsnwCRgzK4iDWSs9hs+h0zfGnt0QY0LcSOvDie2Gg53hEFPT1S/PbnSZY9vK2RDSNjaSPPHB+q6liL+R1AB41uHMaF/txlnypdibTps4CfhI2C9OEz5/t0B2w9t+DHHGhI1tKwNHYsdN5gJgLwINtgXxDT6brKUj2I2GgnWN7+6qLdqj0/sbzDvhjG3ql4hnJSa15TTwjl3DZi0rDxcS14hLIXYN8TXsDmLaa47jbHZDEdyZ/OH+IGbIKpLdMBAzsB4X2Zl2Y7wmRoIxFs8f+ErwN46UG4Udwhol9tps1eETxwdwITHG8vg1W2ICsa9qybu/XrM1EK8ZrRzbAX8Svtnrddg9G2OyriUx9ijPjtRwz3GEGEPiyPSee2OEGPXnz6FgvPbX7xM+9TvbxvWH80v8ipbDek/TzMezwh9ErApfE37pWKWtv+Y9zoILIS5Kkf1IrKbjGdg3UYHyHgb9AZu53DQmeYaLx56T2Cu24ob4+rDh5nFqtgH2cod7CjZtjLNvfGpbgjPJwjrqbl7aif/tOHgLdoKxIWPmLvcL/N+cfKnELN2k5ib4VCtunRID/7T2/6/30zC3iOcLjBbia+YXbPZEfShOnQVn0BrPZrCWl5ErNa3IQOzbZT0iYvzF3Jv16Si5Uo0+GXwg+Mke7JGVYLlPmvNo4zxlXFbTLi92wZgSDx224e9w3TW3uXaDvqAzjiWn77APTDAw1zrLeeosGnP52JvcJ8TXMJYsTuziJM/I2r+dhUGV38NvjS32geL8wnqsB/Fx/A36X7UIfjGeBWcc4tGTY8RgN4hpTePJVzFi39uFTLzp5pAv8XifT4fsy+S7a/5knLIl/q1Vr7EXwbTChvTEJHWs1/MesBcG+2hYO8fe2mJ81OQzV5/j9D4HcwbBFvuCfQSx9CJEhfE5VIzlWnqtsI8zfI4tf49z2WTfruUwR8F+5O6RMGFN1m6IMzMZV58eE8Z91TDtNPa/JJ8DZ4EKXzeSOIw5egc2/3CdhXX62Ga+1Amkv9FmbvzT1W6cwW7Qv1cln18nFtij76cf6Nc9vd1w8C7sXwgb2XbDYX0W6y4MpIaLv9PWHMVuwO8Rbgv4xxvyW6S+9ClzHPTn+Rya9enyev2l75a+pNgAK97Fowdyo6rENdKHRH+jSxxgdI1VzhGrNOFr4KyOaeusjeXwedsFilWaWKeCx1LtzD5//p41og77ILCOLJMxy3FiFfb204/2GC8wBxSdPlbp6NxX+O+J+1mYuxy/rZ9Frj9KP4vUwdlrCD+Y+e6NHSb5nddtSRPXNyJyD9hxA/6nRVt0tSVnsiU4CzbwA2Phg3AQ64fNuDh1lk7U+mCoSf1unFFnaUStT+y7Z09OF3aRWEVPP5ItYY+WIfPH3ov6My6SE9iSVr2mkXsJ9v7EtqRJ7KfxNltiMSd0BFvSRBzD8R6bElMjmklt6Ks5VNvpEs/O52V9kP0t0bX2cqZ4pl4Tjp+W9CsSN9bWWh8KFM/E2NNSz8uq18IfHhnsq9XI22E7rKt21Wd48n+89kJuAMmFkC+lrZ2+9mIR/4J9ddgnIdcB1hrOg25OTNMklkaz6u039+4LVutNXENj3DdI+JmOgGHHvMMXZJ9AB3PQUNNnONQ3B9szxrMGW/mc45lX3+QsNRlV+FzCDuawQQ6bgsU57Yh9+9JjNcqKc9iLS9vDtdRATNJWsKaO1LfPcw/no9M22E9opT73afv228wZX2R+RDAdIbG+iE1i2KOwk8+rKvwSTfGlsSY25LC72o2z2A3E/YHwO9nEaNMHcJJ9V5CYRk1reLqVyU/W4O+J09DtuE0OVPouUevDUXwR4loN1hrJN4Zn2J6896XO2KJNrpHo4nAgTg3z2sFZZbE/2mjhjEh9qQO2o2NKf2eIa9kzQ5xOyk9zxbCfumeOPLbE7uBclViU3AlFwoF0dMGBPHIhf1+Tgc1bMx5H5KpbxGgSR3u0Wi45mJuYP65vchl4p67JRC3H2gr24RJrMtK/whpajRhA2IKGkotXj8lPS9wp7KmDz4SwH9f8x1lwINJLSvwvYlfBjzm1uEj1XPbTCobLaUSZtgO/F5514gNCixoB0ZHyH1zb7CEkz6Ox0xs4aaxCviZyv+VwjP0vxI9tpL8m4REjd/aGNUE7t9/WE84C8npYkjuvxVf82Jk0IJy2JtodMfl1uqzJmwWKVXSs05j53JRX93msoidcy0HUIheGfM56nt/8B+0G9Rw64o9ZcYPnYmSfPFYhlz77wtrmRerHsM7j1HTpaSYfspOXG7Ui2vAEty41Gs0ij8M1z3EW7mSb+EbptSWvGHkTLKNItqP1wVCkXy3to31uO/B71lkiS3CMnUjwXkeyHVZIjEEHcbXwZyr2ybGnDZ4/Rm7N5X+jz8G6a9xkPYn5b/iX7TixzQcw6+RZc4gx9sgLFAkHpXPl+DgTJzLmokncOjlo2PO+TbUKCpLnCFRyfFjheJuNIQsSjCZrK2FTtXkepVw6f7q2whowe0BZc4LtQox9egwZsTgh9W+8C7Qd9HUt1s/YE40/DS03XonJC1JTZL3i77bUca8cyGfTf6EuW512I8AeZW9pkWzHOPrI8QvHWrbtGMcfQ/JakleMZzT7r3YY9z/Np25KzMS+fKezfc4fcgqeDyvRqiBv2sairkb9Av0P2AFLtFsChf6m5SDOz815EPsDf9kht0Qz0Re75jzOlPNg/8FY/MAWeficnfZBMXKliEPWrL1iL8UZuVJil9dWKNxTuEbqzHgX70gcYzXyBMXSixyeHnPK3mGcQ3pag3wdcxqzPygPJ+aR4/GtGDHxt+z6W/RduHYC5Tj9t+RwgT/hSF8MdXPe0H/bkH59zDl10GKbefVr3eVMtqTDWhn7YbY493D+WykvYCFsCfNja8E7EBeU5Y+E1Ni1hKcbMRh7YWL7WLaE+qwxtXCJF6Puzcn76KjPxh6+RA/ismq2RivRz1QxrojXhKsqr2Yb4ezbiK5YTM6QhnCeXvOnZ9Kei6kXLXhfxPxd+ITdAnGMdbdWZFDvg7XTKNMPcdpru95MahSxRb92p/FxBD+EsR11zNrkdDRPjxOjb0jtynF0idzq5BcU2yhxP+uxzVxdBswx41w94fUmJ3bin15txzl0K0UzXfDf1LTe9UsVxHZQA1cwpmlu5oUGLn5PjKn0c7fqlkEOqyPVXphLjqmxjfuqopt4cp5k9g6MDdHDukTN27po5sAGME8oY51nOwzZW47wNmDOO9o1XjlXvNIUPq0U/62JhtyHAsUrYUDNQS3FSr2wG60PBntSyfWxpSZ7qv19DG518gMyp0zu/zitm54qVqEGpym57BB26xJ7WphjY76K+uhhgzZAz+dDJg6a5/CY/C7RLh919TfO4G8QG8Y1Wm/A72efbbtAOLFujD2MdcXaQ1affjNOMOTkn5J821bypsfhNjUE81gnBq3LHrtT5zg20i8QdpXLtBvU7GKthTylHnlb1Fy7ETYj0et2LDPhqkk4I6924xx2o4k4kz3o1A22Irve2RbIbijWyMBzsY6ShS9t8vfse9kIvlQ4tvHfY8UpcdugLgBxdMSLnR5fyvwh/R3rEnMcesJ975EfhH1x8B+sXP049hfZoo9N/v8GeweuPsfZbIclun+Sq66zztJUimQ7WoJNlzpypu1oEZsuz17bJJpkY/VY+FLJrbDnhzUOzuPp86PEQNG+xyk/kmlfZI2lrQu+1LGIbUGcmGtDTOJ5cM4ZSQ6ZPELXftozaUKRl05tMV/FnCP7jZL6fjGwYmEH/jv5mzuwI5l5UtUeGdInITx15KyrB+axcKYt4fwOyDvE/PHJOTyknzeWPoIUK5ZwVrzuhwRbYudy8GKG9cnYWm/jGmOvJPyfQHkL1xh5NVJM3RHiGvYrddgjgHiFfE9BlBfXwBfR2fssvBLEsYcd5cqffKY8ap3xJbkk2OdukbNFKZDWC/w7a01tati+LP7kSPpxpXezg9ijlugeHqtXnxqRMe9Jrs1APwfHB/YV3r17gdhT1vqIEWQ+1FJot/PwYkmPbQd+v7dNtMDIJ+ldfZLz+CTsTaM+D/U2FKtO/E6B8OuILZibgL+rZ9qNGPE5efzr1HpJezETXZQj2A2ubWLoEz0cO7bOgBcjBwHzxZcYy1iq6EvC92O/LXwJ4w01mFiwg6GlWYJfDzT7ils/k89Bvvy26A7D7m9EbykqkM8RU5eVWGZLy7YdwRpnEdYS11VTPVrPS0h9TtHM1Z+4iU6JWaf/Tm076wL75YRXMBZ8Ytih37HN75fDGQe7wRovYhzhV7/yIp8L78G+54D+sPQdYfS2Bep1IRffOtGRaOtWFo9pyF5cy2T9BT6HQhz5Tmfgz+dAGkqi70K91XFs1btn4DH1yCumWhfZp99g3YX5UKzBtor/5uLTkxhF6mxYHzXyRanXHMfZbEfC3UXuLKe7STn3ChKnsM+W9Uv4QZl2g78nfqjDmFBN6oAd9Uh2QzTdLdFMHSspR+NJ+2xbwn/cTvSFLyxOsWXOOvQRYT/YK9vV8uyG6IAJdi8gxoyaHFfe9PPUbQ3m/yzR5bG2CU94t0h1W7PF+gA5ZMLMui1/r1ILmfrXsHvwncbHilV4zw3jFeFJDdvK6bkI4ZeTV+wyOUzZa6glcQrOiNjK8zc04hlbDrnxpXeJeaer3TgX3oN2g7pp7G0OPey9QCuO3fA2otHitLFesmq1Fn8vmrPCLeAEWIOecqRabZKz53ko/EBv4DANfvzx9oeb24W76U3dB//2/c2t5z7M3VEwvdMUraSU1aqjVkxTVcp61TSMr3dz1dCqRq/nzWaTwWwz7fX94Wzh9+aaopp3g+Gd9zC/c/t99265vusr6l1ffRcuZ9MJv2jpL5ej2bQ3Grz9q27/+OHm99v+ejqY+OkHH79rfn+3vJ8tVnfzhT8cTSb44uXdQjH4XbsHxAd+v8XPZ5P1yu95/mgymga9DX48XU8muNAdrvxF79UvGPjebODv39mdevjSnj8ZBaM+breK5DuSf084iqvF2ue4+i7efIkf/Pf//PH0wfli9s2f4h++fK7vLvHRafKPwXrhrjhE/JReeqebSqWkqFUNHw/m695w4f+tdx/3HnyXb6Zq7/Sqvv+//ese3nDhiG8t37m7VHlXrVb0qqEqBy4dpVdqJqYLv5ffbUZTjHhvuV7OfW+FC4buZMmBmM82GOLN0zco1YpWMkyjbOglpappxt5Fy9Vg4H+Ty1TF0DTdqFZUw6zqplHiGsKqwXd5s/WUX6ErCn648if+g79aRL2+6439aTKLvCF/OvKWXEVZi2jqB5U7LB5/4WM+7pYrd7HiHD+f3L/jo95itBp57qTnT7+NFrPpgz9d9ebucukPnpbGy8WSM4KPawbLx1/68u6vLLP9711O3Tm2CP5y72pmiU9frlQrZVXTK4pruJru982SaQz8UkX1yr5RUXzf0CoVz9TdarU/cIcD09UUfeh7A7WkVZUy33G4mMX+tOfyKW65fe+U8h03cPW9ab43tXflilk1S1957ejhYb1y8a69ZKdhafrx3ovPZ5ORF+0/oK8MNKVSLfd9wzSrfkXz+r6uldWhWfJLQ62vVIf9/tCvlozSED8wXbWKBy7rWsXEzGhi0tbTN03W0rv3H9zeN39Bw8Trw9l64m9GS//do4lL9u27b6p8YrZeYBbGo2SR8ca9xxv3khv/sWd/ek+P8sLgrTCwJRMPXy0rRgyDVzV1/W73ybvEtN690dzhHdyAG4P7Y7U3wLBgIzG7i9lEjB+3YS/dbsl2rOBBsCRKGqceT8NVNMSUr0bf/N56Pn+6sgwDbeDiiqFrWA60S0PcdrbhjZ+Pes4zpzO/N/iPr/5N2x1MGM/R0JXN8Pvt3F3d8zr84j9eHh/7o/k1Hc0DJ9Vrj/Z0Xi1g+xcD7iyDL/q0RDVN8dyh4en4toqODeUOh27f7PerQ3cw0EqqqhsDDKA/KPuDPo5DU/HNYWlYdvv+AEZTVkhyd3/wchtpynuz8l6DfS3pparxNXmW3Rp7g2167eg6u216eovv1l+popVLOgamYpQrhtj5vT0F4+6t0hWCb/D8ARfb7jF7jwfod5/KW7UL3BUf7HFI/EVy9wxHAXtG/CJM64jPgLFL7uy58/19x2vSEXrcisub//rx5vFfw4Urb3HzbzcYw5WLJx48Durt7gDkfR6dgI0/Cu5XuGx/59785483Lzfnd+/ex+Eoq+HFcOPL/0W9+febFV5rIVO2e6x/5S1W9zgx3YkYthkOebwtHIn1aIH18cPuBZONmliZ3tOrLOcuTeWAzsHoYf3wOA7pYk9uszc6uI9mvFPkl8v1ZJWYyHnvfrR6i7OYtdvlc3yOl1YwfbVe+l4vf8G1u1wvZCbt9CL5NX5+DxOyzPUk+fDLxCeR13ox9bIYK0+j0Xv1oZbr/uPSeH9jyu0yVg2/S373cj4TB+qPA7/jhLojLq/Hhy7hfK/AH8NhK27d44p+Ppovljon03xXwqermBjczCiXnq57nP29R969BKdr9+Pk4FzM10tZvevpEh+FvTJ7u2kX72O0WMJs3UdLsWXZp873Rl3dHSf9ksErj5tqbaSynJbaurxUq27XKS/XltJ5IiNn5aZaWc5JYKiU/OkK1O6kVIZ7padcOJmTyEtLaiFualIWeAuc7PXPFQxO5iktSu/UPUPaqwkRTqlps8o0e2viFGkTE8+1YbrVDkk71cmCohrYY6YtY+xpbNUkdPRQ2mTvHQ60yVB2lim9LqkR2Rqs22H7AJUyaQfGutB0xt245XjYD5//CdTKbW1XBr0wWhCN4yb06hg7SvthvPPkHBKZ23qXEBGsY8IBxqeEpT69V276tbO1BHrF1h6RIktpZfLSr69/rmhlG9gPSQ9bQo8t0rJFsiNbpl8TWc1mpmzlR45tLBBS0rpi7zd0+5CE1J49PgBN3VojgzTsegJ5pSxrgzDI10u+TmdN+nTYNKNF6ps64S2e9k9o38V3EDriKZcoD4OxZovMliUznMOkoMilKLNJU1YXmhG2/bNl9KQUZXv7Ig8+ogrMpW5tZa3i3EnLCnnwkQOfKxpctWuIFCQh7pRS4t55XZJub02cAkIyVmRthJbI9WKtZNIN4feEuVNuki0+W5Gx//TnbUrrA3yiOm3JeJNAJLGXEwq+bJsSNteki0xoVMfwT+Sz6j+hrRf7rEPJ4kukBCBtDVt4RaqyJS14jTybotoh6enYGkDfcJzKRRQOjvZ/wZ5w3TM+oKyTZjnNIvknbGUjnJTQ1kxYCeFohK6yjZRtea3nZdx/KM5hrNgwLGkhHhsCZ01hD9lxTvZz/BPsCGWo2a6sXqR0XcwWJcaLDbbWsbUmL9ZBbI45knhd6O1EVr2YUJPLj3UoA4T1GRNe3KoTopy0uxUAaiK2xI4Myjpsd3HGM6iJ9jEU2Xb6LvCP6Zt4R2rBI61Hm7Bag7mvM9Aum7BjCiWAc6gA9I/heLtrBThEB4CxJP2gab+VEsARmSfjTZQAiZTLkeBrzDda9JPhf5FmL5cSgGc1qSF05pUkfqck2ejqn5yt1YYtefWGiT1JWvSNVRQpCPi9sC3rRObd22bkYRUrIg0qzybEOKS/gi0/DkWit5GYnO0cdeYIx+oZ7Ioi9JXO+BJzJQYltyh1arHNhudBkrs7KKUrrRN1thKQ5j7Y5WuLRwlw8TWcgP5HbJGGPyY0/FEqvgCtNsyTdLYf2VZR7yq7HMX3/gjOlZAyRAFlVXF2JRKJx4HMc0woz+vFYlOdjnH69l5KzbaN1Be7MDoR+lBtzRLINSU3OqnNP0gnshUfkbVf0ghgjq4+x9l8DjWVT2BeizUPo1A+hxOsW1KH9bIkZFRbJGbGEWnoLeYkwuaRpDA9w2KbnEMqT4stBae3G04nprwgfK5Lsxu0wzrPUyuRB2JLkdE6LMEdYV1rXAuMraTdGzGmfbUb57AblB0UKmOhLxO5x4ZaGCoR2o2QPjtlHrLqMl31o8hfNjX4HIbUQRMp9z+f/6iLPIbIxsCGaM/in1PEKbHQMsbd7UXmTetjymzQt9zQf2jl13Rhuy2cc12uCf59l1+/ximnjlPYRh92JTdn1Ttco6QNLVCc4lFaG88XmFlSlzgh1pbExl1d6JOcxmMr3xHyppRUTM41xD9W2D49dRnp3NlyHV0aTpW1blLwy9mK/cLWUCtHBoKyVELNaQh2hJR2V1/jPL6GE6hsQYZvTzsHP7BbHIlch9hnyml3SKubRXmotz4ZQkso68lhvBwcS2qbeLaN1MkcUol4p7YZ9DVIy2NepK9BDGPMesp4YxNnGufjUW053xq6yHGElIDoXn2Ns/gaDeZBY+KjbIf7o72jgSqIzfDWiF9J253Gvd/7Gi368pR7cLoqaXosOcOaR5LVJmU67ksKojppmbpnoB9qEkNyiflQQ2qqxAXCj2Mu+w30yopgHWln2EcTdq412LPlNbxYfGDuOVL8OM2oUL6GSGa39SeM1ne+hmlFhsKcDOzfBvEE4prO5miSMXGHfUK6YB/rnnL6fGgT74Q4Pm4ctBt4/7VIxcbdnDglQLzHOM7S8n2P2pp0MrbQO+X5ILy2tkllff48riMWaVH6v0LZhrWQ12MXJ/4mZRZr9F0oo7y9YsXOgRUjhSXjasFzGKSZf5yLQmDFgo0ldGU1M5MG0eE7dPnsxFXBVyB2fKwcic5M9jPW9VZkjkJPPTmdGUaN/atW4ltdGH0qsWXEmpJGmdRmGOM8XyT24DNTUgZnXyzSd6lc4dUXOX1tlnRynvR82pTgcIIi1VgMxMgptVgtqy+XvtSa5xbpHFtO15A8Tv1Y+VL2KzMv1NxIj2548hiGdPTE/xoX2Ndvsi886QcnjaqFcfaifOrlLmwHpXY7lPZ74gK4+hynp0KUniPOB+USGpSKUwvkc2xtSluy/8FpRJm2A3GOUKjWA+LsYXMoLxUcqUbbURHDINZusC9XS+mzTyu5HVN6s6HY0QXSqHJ8iSeKpa8FtrmZzwniiETrtkVpOtoSrpFrDuRMfgdlwcaU7TFgR+B3dOMC5U4N9rISd0jZuUzbETaIGaO9YH9HRDrvHQ7kz9uOBuOUpG+D+dm4c3q/o453Yuw0ukTqdsTHpMV3LI1SPOxTzucTorxMQJwtJYQUodC92o4z2Q5yOzHnQRwU40grLoyspdiO8Vq4ecjJ9Skr38H+1lqS/2WfMCUSUqzAEWiY4ddQMrbButkOo39K28GeHPqDm9YFytPZ8gc+hMQf7biV28PSZD+RTv/SdoT+PUox+td67Rl6WGgzhKcnbjLfrbaK5HPEHp+R/872OWLhC1NEJrxeY87DOJKspZ5ISrKfDn/C7iaVejql3UCs1tDg10f2BfocmC/s/Q7OLMprtNkzHeXLWjbZ70KuBJNxLT93zZOejdeDOSdFYsaYcjFBbBcoT8q+WYv9X9k1W8rSrQUDAFstMtrsgztO3yz78CkxpVG+Gefi9sT1la3UVoRb8vJ639ivKGuOvRD0KWH/7Q859RXWY7gmQvjHlG4j31giI3T1OU7vc9B2MLeoUpIN80IMeGHw6LJfQ/K84KyJsmIV9s2Si4d7rLYRDrDj9LHgfuzRHJObgjwimn1yPHoj6WdmX9HFxSrkJZQebWLwtMSHyMGWOl3OCfE8qtiahPf0ajfOYzc02+mKZDNr5eSkKFBtRW19MJg701O5zRc8p7bwdJBblHj0IMG5HQUj1iX+WWfNBvaCvodun5yng/18XkQuz8OY9DHmu6vk+BymzbH88EbeH+n560Zv4v2JJRdznFqt4NQbhtTIsGfIX5sfv9QS+U+HPLONiDXba870XPGLxziSfebETNBPj4qE80DssMazqTZOieycKfZRGOjC9+VQEpE9Id2j1Fts1hAFR038e1c5vT2pmfh+gzHURXIkxx1KErKexfwO9kmQz2daJ76UeZLxNumB7Fz9kLPx/iA+CJkvJY9bx9z5hMWIX7wo4djzXqm1ePCnGV/wDGJ/H/stm0fCljI2Zy8FawLkOUx4vE/M+8OzFfvqInl/InKi0Y9M+6HTs+FQn0uX3NOcY/oo7DXeXHOm56rTwn7jTGsRA4XzmviwIvkcreSsMXex1YucaTzG77vk1iZXYkQ+Z/toHKbw42P4YY707Kb9W6f0ORqxLfF+V79AnZco4S9G7Iw5g5+4zeULizs4h2vUJSImeivyzle7cSa70aTd2Nii/SWaS9EBTYYz2A2PPCMG4obMWov01Tq81tok+Q+LujVHqtM2GKsk2GByHZ7cbjRF8vwytRfI79Y1Je8WMlbuRvkcpazRejxL4I/WWANjHHnlTD8XJp34XsQEsBuqcG+lPnlB8qbM9W3lbEr6Np/nTdlbGyXjzL75wECs/Dy/+Y/WadlLoopGlEN8J3yzk+c5WHtuEoNzmXoLrI0Rsxu26UMoufWWROOFuQBF+LhpP6750bPxosPeqwkOq7EVvsHiYMNgCxrEb1DTLcWsPctzhLR/xKV48JfIgwwfKuzqx8GUkhsVcXTcpM8Dv6xxet6wkLpWOJsvrw+OOh+qzHFI/ugmsXhmbm2FOHThiu9ucc6x1+fay3JOTYWQnBHMFYjehVos2xFQlw1rq5YVr0TSQ4uzWbAqUrNrmkeyG9QRYu899bDYZ3FyDiDYDMxHW7lMu0E+SUsTzG59TK3r3D4WyWuE9I2DxJaTh+ZqN85Uk6WPb21tx9OFT6eeaD8XI1YZs39WobZBq94wMu0GeYLoNzkdrCXakaPFKuzN5dxJ7kRq12eoyZIrq+UEcY7GU/QxbGJfdY08jSdrRH7xrtZ6I9aD90TMqL0B64Hxp9aBdyQuIMb7niGYwHAsHD/5vbWB6DoxZ0JtLOmTu9qVc/XHYfxFm8tMeljHpl0kfyRswm5gDOOmnmlXwgZ+7zGeZlwMX7e7tZ2j8RIiLieGtavie7Qz8BJSW8oULtcL7I9rEdNArHroJeMcJjpeh2yHlfBi0ych95v4KNf86Znypwl/umpLr0GAvyf9JAXxSaIW8VpOI0oxKC+0sIlLJW8geexaovMUmPbR+lzamuAY5fub2un14RrU92au4AL14RKuBSuJaci/oOb31lo822BvWCfkedzBmTK+8gGdzXbwWRvkBlWsOFDZn1og2xHbI0OnX2RncRCGFve4Dj+aGtXksqP+cXyknnxDznvyejpd2I/T68PxO21y21+ezhNrLeyRi6RvmTXcsLFt5fXIUXsrJq6HY1JTRMf42utyJozpOCJmD/42udQlZ2en/YqFwJgiVvm4w3pmal03FcT2RoJXCXTquiFe0VtHqtsSOyd+WZ188+ytOXkuhPESuVnjC/Q7GHtoSf8yfTvMXcL9fMjvMKnpLZhj8ZfJ8XbFp5/NdoRtajzF1Bqg/paV8H8WxHawf1bOpDiT+zhsm/g9+3KYDyZ36Y5T5gi5Dmomt03h1mQcdHqsmCq+D2z7JcYrgqEhR0fcVBL937y+Fou9+broUrCWHQvfrnGNV87FX0rtlnZEfRScATpsulmgeIU9thvpmUz06577HOyxJb8odYCoI0vcypHiFfKGWuzf1YQ/9OR2gz0f9Hk6l6gvSZ77OOHmoH6LcLXlYUyJF1REjxKfswXzkWrLXe3GGTCmAbUlFcFxhh34SkXSWoAf+0n07JRUg/S53dBs0UYm3zt5dGuyHo/FPUjsPnlLsa4Vy2loJ89zcH5ivrt1gXmORmzXyQNm6aKpQY6ID/laC8SVkeekRYxqHOxwjde67OlxYuxrQTzFHugx5tBTCsRbaor2rOhfwg5nYkzZSwu/I9FqoU668pxf9B/nPKbOgcVcPvsGNevkvKXsUWwmveqXxz9Ibn7TkvpsF34uuR7b+ZrWPJPjjibcpdSmDTvx1ec4i8/B/jHWV7REd537NTlbC+JzUH9WoaadHWbGKjpiGUVqMHXmJJrCM3qcHnz20DYi6WVln13oRSfnH6Q+ruOpVk5tBftuTW73jF79Z/ZjzHwzeQ2Nt2nGsd/1UZ/mkD3ZSK6JfCvRUWIZnbpv2D84O9j/Rrvi5dgV+s3k9KA2Rtekrd/ps19zpyfn9qDeK3VfVcxJggkuEE6MfbSIUYjRMrNwYlg3a+Z+sU/IB4Rzbdez/ec5xoT/ro6zLxbbcnJOU5tci3XBYV4ep2lM3crmJtEpb0fSbx/lcZqyb5Eay9Rg4HwznrnWa89kN7g+yR0Rwz9EHNrYFspuyDlL7eeult0rh3Ellwf7LqUf9ph6k1yX1BhqqORFpm90Bj5k+iPEYx+0HYKHGR3Onz675hBenX4YdbTexE0oOtSJv3IMbsJYNOTqrMF0FDt9hgOYU416PS0nSPt0yanQvtZhzhTbWAnXfdo7HZAHTy9MbEON5U/Mo2H8Ul3J72Mba5PwdI+pgUxse0Se5yP5Ibr0CHF8YvoDXn4+Nfjxx9sfbm4X7qY3dR/82/c3t577MHdHwfROU7SSUlarjqboJbNaqVTLivH1bq5WTV3v9bzZbDKYbaa9vj+cLfzeXFNU824wvJvf3y3vZ4vV3XzhD0eTyZ3bX94tFONduJxNJ/y6pb9cjmbT3mjw9i+8/eOHm99v++vpYOKnH3z8xsXf7iazaYAvnD3MV+n36fym3UPi8t9v8fPZZL3ye54/moymQW+DH0/XkwkudIcrf9H7O26v8fbu1MOb9vzJKBj1cc9VJF+U/HvC4Vwt1j4H2Hfx8kv84L//54+nD+KO3/wp/uHL5/ruEh+dJv8YrBfuiqPET+mld7qpVEqKWtXw8WC+7g0X/t9693HvwXf5eqr2Tq/q+//bv+7hDReO+OrynbtLlXfVakWvGqpy4NJReqVmKmX+Xn63GU0x7L3lejn3vRUuGLqTJQdiPttgnDdP36BUK1rJMI2yoZeUqqYZexctV4OB/00uUxVD03SjWlENs6qbRonLCAsH3+XN1lN+ha4o+OHKn/gP/moR9fquN/anyVTyhvzpyFtyIWWto6kfVO6wYv2Fj/m4W67cxYpz/Hxy/46PeovRauS5k54//TZazKYP/nTVm7vLpT94WhovF0vOCD6uGSwff+nLu7+yzPa/dzl159iX+Mu9q5klPn25Uq2UVU2vKK7harrfN0umMfBLFdUr+0ZF8X1Dq1Q8U3er1f7AHQ5MF1tz6HsDtaRVlTLfcbiYxf605/IpbrmD75TyHfawWn1vmu9N7V25YlbN0ldeO3p4WK9cvGsv2W5Ymn689+Lz2WTkRfsP6CsDTYEd6PuGaVb9iub1fV0rq0Oz5JeGWl+Bn9Af+tWSURriB6arwmx4ZV2rmJgZ2aOL9fRNk7X07v0Ht/fNX9A28fpwtp74m9HSf/do65J9++6bKp+YrReYhfEoWWS8ce/xxr3kxn/sGaHe06O8sHkrTdVLmlouqaZuxHdzbATDvNt98i6xsXdvsnh4AzfgtuDuWO0N78D3RmJ3F7OJ2D9uwl662ZJdhrVQUTWlVFJ0pVQuVbmGhpjw1eib31vP549XKuVqWcNWrGiKUS5rGvfjELedbXjj52N+8InTWd8b+MfX/qbtTieM5Wjoykb4/Xburu55HX7xHxmnx95Ifk1H8sBxlf1gT4fVwvdmiwH3lEHz9rQ4Pc3VVb1imFrV9UyMWHWoearnlhSNG2WomerA8wbaQHX7ONR1XKOpJd8wPNc0Dc2TtZHc3R+83ECa+t7Q3pvqO02rGNXq1+RZdqvrDVbp4Ml1dtP09Cr7C1DBosKyU8qGWalU9Er5uytxOnIpJosE3+D5A6623WP2Hs/P7z6Vt2wXuCs+2OOQ+Ivk7hnOAjaN+EfuYDDiM2Dskjt77nx/4/GadIQe9+Ly5r9+vHn813Dhylvc/NsNxnDl4okHj4N6uzv/eJ9HH2Djj4L7FS7b37o3//njzcvd+d2793E2ypJ4Mdz48n9Rb/79ZoXXWsiU7R7rX3mL1T0OTHcidm2GMx5vCz9iPVpgffywe8FkryZmpvf0Ksu5S0s5oG8welg/PI5DuuKT2+yNDu6jGe8U+eVyPVklFnLeux+t3uQuZmx4+Ryf46UZTF+tl77Xy19w7S7XC5lJO71Ifo2f38OKLHO9ST78MnFJ5LVeTL0sxsrTaPRefajluv+4NN7fmHK7jFXD75LfvZzPxLL/ceB3nFB3xOWV3Kj0rlLSDB0+V1U35BB4XNDPB/PFSudcmu9KVVXDMV0tl4yyUjWfLnyc/b1H3r0Ep2v34+TcXMzXS1m96+kSH4W9Mnu7aRfnY7RYwmzdR0uxZW89dtTdqdIvGbz66JKWbIUk3OcCaUQQWhpCH5TImhEiEuW27MYsI9d0y2HrhrfBf0+Zin1KQ+SmT8a6FbbZihZZ9bZux820/SsvffL65wqXPnlt/rLSJ3vp4NOkY71YaJTjjmGlFBnPyjjGx5D0/t2YtAWtureVctSh1pn9d3gdVrK/byk9Qoj9AXr2gNKaJqmeLZZHpc23Yxwf2tqOBMaJZzoMbW3j+Ulf3BZY8u5PbrqWJbNYqI/Nvc9pbywjq3i27Z4U1itQWF7LtoKENvvPw9ooA2ZpttNk+XjLVr5krx2CtQWUMIyxR5kyjAhlPCmN0d575ZWDhDq8TmlEQqs80mFpbykHHfhc0VpwSAm4IQRBpLnrLOm/LhGxdyadJoUbW4Y9MhRbKL6DTLmqj4SshiwHENLWYLuMYf95G7S1RqR5arOMTBp80uJEB+D0pFwitYEhbU3SXtIxWvVfjw+TjZuxLa2v7QuUjRA6qhjzaCRj3sn1Z2yeP/WxhvOCUqksnSinLAft7Yk8mCxhmoRXs2zC1sUd7CcPJnvgc4WjReP6ZCl3Q5izncgFFcWWkKIZ56RQhGfToo2MmGdYAqm1YrZuWIdluvf8wgPlZYc+SoPU67EdUlKJ/lL3AJVAM/oYWpR/lTI0zlj8aW8t/eiURpuELqa7aV1efGQKhSVlrNjGGdeSdvAcelbx1RxKvtYoeUW4fkEp4S8+PqKfqpL6oiUUxtK2aRQoPmKr21qkccJGlAlzI7Q27Kp8ftsRP+K5XMw/4ptwDLdCzYpYhDaXLZAHfJPs55j+U6ieNdIAXaAkL9Zfmy2nsOHS+kfKIyPHlmBddNRE4p1yWIQFW9urLTmPLWEbPWVdhDYX8SrP+MJAVWL4S5GhIxbTsunRLOwvUmSx5a+BfdzZpG1yR5DyrjF3w1YRTWStTk6NxtYDzyAU7BKpBnBWYI45r2y36Ki5bX9hx0woWbuUoVAlv1LMtr/Lj2ccUpOQnoq2v0Op+01x6OFJ09lekzKR1EIZ/oeCeEdL8lDw79kujPP5ONRGlDcnLRnzd5SzamvW6amNdHmvS5SzckjRPabskEK6Xc63nUs10FGEfivu4hwJmENJqdSuduP0diPA3oQvjPnDcyNu6SjWqEB2I2ysWwlNYoavQdoj1n4owcq2046G8d4eCWJvpDUOlbHcOeRoYK8MoRocXV6MInlh0t+T2oIU/LGVl+/APqIcO9sga6bIvcZFpTW69BiFMi5CgxkLJRVpuFMa04LEKMwjbBK5nCwJvI7+EedOkrdnm4ZQqBnHoXCW7yTduIr4x7BIhXHyOKWpC0VJaF1inBJJC460sHUxd576JvlMyrLTRwmbPJu3aa68cG19/wfquIbIxyU+EnNwO5nKIlAp6rbkLxq6UG7GWa04XbzrmPKLQrXMc8sKn7XM/MM+B6nimvAVeSY2WM85PbUR3yempHpOS7BDX6Cd43c02NakvA0XEpBaYZPSG+bRCxDLkVDf/nl7YpA+UyjoiAuqW0auDE29k9BAi3wOaYE8zY6u8ct54hfmt4lfYq60Qdo03SpQ3gP2ZA37QLzXNouaVeiQ6pRIa1CSl/EzsY7HoTuiBK8zJl6PODPE6M3TxzCOJfi41uXJ0LBWy71PSd2tYNUQn+RKalJWnTRJTlNN7Hw3xQBdbcfpbYdHShJSZJqkBKOsh12g3Adi2DUx0JTUzsiZkg5pK7VmUnUST8Rze3QkGRr62Y5I8VJ2NDq9lAR9kCZrmJdIsYi5bWzt0NJFgowxSW6thX7KmPR1mtRqSP2f+GjXGOb0MQzmD3ab9IrE6zCmOYAfO30Mw/xGW23VG7tax3c+BymPKF2VnM2CsTZbx5K+qweMyXHvpmHV2+qOqu2EPgdpwjY26UhHF9hHUxe50lTCpIbYOZE3PCyb2dGkjya0SFu6lfziNV45l2zmRuJMx1JJvQe7oRUqXsG7SJ007GThTolLVYTyRWJw0kR2NPsoNCTeBnafMuGR5OucxhnypsSdEaPd0S+QEp5Ub8xzqILPpQRmPU9KghSapAyj7G8jlvw6fJZrzeVM9Kzcb6TcIpYh7mI+alqBai46/GOMX4f+bFb/CymMVNg+ZhiZv1eltnkk22ET/1Ln2UasSXCGeIX7qquJHA5jyXrtAuUzKSsjeTYt6TdgH6WXLysRImbZ1Xmlny64xi3noVRUYcsp2UQZly1pWVP5hoLELZ7xMeTfibHMtiF2ZGCPiVR3hLMaPtRYtT8cKefhdLCHiX0m9mKsnwFfqolkS9y4RNsBv6q5TeqvNZ4Z6hv8j4QqX+g/KfXaVltXfOmZ+uWIuaa/z5xVB/sTdrxAcQtpmlsiN9PJypWSCnwteAzKTYm0EeXwOsfJeVCuop5KJznsAeqcvs7CvhrKIl8gdwhlThPJbuwP8oDkY8VgvwMtoY3H3Mvf03rx1XacwXYw3iQeinbDY+5ALRI2nVTOrPuz1pJpO4hBJVaRkvEOa3fM2R9JPjMmLpw2daxKredZr8xpbAd9r0vEmRIT3I4QJ+sJZ0R3w7643BptPeA6jUSqgDKBYaBe8R3nsh0d0nhjfyC2Jo4ixBwWp0arWtIDgfg23vXbPKOBR6z1UWibvaRPIiTGydKPI4XXJr8GnoHyGqzVdk9tO2DTPcZMyf543XbEVmQYOXXaZ9cc5BDSpT4ct9+CFVOEU210nB452AJijRShEa8L10FODMPn5P4SzBrr6ZHtXPMfZ8p/MNcbJ7w3iAOI43Oaxcl/4Jyi9B3xiGls/Dz/EScYTeaCKbVGmacjSUrElipyG1yfzIM7J+932RDHl+QKd5xinQvkDWJ9XOJR4tG3rXrKhXa4z3Yjtd6wmeDHuMfSvN3VhpzchhgJzpT8fcRmeTtJ9oLYkAbehbwP3iYLb2qRV4b9VzH3eo0caliD3pH8EcFrRTwjYZvIc6WfXpqX/H4N8hBdIG5MeIIM8l1KDJorg0cuGuJ72rQXxNbDX0t6Cq7129PXbykD1JLcqcjg4tkbBbIbTfZzRGkv1QvuQow1MYeRcJayb6feNo/Tn0/7OY6Ea7MOvybsnsFmCF9O3HK8C7QZna3Ep6HH3lm8p6fkyuDxbGCfbZ3+BsamPlavudOz4cViYsXIm0GeFZv5x08Fyn+EwRrnhtQ/snKnOKPY/0JJYdVyutIzdyS7wbUsXIPSMxN2tvbJ67U1jfgX4iovsF5rEjNKnlr+l375G7AeKvN02Ftmes6Rq/fKSXg2TkL6wZRMJifcWEl7Ogvib1jYw1wjYzULow5bwThGTbBiDXJbkgvDOFKuI2qJXCFrUcTBjM+AF+sqFu15PL7EHAf7WiKpvzrkohqnNv9QjoPS4haxg7pggOPdOXH1Oc6BUWcOjnvOJoc35qVA9Vr4Gk3y8+CcGSupL/HMdniMZRT2v5BL0SIfWt07EtaDXEPM2zUiwe6nXO8nzJMqrKW3HMtsXaROTFu4/e3EBpC3Tc/XiRnrkneSvDnzWePttV57Nl51rM8O89obmzl99oJ9KJLtGOP85/6pRZnxSsx4Bp4m+8e4x4grP1ZPbYh1GXa3POuk3390cl6gjfBnhZ1L7KndUo4dtsCgbyVYwLy6StxmDz5zWlrSF+Mp9uhqN85jNwLGmuTJNATnUa+l/V8FsRtOd91iTEzNhUyfIyD3lya8DognmLeBj3CceEXqoV3WhYmhZi+ncuJ4ZYu5YbzEvrGDtqMlPPNjNdXTOOB7BBtys7KP+o38QPBFrU3KOZ2D+WCNLlCOg/mQcyyS+MRhfsNS07z9oboL/U2u6VSqnZwuV76xM9VrWYekLlxsMxcSCgdcgfIgzHPAF2CfZWa9dhxhPbOGp4jOh9RePOVIfGPk0CQm0kj+nDyWQWxJXouEE/rSeuVs4bJuK/AzjFbdwp+8fhf2EBAjxnPGIi+yyp7ka/70TP22jPOdAOctdQ4bmh12C2Q3mONgv2vbsDJxp2PzI/wG9k0lOU76Dm31SP4I1nZN+F9hi8iNHJ8lfxqPtYvkFaPPXmc/c6KXg/kzcjHrcYO9uLrkTevS/6JcecXOFcuwf5V+YlP02xhb2kXKn8bBGuc5/XktU1uu7nG8yfNBPh9DcIfH6pVjD7nTJO4sxVCfhZNQpebA5Wk/Sb8L40Ry1zJm0/jffD5TyaHyfGOdfmPFXeXqc5yL44O5QdYsiJ/0yDVbII4PcqQbcUv0v7O0n7DmPhjbRBeV/S4Wuci21vE4CVWJWRycizwbT67jwvrCWDR2Ly5eCRFbOuTBZ09P25Se28P62JHgf8i3Qo57OZ8bV2zpefQYWFcgn5Mi2Gvx+WsF0ozrmNbIUImbtzN5PZqR9ckgJiO22B/HfQ7/90hYD8YqWJ/knmkarZQz6bSxiryXkvb2Xhq+FPMmGkIq66/M3+diPeIGbAfn2DLJI28TA3yNVc4RqxDLYCT+uOCwddEMjYoTq2CdrG3qU4UdPTNWCYOEI5m8OQmujPxfx8J6UL8Ftp96lsS6tk8cq1Bnh/293Y19ebEKawbsYSReg/hSrL9OPtZDcKnMj45V6Q0Pa1d86bl8DvYXSW8i4k3hEa7pxfE5yBNAPsKAPXrbTNsRwz+g9gdzqCE13ljTOhKvh5z57Q1rt3gWw3qGPzuB7YjIt0dNVyu6OP24mH6cFbdFV5M4wNQ2v15bceADOtTTa1JXWRUeofDaQ3uWmqzDGmagsT4O/3xri/ZOgWqyrGeEY/IBpRiiZ7WVsB19DIkJYf2yQf0FhX3rx4lXalqCOWBs3eSf6PRYj9pG6pA5/XA2sR5ON8d2tPGMSQ7rDbwe5G/FmL6F1yNIfNVPx6jVEheIcZczoKPZMfW/crkJDeGejMfkJ6MGtsb1cPVFzqRHyZ78uEY+dfK9IObqbgvki0h+w2I938nMmyqtT4aZ8LGS30602NXj8Kp3TdZoYVuUxBepnaG/lr1Hgsu8wF4X7hHm7IljaTM2id/A54HYljwerPHWkjPnijs9U6+L8MNthVfFEV3QbYHw6lqS3yAnnZVZq5X+2jp15mrUrKTfoB9JxxbrGbYj5n/Jd2VtregcOrbExnX1i8SHCfci6y3kXGpG+RpQHuMXU3zEsBnbwoHWucYw59GAIq89/EWc7/UO+/OZRyhQDMP+WuYfmjt+9GcxjOBO9aTe3CAmg36CfiR8GDEI9KHjVt2CLRufnEsM+0kX3/wC8WE2eYDqzNtT+w/zm9uXbzGuMhJepjFt+ib9zNVunB6PbhKzSd1J0REmliEuEK5UchvU0w1MO6svPxTcKfMSgoMQft2weSQOQvqKAdZ0wiFG//H0+te0hd5OK/fCYhXa5KZiiY5cQ5PYY5Tnc7DfiFq1WA/CCSQK4VfbcSbuQexPRbR3iO9lL0ixbIf5MUx5STPzptR3IVdym3U7zWaPnHMs7sFaolfLHF7cYW5QPbXtYP4v4Ye8OE4PagXRzmuC4Yk7rMen2qKv2g7hHUt5r5McOfNcV5zHeXAeUmshJxDzHNQPbZsFwnlo7K+llqntZOq3EAe7Zg6RWBXhEYsb5pHyo4bwXMXUlPISXdVPJ9ed3FJfgjwWF5fnQBwoek9xc0NfF+/6BrsRKHIWO1LXjclDc62rnKWuwl4JagsQR2FIn0BythXE3+jGH6ntw/xLZo6DvbPdGOsoSjgKOyr83iPlOASDBP+lKxjIM2gvkM/NZGxvX6Buix02DMGIwpfDXiEnvJav+dSlDqghuRH4E8zt21e9uPP4G6Elega25LnbW55tVpH8jVjwBlHKo/+8Hmu2qGUbEkvaEN1k+EvKcXiAiFXtaMKhHNJ+tNXT11WITWM/cOMS6ypGgp0R/lJypURvyI+yN5q6CuQjMSU/Eneuffdn8jmsmDE0/D/Yc0s4L7oF6mXp6q2UIzGTryPm2RxoojPj1JSkdnoUTKlGLl3mX8V+kV/GydeZvP3h5nbhbnpT98G/fX9z67kPc3cUTO80RSspZbXqaKpe0tRySTV14+vdXNMMw+z1vNlsMphtpr2+P5wt/N5cU1TzbjC8W/ztbjKbBnfzxexhvrpz+8u7haK/C5ez6YRftvSXy9Fs2hsN3v51t3/8cPP7bX89HUz89IOP3+c9zPElffdufo/v9IejyeSur+h3fZXftntMfOT3WzzLbLJe+T3PH01G06C3wY+n68kEF7rDlb/o/X1f4cpXuFPvfrbo+ZNRMOrjvqtIviz594SDulqsfQ6z72IQlvjBf//PH08fxEB986f4hy+f67tLfHSa/GOwXrgrjhY/pZfeGUpV1SplrYKPB/N1b7jw/9a7j3sPvstXVN4p+794yPrNiC8od939Ts383ejpV/LjzWiKgewt18u5763wu6E7WfK15rMNRm7z9E2qaRpaRTF1xahq+L/S3kXL1WDgf0seqKRUzIpRqpYMtaIbpsHFgeWA7/Jm6ym/Qlf49St/4j/4q0XU67ve2J8mk8Mb8qcjb8nlkbU6pn5QucN8+Qsfo3u3XLmLFWfs+VT9HR/1FqPVyHMnPX/6bbSYTR/86ao3d5dLf/A00S+nPmcEH1cAFoO/9OXdX1k0+9+7nLrz5f0Mf7l3NbPEp9eMYalfVYeuaw79kuv3Pb1kusOKgv3veZ47MHTDUHzTqCpmqVIu+RXP7Jf6ZknrG35FGfIdh4tZ7E977kpuiH15p5TvuDO192r5vVJ9V1Uq+PxXXjt6eFivXLxrL9lAWHd+vPfi89lk5EV7D1j2lYGmVKrlvm+YZtWvaF7f17WyOjRLfmmo9RX4Bf2hj1VRwhsMTVetVipeWdcqJmZGE3u1nr5pspbevf/g9r75C1ocXh/O1hN/M1r67x7tV7IL332TvbycrReYhfEoWWS8ce/xxr3kxn/smZXe06O8sGQrDc+sVEqlilKtxrBkFV2p3u0+eZfYzbs32zG8hRtwa3CHrPaGeOB7I7Goi9lErBo3Yi/dcMlOwxMoZVM1VUMzFUMxuY6GQyzC0Te/t57Pn64sa5pmVjD4WsUwK7rG5YDbzja88fNxz33qdPb3JuDx9b9pu5MHYzoaurIhfr+du6t7Xodf/EfG2bA3ol/TET1wFL3+cE/H0cL3ZosB95fBl31aqBXTd42hZ1R1ZdA3vZJS9ctmtV/VBtqgr5Tx1TBghuZXBiXdw7gN+gY2WF9XPcXvGwNF1klyd3+QsZn094b+Xq28K1dKerqZnlbaGyxU7rl0dlP19DrfLcaSWTKrMD8VGCKcEep3V+Ls47JMFgu+wfMHXHm7x+w9no7ffSpvCS9wV3ywxyHxF8ndM9wBbCDxgdzBYMRnwNgld/bc+f4m5DXpCD3uy+XNf/148/iv4cKVt7j5txuM4crFEw8eB/V2dx7yPo8n/MYfBfcrXLa/jW/+88eblzv1u3fv46yUZfFiuPHl/6Le/PvNCq+1kCnbPda/8harexyg7kTs3AzHPd4WTsN6tMD6+GH3gsmeTUxO7+lVlnOXlnNAN2H0sH54HId01Se32Rsd3EczxJnAqllPVonFnPfuR6s3OYUZG18+x+d4aRLTV+ul7/XyF1y7y/VCZtJOL5Jf4+f3sCbLXH+RD79MXBR5rRdTL4ux8jQavVcfarnuPy6N9zem3C5j1fC75Hcv5zNxu/448DtOqDvi8to9dFkpK6UyXEkYsdIPewv6+WC+WOmcSxOfVzA1CveZolUqTxc+zv7eI+9egtO1+3Fyji7m66Ws3vV0iY/CXpV6u2kXZ2S0WMJs3UdLsWVvPoLU1AryhOmXDH7i+O1zTd1m+9zoEltv23g3b4sQlTQtCCnfkF4lnUvYiC2WymJLE8nyU8LW98rUeVCQRAYwMAlnEkqkeiLRkwcFOfC5gkFBCFnxFJu0b/Xm1oobpAh+tTSztyZOkCYRGn6236at2paZUdI1SF/I1L5NmDtL05Q2OARd3xvHA6mSvb3bYQubSMsdoArKfo7fjt+OK238hOd/uEB7IlSFlAyxTIHAYD3myzYEAj9uOQ22Bm1JBXDKlOvee+WVawh9gS0Ya3Zd2nbwfs23lGsOfK5YbTCkbmpRLoqlTLbmOu1dS1JWuWYv7XuCUq9D2mbK2nKfYjwz6U4JD2mSumoj0HOmjh0rOlTq3RvHAyWbRoTvJW00U9KKtIeSZvN16Yat/clQSFdi1wnVhp0Oa7DPvxy9TZftpyxzpiXAi4KqUgYUY6gmbYOEnDUjK0+2EvaDlABC8ySleUp8nbQ95mlf5JZxCKejlG83gXKybfBNZZzXP1cwKkPKucZsqWO5QqRv6+PXqQz3z/Z/fglYpcQQ1gtsBn3fwMykBxkZhJYoAl+SVrxaZH/40/7JtvXBiHHuKULZRmkA0h/EB0o5IeWu2qmkQIfrG2v91+Pbk5gyexahgpdnT0hv73RjkaYgLSrnNadNl3BVtl2ShtNySI1FyuluIaHv/wfiHfroW5GPdTxSjGIfd4oU70TY16SB0FOavxeQEikLs82zPk7aN+vtwxDWt9kT2mTYM5b1x7QpJs7AR1hLtj0Zr0mbw7YdrOkooSYc60eHmVA+q056wI5xeTATT5f2LdI0ODiTSdWbZ08IW2b5vi4QbMKYjas9OWP+BL4T/UvbaaikorPjglAQSbzD9l3GYR082zjDnlh6IpcoVMuks2Jb4ZFkYTqMxUmFA/+ErV+npmhvxPAd6csrOdRlGvaVYefYDsRfsHftfH/kA/NVpLr31D1I7St2hPBBtlEkdLJ/3j+hbHaDkqs6pezYCpmfP6nR/+fZoyfrYFxQmPz/gVgnDkye7VYCy46xfwpChSi+CfYRx3N3Rn2fO4EfsoaN4e8RC0keLtrRFP1ZyBrlLm3xLxBzCW27dXIqAMSdOKexr6NLpAKwVFKnWnFnK7WZejevjoMYqCbUdhbpIR2ce6n81tVunF7uAf4jZUg3mDv4k2w/6xbIB+kQjos9jOdLpeG+90E6WMcWqQIMaaEOu4kMwIdjweRZ2yK1EXN6VnR6KgBSw9biy6QtaydSgk4N55ZIW2r5+VU5T0jJpFsO5abYpuNd45fzUAHElkget7E/ugalAnF+F8l2ID5hnOspWfJ0GGO284o8assZxy1psWkcx+eIhb6EEt7cw2eIXyjHRmoGa2tfpMRUl61deL+O+BuUJc6Vp6PdII0d7UbcSPLvxaQ8vPhaL/NxliMUchs+t7RIFUOeTtaFzXeJx1gnzex4RXIUNaVF+pq4I7XW40hMwY467Vha1UM8S9w9A+Uh8y7EWY2jS6Q8xLxSmghxYEDJACVXKobSx/Uu/UDdqguFiGZf7caZ7EZAbAjruqYlcWdQIH+DtGRtXeK9LJsRs4YaSNttizkzZ4z3aR5J0pI0npQXbxPHZLylLe/I/saWOZ4WawqX6G+QupCU+PB5EWPCz02onQ76G45QM5CqTIHdMFvONTd6rhxHqy5xPP17nvERznetQLlRtvOqUvMYZdmN8RpxlUEMF2XO8PzblnMsu0F7H1AeHucabevp4xTKPLYoc355mFTDCim7A/9wJ2/r1Iz8mgrt+Jh0gDrWhgn7oV3txpmkcEORYiHuEnMXwN9IZdCLYTeMJNfA/HlWbjQgDQDpCCmXSxk3UgKox6E6bCiS63eYP+H51jiDhDbi9zjQLrA3xhBZKZEE8LbMfaf42kNSMMyj0t4QexOzzsZ9dbUb57IbNdJz6CL5KpQd422B7AalcHXmLXD2ZuFOTSsySO9tCpbZ6QhVz5EktDEuQsFH2QChoT69hHYzkcN1EnniS6MeElk5xyIVLM+GbZqTP0w95HR1kfmMpV/AtOqda03lPDUV2HFSc1FGltTm4yiVLihIjmNMDKlOqc1MemVHzkAjoUYcb0UGqx4ciXoI/g5lA9jnVSdOPDg53SFiSI05w5wchwr7ybqT+tI3eYYLc6y14Omd5huxYW1TaNPfhA2j39eOjySxjdiT+DDWabGHSCmVV6uNLYO1Qa4JocxNxu5qV85jV3T2j9Avwfohto+19OLYFaEsG0uclZUDoW/7MSQ20VPYsyk5znpwLMkHVfDwIj8O38jpnpy2HXGUIX25cfdCJR9IL00cjcX+Y6OVL08XW3EHYyK1XYXSCFZ49UnOZTuEmpJS6Y7kwrXCSOWK7WBfbm2/J/aZ7WioxIEk/m1gMAfMXOuR8iARfBHmZemXEKelnFzyoc55CbBnrAu0HU36DyriRdblY1JbvgEjRnkS3Yox5+yJYc/0p2u99jz1WtoK9sxxj4yVJ7+xEDgP4gjX2LO0HUZGHoS9/mvYDJzPlOZh/zBxpkeqvQiNNvGd9K3ZB3eGmq3ThT9oqS2HfiH/dC7PhrAHn7GYjHUAW9nQ8uVxPXLakHZbE6kjcgBccyJnk6uz2D9BKY66xZzIbp0WxP9okr+HWDCtlSUBwRwr5QPIP+BQ/trCmeQdxYakfCOKyOk4jLebZ7AhY11syIdLlIAYsz4N299Q7RA+Xjg28jnKpFeA/C+sA+icb/vD1f84k//Bs439X8yF4+/NzQFOodP7H3EH/gX70oJXYhcLe6yjtgTjzD6Jpm4dRVrbi8WfJu8e5hC2wTh93EIui84uD3VhXB/ST0CpA+aBYR/xnvncQcxp0c5sKTdlSUwbXH2O8/gcqk2fmPySlKkQLF+Rch6JRK4NXzZTdop5f8rKEa9MCWxKiuDao+U8KI9bpyxah2f/6aW12UdcD7atC8Sa2uwXYp5KsGBt8pxuc32OmPknS5O6OvkPY2uTxtlXn+PkPgdx0IhR6DvSjmCtFgf74SmtT4YqvVNOIwMz1sC5Qtkpchg2pTfOcmrHkselxCTxCBrPOZyN2snrLCFiFe6NcHyBudIu/UPNppwX/Y24oeb2tlDayGEPVi3t3acdueY5zuZziKQjseodcmJHVpH6W+IOzt6u+B5WJt4UMTJxDyHjFObfiQ0dR0eyHRuR6sbZJpim8OTYD6k/CPdqDh8QxkDLsR3PrnkNN0YMB/2Ajtb68Ba8R4P1uegYUtvCRSVcCh3GiPAnumpOzpRcylvpjXGIP8P6JWfDte5yHh+EPPkx+0Qa4odYxO0UKO9hh9aaWKJdv/0zO4KYxqDMHZ+fXIuqFQab1lE4PYinDqQXyKLUd9wxnt33BPjTsS4ywHHCeXNhnIQqOcmsWPpr8d+xAr8kD39KaWRTbDy8WvohtnP1Qc7jg7DviDyeHdg38rnV0v7ogtgNkcxlHjfQs+q17LHlecXemJYj3ITETB6pXst+/JpGjiSLPohzBh4xYoPD9Cy+uJ6XhAuCtSzYe9VKsasHe+Xo88QWdQNikdom38s173Emn6PBPjTisjGP4nvoBeL0gO0IyG3BOrKabTvGa4614Mjq1BiiXPGRsB6U22aNVPhCyAPePkf8skFsqbQu0nY0mGujD4FY1WPNVs3NmdZFYht2wyOXhCGcp9d45Vy2YyNcu/TzHT5rzSxSvII4mH6FIjn2zL4X9tri9/GYOU5il6k7daRe2ya58jh3tKnkGYlPnDclX5ZCfmCsqQus1ZLHvxlbDn1eT2EPrZ2PT2d+gzz6W+pOIebZpHHONWY5fd6UPQUm7Bzz3qpw7hWqVjuOYBvwXF0ty+/A2lnbTpe9UeRSJPeDuuM6/fM9c5g/1nEci3MYn7zeIhzqDdZcLhBX2hC/g2Nr1/H3cJzLl26zJs8ep5C6gG3Mj6VefY5z1WnJ60F/saHaiKsLxkGot5zxOuFUbcSZ2lAY76Qnh7h6j7hY04qO06MPf0aV/Cixj07tkNbcPylHWlO4tzBH+sXlSB3i/gTLTG4Wg/jhVoKheT1HSj5Gh/0swrEbSY9//dpLe6YcqS6cNyGfkT2KDeq3FcbfIA79Y0jOkWaKAXoWq2CsP0p/g/TQRsybHYvbI8GTEtOZasqdnNuDucAu9WguUO+J+Q32+bXJJ2YIT0c+LxBr8cQXMyeO9dEmh4N+5QU6Cy8QYhQPfqJF3vqt5VCLuVMguwE/I+yYTzz8z+0G+2wDwZAh7iX3qi6YkONgSjWpOcXUfsS6/nRyf0MTvs7DudGtFRm5nB6WxHNv5fMg96Kl5MYsrIeLxk/3KJotPAPIc2CRJ0z6D3JjF8Q5tDdtw6o3NqJXhvG69rWcJXZhb6IpmkKigcH+kEaBMKZBZFGHEj5I2tvxXIcyQgxu0O4kvX0BPnesGm3CGyG9V7Glnx7bwf4vnEX1jnbY/+iuM7g+VoeuOWxHyF/SjO034cTYz5zEVUfgBdKlvz6mFqVHm6Ln8QJRK1A4VxgDIW4V7corn/qZ7EiHXE5a0udM3jEr7VMqRA4E+9jDHiBee6cr+SwHEgbkucI6kvHe0H84Ek4sJiaJuQ/6l9TTO732U5M4/PgS+U2x1qhTSL6UjeTd4A/n5U5ZI8TZQj5U4ueIE7nmTs9Wr8XZ7gh/htYSLGN7Y30qkN2I2+tW3UJs09Yy7UbMs7pNXSaDuUbiMe2j9eQTf9ZQbeEL6e60IE6JLyUWm33PF6jf4mnCmxK3I/YRWaI91szLgej0NWwnSPXmurF11Zs8oxYD+2pFMxhzQUxDYBYodlEsqVtSjzszdqGObSRcMpKPoy7l0biRhfuf/nTio3dj+9R1F+Z+OBbhOL4829GlVi18KsRJwgNETd5Oru2wOOcheZJ4PTkLkp6mq+04g1YtsZnEBguPZFfd9TsVxXa0PhlcI1EmN7Jo2RIX68Wsr9rsqwrbR+zJ53hQn8gi5kM7OUaMe0Xws8GlYT0UwdyzlyDJV2F8uzn5UvbACG8cfUv8nbFL7Vp3OYvdaJB7K9Xva/DM1uwC4cMkVxhaxBJtMjmARMe2Y9oh40HWC4hVPJb+U4P9Wob0wbFu++nk/gYxtY96ahfmbxjsweSaS/phg20+BxDrul2cc4I5puZ5fM1xnCc3KphM6nc5Hs60Bp9ZsYvTC2dIDy1xWo6XiQ+jhi3iXvaPKxL/pj79n/Y1QvjB4ZhjAzvaIVb19L5GaEke8AJxpVh3xOZQi498Hg0FcWCUg0dnfjqSngnaHFyPGDK69sGdyW7EHfjgrGlaW6mNwfcoEOegwR7apPbWVjPtBnto4asiTqZ/wL4c1U56G/48Hr1OjlJLQ+xmtpj7ObmGS0OhHhff6wL5SjXpvRe+bfKvWPTJ8/vgyI1Z7xJfStuzIe7SutqOM9mOtkmOdDlfBUdgFcx2SA+tSs3WbNshPbQm8YnsyWbPKc6vI9kO1pk6JuM4xtQnz43iO8lbBt8jJzcaYD83ohy/w4C/sLVGufZjQ12chIfHi96AE+OaSTgb/nT8Qv46/Ilr4u9RAzvtWz7E5QEbItyFUpthb/6VN/1MOHXuP+oq19vw1Zn3oIaGV6C8B84mcs6FxABk8QDBVo8MrMFu2h/cRHwcREeKYXjmSf83uf7t51pSJ4lhOqLxZ9cvrzeO/ZiWIxxAZkviEsu087gIHda+qNHuYZ2Se6art665jzPhO8hdbSXYHM4j+5QKhO9A7LDG3iWfe6YfkvbUmuR4aPEMY57kKDXaLrWjcCayN86in31yXBjjS/gD2wvkAMLYBgkO0ekgfmk8jm8Oj4ciOeyQGJ7mlj3H1zrLmeqzgsHsbHmusd6JuVELVJ81W58MrhXp28uwG7H01Mbw8RgPUz+s3o7sY/XG1dlzURO/0YL9z8emz368/eHmduFuelP3wb99f3PruQ9zdxRM7zRFKylltepoulZRKqVSRalWv97NtYquVHs9bzabDGabaa/vD2cLvzfXFNW8GwzvvIf5ndvvu3fz+7v5wh+OJpO7vqLf9dV34XI2nfALl/5yOZpNe6PB27/y9o//+eP/Azh9lzXGBQMA"

_CAP_HIT_FIXTURE = json.loads(
    gzip.decompress(base64.b64decode(_CAP_HIT_FIXTURE_B64)).decode("utf-8")
)
CAP_HIT_RECORDS = {row["bundle_id"]: row for row in _CAP_HIT_FIXTURE["records"]}

# The lead-verified audit table (docs/reviews/2026-07-19-measurement-
# soundness-audit.md P0.4). Values are asserted against the embedded records.
AUDIT_CAP_HIT_TABLE = {
    "p2015-df-cmp-abba-su-b01-b1": (306.6823592185974, 0.09184273619271986, 0.07697866908265495),
    "p2015-df-ph-short-prefill-abs-r04": (300.06907892227173, 0.08203123624288897, 0.07510403184326292),
    "p2015-df-rq-long-prompt-abs-r03": (306.8624310493469, 0.12388120660306769, 0.07972459820477226),
    "p2015-df-cmp-abba-ph-prefill-b03-b1": (300.7070677280426, 0.08090751514250405, 0.07222589642845832),
}


def install_real_cap_hit_manifest(
    runs_root: Path, bundle_id: str, *, tamper: bool = False
) -> None:
    """Write the real campaign manifest + raw trace bytes for one cap-hit."""

    record = CAP_HIT_RECORDS[bundle_id]
    campaign_dir = runs_root / "campaign_manifests"
    raw_dir = campaign_dir / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    raw_bytes = base64.b64decode(record["raw_b64"])
    if tamper:
        raw_bytes += b'{"tampered":true}\n'
    (raw_dir / record["raw_name"]).write_bytes(raw_bytes)
    manifest = {
        "schema_version": "joulewise.campaign_provenance.v1",
        "session_id": record["session_id"],
        "analysis_manifest_id": None,
        "first_physical_run_id": record["first_physical_run_id"],
        "members": [
            {
                "run_id": bundle_id,
                "bundle_ids": [bundle_id],
                "execution": "invoked",
                "preceding_campaign_cooldown": record["cooldown"],
            }
        ],
        "cooldown_gates": [],
    }
    (campaign_dir / f"{record['session_id']}.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def install_synthetic_recovered_manifest(
    runs_root: Path, bundle_ids: list[str], session_id: str = "synthetic-session"
) -> None:
    campaign_dir = runs_root / "campaign_manifests"
    raw_dir = campaign_dir / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    members = []
    for index, bundle_id in enumerate(bundle_ids):
        trace = (
            json.dumps({"rolling_mean_power_w": 0.05, "timestamp_s": float(index)})
            + "\n"
        ).encode("utf-8")
        raw_name = f"{session_id}__cooldown_before_{bundle_id}.jsonl"
        (raw_dir / raw_name).write_bytes(trace)
        cooldown = (
            {
                "result": "first_run_exempt",
                "session_id": session_id,
                "following_run_id": bundle_id,
            }
            if index == 0
            else {
                "result": "recovered",
                "session_id": session_id,
                "following_run_id": bundle_id,
                "raw_artifact": {
                    "path": f"raw/{raw_name}",
                    "sha256": hashlib.sha256(trace).hexdigest(),
                    "records": 1,
                },
            }
        )
        members.append(
            {
                "run_id": bundle_id,
                "bundle_ids": [bundle_id],
                "execution": "invoked",
                "preceding_campaign_cooldown": cooldown,
            }
        )
    (campaign_dir / f"{session_id}.json").write_text(
        json.dumps(
            {
                "schema_version": "joulewise.campaign_provenance.v1",
                "session_id": session_id,
                "analysis_manifest_id": None,
                "first_physical_run_id": bundle_ids[0],
                "members": members,
                "cooldown_gates": [],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def make_summary(
    value: float,
    *,
    metric: str = "gross_energy_j",
    reducer: str = "0.5.1",
    anchor_bound: float | None = 0.01,
    envelope_point: float | None = None,
    interpolation_bound: float = 0.0,
    precheck_eligible: bool = True,
    precheck_reasons: list[str] | None = None,
    idle_method: str = "duration_weighted_newey_west_bartlett_10s_iid_floor_v2",
) -> dict:
    """Minimal claim-shaped summary for extraction gates (synthetic inputs)."""

    is_phase = metric.startswith("phase_energy_j.")
    point = value if envelope_point is None else envelope_point
    summary: dict = {
        "status": "succeeded",
        "summary_provenance": {"reducer_version": reducer},
        "measurement_quality": {
            "cooldown_cap_hit": None,
            "idle_window_suspect": False,
        },
        LEGACY_THROUGHPUT_FIELD: 225.0,
        READER_THROUGHPUT_FIELD: 223.5,
        "energy_bound_terms_j": {
            "E_interpolation_joint_edge_bound_j": interpolation_bound,
            "E_drift_bound_j": 0.0,
        },
        "idle_mean_uncertainty": {
            "status": "estimated",
            "method": idle_method,
            "correlation_scope": "independent_run",
        },
        "energy_variance_terms_j2": {"E_idle_mean_j2": 1e-4},
    }
    precheck_row: dict = {
        "eligible": precheck_eligible,
        "reasons": list(precheck_reasons or []),
    }
    if is_phase:
        phase = metric.split(".", 1)[1]
        summary["phase_energy_j"] = {phase: value}
        summary["window_evidence_precheck"] = {
            "phase": {
                phase: {
                    **precheck_row,
                    "windows": [
                        {"interpolation_joint_edge_bound_j": interpolation_bound}
                    ],
                }
            }
        }
    else:
        summary[metric if metric != "idle_subtracted_energy_j" else "energy_request_j"] = value
        summary["window_evidence_precheck"] = {
            "gross_request": dict(precheck_row),
            "idle_subtracted_request": dict(precheck_row),
        }
        summary["gross_energy_j"] = summary.get("gross_energy_j", value)
        summary["energy_request_j"] = summary.get("energy_request_j", value)
    if anchor_bound is not None:
        pointer = (
            "/phase_energy_j/" + metric.split(".", 1)[1]
            if is_phase
            else "/" + ("energy_request_j" if metric == "idle_subtracted_energy_j" else metric)
        )
        summary["energy_anchor_shift_envelopes"] = {
            pointer: {
                "method": "common_trace_shift_interval_overlap_v1",
                "anchor_bound_s": 0.05,
                "point_j": point,
                "lower_j": point - anchor_bound,
                "upper_j": point + anchor_bound,
                "max_abs_delta_j": anchor_bound,
            }
        }
        if not is_phase:
            summary["energy_bound_terms_j"]["E_clock_anchor_shift_bound_j"] = (
                anchor_bound
            )
    return summary


def write_bundle(runs_root: Path, bundle_id: str, summary: dict) -> None:
    bundle = runs_root / bundle_id
    bundle.mkdir(parents=True, exist_ok=True)
    (bundle / "summary_metrics.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


class RealCapHitJoinTests(unittest.TestCase):
    def test_embedded_fixtures_are_the_four_audited_records(self) -> None:
        self.assertEqual(set(CAP_HIT_RECORDS), set(AUDIT_CAP_HIT_TABLE))
        for bundle_id, (waited, decision, upper) in AUDIT_CAP_HIT_TABLE.items():
            record = CAP_HIT_RECORDS[bundle_id]
            cooldown = record["cooldown"]
            self.assertEqual(cooldown["result"], "cap_hit")
            self.assertEqual(cooldown["waited_s"], waited)
            self.assertEqual(cooldown["decision_rolling_mean_power_w"], decision)
            self.assertEqual(cooldown["effective_upper_w"], upper)
            raw_bytes = base64.b64decode(record["raw_b64"])
            self.assertEqual(
                hashlib.sha256(raw_bytes).hexdigest(),
                cooldown["raw_artifact"]["sha256"],
                f"embedded raw trace for {bundle_id} is not the sealed artifact",
            )

    def test_all_four_real_records_join_as_verified_cap_hits(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            for bundle_id in AUDIT_CAP_HIT_TABLE:
                install_real_cap_hit_manifest(runs_root, bundle_id)
            joined = campaign_cooldown_evidence(runs_root)
            for bundle_id in AUDIT_CAP_HIT_TABLE:
                row = joined[bundle_id]
                self.assertEqual(row["result"], "cap_hit")
                self.assertTrue(row["verified"])

    def test_tampered_raw_trace_never_verifies(self) -> None:
        bundle_id = "p2015-df-rq-long-prompt-abs-r03"
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            install_real_cap_hit_manifest(runs_root, bundle_id, tamper=True)
            joined = campaign_cooldown_evidence(runs_root)
            self.assertFalse(joined[bundle_id]["verified"])

    def test_ambiguous_duplicate_records_never_verify(self) -> None:
        bundle_id = "p2015-df-ph-short-prefill-abs-r04"
        record = CAP_HIT_RECORDS[bundle_id]
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            install_real_cap_hit_manifest(runs_root, bundle_id)
            # A second manifest claims the same bundle recovered cleanly.
            conflicting = {
                "schema_version": "joulewise.campaign_provenance.v1",
                "session_id": record["session_id"],
                "analysis_manifest_id": None,
                "first_physical_run_id": bundle_id,
                "members": [
                    {
                        "run_id": bundle_id,
                        "bundle_ids": [bundle_id],
                        "execution": "invoked",
                        "preceding_campaign_cooldown": {
                            "result": "first_run_exempt",
                            "session_id": record["session_id"],
                            "following_run_id": bundle_id,
                        },
                    }
                ],
                "cooldown_gates": [],
            }
            (runs_root / "campaign_manifests" / "conflict.json").write_text(
                json.dumps(conflicting, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            joined = campaign_cooldown_evidence(runs_root)
            self.assertFalse(joined[bundle_id]["verified"])
            self.assertEqual(joined[bundle_id]["result"], "unknown")


class AbsoluteCellExtractionTests(unittest.TestCase):
    def _build_corpus(self, tmp: str) -> tuple[Path, list[dict]]:
        runs_root = Path(tmp)
        cap_hit_id = "p2015-df-rq-long-prompt-abs-r03"
        install_real_cap_hit_manifest(runs_root, cap_hit_id)
        clean_ids = [f"clean-r{index:02d}" for index in range(1, 6)]
        install_synthetic_recovered_manifest(runs_root, clean_ids)
        values = [40.1, 39.9, 40.3, 40.0, 39.7]
        for bundle_id, value in zip(clean_ids, values):
            write_bundle(runs_root, bundle_id, make_summary(value))
        write_bundle(runs_root, cap_hit_id, make_summary(41.5))
        members = [{"slot": f"slot-{index}", "bundle_id": bundle_id} for index, bundle_id in enumerate(clean_ids)]
        members.append({"slot": "slot-cap", "bundle_id": cap_hit_id})
        return runs_root, members

    def test_cap_hit_member_is_slot_excluded_and_guard_runs_at_n_minus_1(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertTrue(report.extractable)
        self.assertEqual(report.n_planned, 6)
        self.assertEqual(report.n_admitted, 5)
        self.assertEqual(report.excluded_slots, ("slot-cap",))
        excluded = [member for member in report.members if member.excluded]
        self.assertEqual(len(excluded), 1)
        self.assertTrue(excluded[0].cap_hit)
        self.assertTrue(excluded[0].cooldown_verified)
        assert report.floor is not None
        self.assertEqual(report.floor.n, 5)
        # Same-slot exclusion left n=5: the frozen small-sample guard applies.
        self.assertEqual(report.floor.guard_factor, small_sample_guard_factor(5))
        self.assertAlmostEqual(
            report.floor.guarded_floor_j,
            small_sample_guard_factor(5) * report.floor.unguarded_floor_j,
        )
        self.assertEqual(report.anchor_shift_bound_max_j, 0.01)

    def test_missing_campaign_evidence_fails_the_whole_cell(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            orphan = "clean-r99"
            write_bundle(runs_root, orphan, make_summary(40.2))
            members.append({"slot": "slot-orphan", "bundle_id": orphan})
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("campaign_cooldown_evidence_missing", report.refusal_reasons)
        self.assertIsNone(report.floor)

    def test_tampered_cap_hit_evidence_refuses_instead_of_excluding(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            cap_hit_id = "p2015-df-rq-long-prompt-abs-r03"
            install_real_cap_hit_manifest(runs_root, cap_hit_id, tamper=True)
            clean_ids = [f"clean-r{index:02d}" for index in range(1, 4)]
            install_synthetic_recovered_manifest(runs_root, clean_ids)
            for bundle_id in clean_ids:
                write_bundle(runs_root, bundle_id, make_summary(40.0))
            write_bundle(runs_root, cap_hit_id, make_summary(41.5))
            members = [
                {"slot": bundle_id, "bundle_id": bundle_id}
                for bundle_id in (*clean_ids, cap_hit_id)
            ]
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("campaign_cooldown_evidence_missing", report.refusal_reasons)
        self.assertEqual(report.excluded_slots, ())

    def test_precheck_failure_is_a_hard_gate_source_clean_never_overrides(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            failing = make_summary(40.2, precheck_eligible=False, precheck_reasons=["clock_anchor_unresolved"])
            # Source-clean provenance must NOT rescue a failed metric
            # precheck (audit P0.2 regression).
            failing["metadata_note_source_provenance_claim_eligible"] = True
            write_bundle(runs_root, "clean-r01", failing)
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("clock_anchor_unresolved", report.refusal_reasons)

    def test_pre_anchor_wire_refuses_with_envelope_unrecorded(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            write_bundle(
                runs_root,
                "clean-r02",
                make_summary(39.9, reducer="0.5.0", anchor_bound=None),
            )
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("anchor_energy_envelope_unrecorded", report.refusal_reasons)

    def test_envelope_wider_than_quarter_metric_refuses(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            write_bundle(
                runs_root,
                "clean-r03",
                make_summary(0.257, anchor_bound=3.25),
            )
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-SHORT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn(
            "anchor_energy_envelope_exceeds_quarter_metric", report.refusal_reasons
        )

    def test_envelope_point_disagreeing_with_summary_value_refuses(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            write_bundle(
                runs_root,
                "clean-r04",
                make_summary(40.0, envelope_point=39.0),
            )
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("anchor_energy_envelope_unrecorded", report.refusal_reasons)

    def test_unknown_reducer_wire_refuses(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            write_bundle(runs_root, "clean-r05", make_summary(39.7, reducer="0.7.0"))
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-LONG-PROMPT",
                metric="gross_energy_j",
                window_class="request",
                members=members,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("reducer_wire_unknown", report.refusal_reasons)

    def test_idle_subtracted_cell_requires_the_exact_idle_method_pair(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            clean_ids = ["idle-r01", "idle-r02", "idle-r03"]
            install_synthetic_recovered_manifest(runs_root, clean_ids)
            for index, bundle_id in enumerate(clean_ids):
                summary = make_summary(
                    12.0 + index * 0.1,
                    metric="energy_request_j",
                    idle_method=(
                        "newey_west_bartlett_10s_iid_floor_v1"
                        if index == 1
                        else "duration_weighted_newey_west_bartlett_10s_iid_floor_v2"
                    ),
                )
                write_bundle(runs_root, bundle_id, summary)
            report = extract_absolute_cell(
                cell_id="DF-RQ-IDLE-MID",
                metric="energy_request_j",
                window_class="request",
                members=[{"slot": b, "bundle_id": b} for b in clean_ids],
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertFalse(report.extractable)
        self.assertIn("idle_method_pair_invalid", report.refusal_reasons)

    def test_drift_term_cap_hit_policy_is_not_governed_yet(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root, members = self._build_corpus(tmp)
            with self.assertRaisesRegex(FloorExtractionError, "cap-hit policy"):
                extract_absolute_cell(
                    cell_id="DF-RQ-GROSS-LONG-PROMPT",
                    metric="gross_energy_j",
                    window_class="request",
                    members=members,
                    runs_root=runs_root,
                    cooldowns={},
                    cap_hit_policy="retain_with_drift_term",
                )


class ComparativeCellExtractionTests(unittest.TestCase):
    def _build_blocks(self, runs_root: Path) -> list[dict]:
        cap_hit_id = "p2015-df-cmp-abba-su-b01-b1"
        install_real_cap_hit_manifest(runs_root, cap_hit_id)
        blocks = []
        synthetic_ids: list[str] = []
        base = {"A1": 32.4, "B1": 32.2, "B2": 32.3, "A2": 32.5}
        for block_index in (1, 2, 3):
            block_id = f"b{block_index:02d}"
            members = {}
            for position in ("A1", "B1", "B2", "A2"):
                if block_index == 1 and position == "B1":
                    bundle_id = cap_hit_id
                else:
                    bundle_id = f"su-{block_id}-{position.lower()}"
                    synthetic_ids.append(bundle_id)
                members[position] = bundle_id
                write_bundle(
                    runs_root,
                    bundle_id,
                    make_summary(base[position] + 0.01 * block_index),
                )
            blocks.append({"block_id": block_id, "members": members})
        install_synthetic_recovered_manifest(runs_root, synthetic_ids)
        return blocks

    def test_cap_hit_excludes_its_whole_block_same_slot(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            blocks = self._build_blocks(runs_root)
            report = extract_comparative_cell(
                cell_id="DF-CMP-ABBA-SU",
                metric="gross_energy_j",
                window_class="request",
                blocks=blocks,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertTrue(report.extractable)
        self.assertEqual(report.excluded_slots, ("b01",))
        self.assertEqual(report.n_planned, 3)
        self.assertEqual(report.n_admitted, 2)
        excluded_members = [m for m in report.members if m.excluded]
        # ALL FOUR members of the cap-hit block are out, not just the cap-hit.
        self.assertEqual(len(excluded_members), 4)
        self.assertEqual({m.block_id for m in excluded_members}, {"b01"})
        assert report.floor is not None
        self.assertEqual(report.floor.n, 2)
        # n_blocks=2 < 5: smoke-only, the guarded floor MUST be withheld.
        self.assertIsNone(report.floor.guarded_floor_j)
        self.assertIsNone(report.floor.guard_factor)

    def test_delta_sign_and_magnitude_use_frozen_abba_formula(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            blocks = self._build_blocks(runs_root)
            report = extract_comparative_cell(
                cell_id="DF-CMP-ABBA-SU",
                metric="gross_energy_j",
                window_class="request",
                blocks=blocks,
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        assert report.floor is not None
        expected_delta = (32.2 + 32.3 - 32.4 - 32.5) / 2.0
        for delta in report.floor.deviations_j:
            self.assertAlmostEqual(delta, expected_delta, places=9)


class MetricHygieneTests(unittest.TestCase):
    def test_phase_cell_reading_whole_request_gross_fails_loudly(self) -> None:
        with self.assertRaisesRegex(FloorExtractionError, "phase_energy_j"):
            governed_cell_metric("gross_energy_j", "phase")

    def test_phase_metric_on_request_window_fails_loudly(self) -> None:
        with self.assertRaisesRegex(FloorExtractionError, "window_class 'phase'"):
            governed_cell_metric("phase_energy_j.prefill", "request")

    def test_legacy_throughput_is_never_reader_facing(self) -> None:
        with self.assertRaisesRegex(FloorExtractionError, "inter_token_throughput"):
            governed_cell_metric(LEGACY_THROUGHPUT_FIELD, "request")

    def test_reader_throughput_selects_only_the_governed_field(self) -> None:
        summary = {LEGACY_THROUGHPUT_FIELD: 225.0, READER_THROUGHPUT_FIELD: 223.5}
        self.assertEqual(reader_throughput_tokens_s(summary), 223.5)
        self.assertIsNone(
            reader_throughput_tokens_s({LEGACY_THROUGHPUT_FIELD: 225.0})
        )

    def test_phase_cell_extracts_only_the_phase_target(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            bundle_ids = ["ph-r01", "ph-r02", "ph-r03"]
            install_synthetic_recovered_manifest(runs_root, bundle_ids)
            for index, bundle_id in enumerate(bundle_ids):
                summary = make_summary(
                    5.0 + 0.01 * index, metric="phase_energy_j.prefill"
                )
                # A whole-request gross field 8x larger sits right next to
                # the phase value; extraction must never read it.
                summary["gross_energy_j"] = 40.0
                write_bundle(runs_root, bundle_id, summary)
            report = extract_absolute_cell(
                cell_id="DF-PH-PREFILL",
                metric="phase_energy_j.prefill",
                window_class="phase",
                members=[{"slot": b, "bundle_id": b} for b in bundle_ids],
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertTrue(report.extractable)
        assert report.floor is not None
        self.assertAlmostEqual(report.floor.mean_j, 5.01, places=9)
        for member in report.members:
            self.assertLess(member.value_j, 6.0)

    def test_duplicate_member_bundles_are_pseudo_replication(self) -> None:
        with self.assertRaisesRegex(FloorExtractionError, "pseudo-replication"):
            extract_absolute_cell(
                cell_id="DF-RQ-GROSS-MID",
                metric="gross_energy_j",
                window_class="request",
                members=[
                    {"slot": "a", "bundle_id": "same"},
                    {"slot": "b", "bundle_id": "same"},
                ],
                runs_root=Path("."),
                cooldowns={},
            )


class ExtractionCliTests(unittest.TestCase):
    def test_spec_extraction_report_and_exit_codes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp) / "runs"
            runs_root.mkdir()
            bundle_ids = ["cli-r01", "cli-r02", "cli-r03"]
            install_synthetic_recovered_manifest(runs_root, bundle_ids)
            for index, bundle_id in enumerate(bundle_ids):
                write_bundle(runs_root, bundle_id, make_summary(40.0 + 0.1 * index))
            spec = {
                "schema_version": EXTRACTION_SPEC_SCHEMA_VERSION,
                "cells": [
                    {
                        "cell_id": "DF-RQ-GROSS-MID",
                        "kind": "absolute",
                        "metric": "gross_energy_j",
                        "window_class": "request",
                        "members": [
                            {"slot": b, "bundle_id": b} for b in bundle_ids
                        ],
                    }
                ],
            }
            spec_path = Path(tmp) / "spec.json"
            spec_path.write_text(json.dumps(spec), encoding="utf-8")
            out_path = Path(tmp) / "report.json"
            with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
                code = extract_main(
                    [
                        "--runs-root",
                        str(runs_root),
                        "--spec",
                        str(spec_path),
                        "--out",
                        str(out_path),
                    ]
                )
            self.assertEqual(code, 0)
            report = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertTrue(report["all_cells_extractable"])
            self.assertEqual(report["cells"][0]["cap_hit_policy"], CAP_HIT_POLICY_EXCLUDE_SAME_SLOT)
            self.assertEqual(report["cells"][0]["n_admitted"], 3)
            self.assertTrue(report["cells"][0]["floor"]["smoke_only"])

            # Remove the campaign evidence: the same spec must now refuse
            # (exit 1) while still writing the fail-closed report.
            import shutil

            shutil.rmtree(runs_root / "campaign_manifests")
            with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
                code = extract_main(
                    [
                        "--runs-root",
                        str(runs_root),
                        "--spec",
                        str(spec_path),
                        "--out",
                        str(out_path),
                    ]
                )
            self.assertEqual(code, 1)
            refused = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertFalse(refused["all_cells_extractable"])
            self.assertIn(
                "campaign_cooldown_evidence_missing",
                refused["cells"][0]["refusal_reasons"],
            )

    def test_bad_spec_is_a_process_error(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp) / "runs"
            runs_root.mkdir()
            spec_path = Path(tmp) / "spec.json"
            spec_path.write_text(json.dumps({"schema_version": "wrong"}), encoding="utf-8")
            with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
                code = extract_main(
                    [
                        "--runs-root",
                        str(runs_root),
                        "--spec",
                        str(spec_path),
                        "--out",
                        str(Path(tmp) / "report.json"),
                    ]
                )
            self.assertEqual(code, 2)
            self.assertFalse((Path(tmp) / "report.json").exists())

    def test_spec_extraction_via_extract_cells_matches_direct_calls(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            bundle_ids = ["eq-r01", "eq-r02"]
            install_synthetic_recovered_manifest(runs_root, bundle_ids)
            for bundle_id in bundle_ids:
                write_bundle(runs_root, bundle_id, make_summary(40.0))
            spec = {
                "schema_version": EXTRACTION_SPEC_SCHEMA_VERSION,
                "cells": [
                    {
                        "cell_id": "DF-RQ-GROSS-MID",
                        "kind": "absolute",
                        "metric": "gross_energy_j",
                        "window_class": "request",
                        "members": [{"slot": b, "bundle_id": b} for b in bundle_ids],
                    }
                ],
            }
            report = extract_cells(runs_root, spec)
            direct = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-MID",
                metric="gross_energy_j",
                window_class="request",
                members=spec["cells"][0]["members"],
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
            self.assertEqual(report["cells"][0], direct.as_row())

    def test_zero_scatter_cell_has_zero_floor_but_still_extracts(self) -> None:
        # Degenerate identical values: floor math stays finite and exact.
        with tempfile.TemporaryDirectory() as tmp:
            runs_root = Path(tmp)
            bundle_ids = [f"z-r{index}" for index in range(5)]
            install_synthetic_recovered_manifest(runs_root, bundle_ids)
            for bundle_id in bundle_ids:
                write_bundle(runs_root, bundle_id, make_summary(40.0))
            report = extract_absolute_cell(
                cell_id="DF-RQ-GROSS-MID",
                metric="gross_energy_j",
                window_class="request",
                members=[{"slot": b, "bundle_id": b} for b in bundle_ids],
                runs_root=runs_root,
                cooldowns=campaign_cooldown_evidence(runs_root),
            )
        self.assertTrue(report.extractable)
        assert report.floor is not None
        self.assertEqual(report.floor.unguarded_floor_j, 0.0)
        self.assertTrue(math.isfinite(report.floor.guarded_floor_j))


if __name__ == "__main__":
    unittest.main()
