"""Offline smoke tests for the RPT-001 report vertical slice.

These run against the committed rpt001-v1 artifacts and report source; they
do NOT reread the real bundle corpus (which is gitignored). Real-bundle
ingestion is the lead-run local gate (spec §0.4/§9.4).
"""

from __future__ import annotations

import csv
import json
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ANALYSIS = REPO / "analysis" / "rpt001-v1"
LEGACY_LABEL = "legacy L1 (manual review; pre-2M)"


class TestRpt001Artifacts(unittest.TestCase):
    def test_dataset_six_rows_pinned_order(self):
        with open(ANALYSIS / "dataset.csv", newline="", encoding="utf-8") as fh:
            rows = list(csv.DictReader(fh))
        self.assertEqual(len(rows), 6)
        self.assertEqual(
            [r["run_id"] for r in rows],
            [f"example-mac-mlx-local__r{i}" for i in (1, 2, 3)]
            + [f"example-mac-mlx-qwen35-122b-512t__r{i}" for i in (1, 2, 3)],
        )
        for row in rows:
            self.assertEqual(row["evidence_class"], "legacy_l1_manual_review_pre_2m")
            self.assertFalse(row["bundle_path"].startswith("/"))

    def test_claims_row_shape(self):
        lines = (ANALYSIS / "claims_index.jsonl").read_text(encoding="utf-8").splitlines()
        self.assertEqual(len(lines), 1)
        row = json.loads(lines[0])
        self.assertEqual(row["schema"], "joulewise.claims_index.v1")
        self.assertEqual(row["claim_id"], "CLM-RPT001-LEGACY-L1-001")
        self.assertEqual(row["claim_level"], "L1")
        self.assertEqual(row["legacy_label"], LEGACY_LABEL)
        self.assertIsNone(row["analysis_manifest_ref"])
        self.assertEqual(row["verdict_ref"]["status"], "not_applicable_l1")
        self.assertIn("44.42591347410544", row["claim_text"])
        self.assertIn("298.68731644234157", row["claim_text"])

    def test_figure_labels_and_honesty(self):
        svg = (REPO / "figures" / "rpt001-v1" /
               "F1_legacy_l1_instrument_results.svg").read_text(encoding="utf-8")
        self.assertIn(LEGACY_LABEL, svg)
        self.assertIn("min–max range (not a confidence interval)", svg)
        self.assertIn("idle-subtracted energy_request_j", svg)
        self.assertIn("gross gross_energy_j", svg)
        self.assertIn("runtime-observed output token", svg)
        self.assertNotIn("95%", svg)
        self.assertNotIn("CI", svg.replace("CPU", ""))

    def test_t1_and_s1_labels(self):
        t1 = (ANALYSIS / "tables" / "T1_legacy_l1_results.md").read_text(encoding="utf-8")
        s1 = (ANALYSIS / "tables" / "S1_legacy_stack_identity.md").read_text(encoding="utf-8")
        self.assertIn(LEGACY_LABEL, t1)
        self.assertIn("cooldown cap hit", t1)
        self.assertIn("unknown (legacy bundle)", s1)
        for field in ("tokenizer_identity", "measurement_boundary", "telemetry_backend"):
            self.assertIn(field, s1)

    def test_report_profile_and_chapters(self):
        src = REPO / "docs" / "report_src"
        profile = json.loads((src / "report.json").read_text(encoding="utf-8"))
        self.assertEqual(profile["schema"], "joulewise.report_profile.v1")
        self.assertEqual(len(profile["chapters"]), 13)
        for chapter in profile["chapters"]:
            self.assertTrue((src / chapter).is_file(), chapter)
        self.assertIsNone(profile["format_adapter"]["renderer"])

    def test_generated_page_contents(self):
        page = (REPO / "docs" / "report_src" / "generated" /
                "rpt001_vertical_slice.md").read_text(encoding="utf-8")
        self.assertTrue(page.startswith("<!-- GENERATED by scripts/build_capstone.py"))
        for needed in (LEGACY_LABEL, "CLM-RPT001-LEGACY-L1-001",
                       "scripts/make_figures.py", "artifact_manifest.json",
                       "Table S1", "Table T1"):
            self.assertIn(needed, page)
        for forbidden in ("more efficient", "less efficient", "scales with model size"):
            self.assertNotIn(forbidden, page.lower())


if __name__ == "__main__":
    unittest.main()
