"""Paper B's registered-values table equals what the extractor reads from the sources now.

``docs/paper/paper-b/registered-values.json`` is generated by
``docs/paper/tools/extract_registered_values.py``.  These tests:

* regenerate the table and compare bytes with the committed file;
* check that every entry names a file and a key, and that no two committed
  places that state one quantity disagree;
* change each source value in turn and require the entry read from it to
  change (or the extraction to fail), so that the file and key an entry
  names are proven to be where its value comes from.  JSON, Markdown and
  member-configuration sources are changed in memory; module constants are
  changed in a scratch copy of ``joulewise/`` and ``scripts/`` under TMPDIR,
  which the extractor's child interpreter imports;
* check that the table covers every key of the blocks and tables it reads
  (a threshold or budget added later cannot be missing from it silently).

Nothing here reads a bundle, an energy or a harvest output.
"""

from __future__ import annotations

import ast
import copy
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOL_PATH = REPO_ROOT / "docs" / "paper" / "tools" / "extract_registered_values.py"
ID_RE = re.compile(r"^[a-z0-9_]+(\.[A-Za-z0-9_-]+)+$")
# Project shorthand that must not reach text a paper author may copy (the paper brief's list, and kin).
SHORTHAND = (r"\bD-\d", r"\bint5\b", r"H_claim", r"[Mm]agistrate", r"[Cc]old pass", r"PLAN2", r"gate-prune",
             r"\blane\b", r"\bG10\b", r"\bR3\b", r"\bALPHA-\d", r"#4\d\d", r"\bNEG-?8 (screen|bound)\b")


def load_tool() -> Any:
    name = "paper_b_extract_registered_values"
    spec = importlib.util.spec_from_file_location(name, TOOL_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module      # dataclasses look their module up while the class body runs
    spec.loader.exec_module(module)
    return module


def changed(value: Any) -> Any:
    """A value of the same kind that differs from ``value``."""

    if isinstance(value, bool):
        return not value
    if isinstance(value, (int, float)):
        return value + 1
    if isinstance(value, str):
        return value + "~"
    if value is None:
        return 1
    if isinstance(value, list):
        return value + ["~"]
    if isinstance(value, dict):
        return {**value, "~": 1}
    raise AssertionError(f"no change defined for {type(value).__name__}")


def set_at(document: Any, tokens: tuple, value: Any) -> None:
    node = document
    for token in tokens[:-1]:
        node = node[int(token)] if isinstance(node, list) else node[token]
    last = tokens[-1]
    if isinstance(node, list):
        node[int(last)] = value
    else:
        node[last] = value


def get_at(document: Any, tokens: tuple) -> Any:
    node = document
    for token in tokens:
        node = node[int(token)] if isinstance(node, list) else node[token]
    return node


def add_member(container: Any, member: Any) -> None:
    if isinstance(container, list):
        container.append(member)
    else:
        container["~probe"] = member


def dump(document: Any) -> bytes:
    return (json.dumps(document, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def python_value_span(source: bytes, symbol: str, path: tuple) -> tuple[int, int]:
    """Byte span of the expression that gives ``symbol[path...]`` its value at module level."""

    node: ast.expr | None = None
    for statement in ast.parse(source).body:
        if isinstance(statement, ast.Assign):
            for target in statement.targets:
                if isinstance(target, ast.Name) and target.id == symbol:
                    node = statement.value
                elif isinstance(target, ast.Tuple) and isinstance(statement.value, ast.Tuple):
                    for name, value in zip(target.elts, statement.value.elts):
                        if isinstance(name, ast.Name) and name.id == symbol:
                            node = value
        elif (isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name)
              and statement.target.id == symbol and statement.value is not None):
            node = statement.value
    if node is None:
        raise LookupError(f"no module-level assignment to {symbol}")
    for step in path:
        if isinstance(node, ast.Dict):
            matches = [value for key, value in zip(node.keys, node.values)
                       if isinstance(key, ast.Constant) and key.value == step]
            if len(matches) != 1:
                raise LookupError(f"{symbol}: no literal key {step!r}")
            node = matches[0]
        elif isinstance(node, (ast.Tuple, ast.List)):
            node = node.elts[step]
        else:
            raise LookupError(f"{symbol}: {step!r} is below an expression that is not a literal container")
    starts = [0]
    for line in source.splitlines(keepends=True):
        starts.append(starts[-1] + len(line))
    return (starts[node.lineno - 1] + node.col_offset, starts[node.end_lineno - 1] + node.end_col_offset)


def python_changed_expression(expression: bytes, value: Any) -> bytes:
    """Source text of an expression that evaluates to something other than ``value``."""

    if isinstance(value, bool):
        return b"(not (" + expression + b"))"
    if isinstance(value, (int, float)):
        return b"((" + expression + b") + 1)"
    if isinstance(value, str):
        return b'((' + expression + b') + "~")'
    if value is None:
        return b"(1)"
    if isinstance(value, list):
        return b'((lambda item: type(item)(list(item) + ["~"]))(' + expression + b"))"
    raise AssertionError(f"no change defined for a module constant of type {type(value).__name__}")


class RegisteredValuesTests(unittest.TestCase):
    maxDiff = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.tool = load_tool()
        cls.entries = cls.tool.manifest()
        cls.refs = cls.tool.all_refs(cls.entries)
        cls.python_values = cls.tool.read_python_constants(REPO_ROOT, cls.refs)
        cls.tree = cls.tool.Tree(REPO_ROOT)
        cls.sources = cls.tool.Sources(cls.tree)
        cls.document = cls.tool.build_document(cls.tree, cls.python_values, cls.entries)
        cls.rendered = cls.tool.render(cls.document)
        cls.committed_path = REPO_ROOT / cls.tool.OUTPUT_RELATIVE
        cls.committed = cls.committed_path.read_bytes()

    # ---------------------------------------------------------------- the acceptance test

    def test_committed_table_is_what_the_sources_give_now(self) -> None:
        if self.rendered != self.committed:
            lines = self.tool.describe_difference(self.committed, self.rendered)
            self.fail("docs/paper/paper-b/registered-values.json no longer matches its sources. This is expected "
                      "on a commit that revises or seals the registration, the sizing output, the identity pins "
                      "or the sealed inventory: regenerate the table "
                      "(python3 -B docs/paper/tools/extract_registered_values.py --write), commit it in the same "
                      "pull request, and re-sync the paper text that cites these entries:\n  " + "\n  ".join(lines))

    def test_command_line_check_passes_on_the_committed_table(self) -> None:
        completed = subprocess.run([sys.executable, "-B", str(TOOL_PATH), "--check"], capture_output=True,
                                   text=True, cwd=str(REPO_ROOT), timeout=300, check=False)
        self.assertEqual(completed.returncode, 0, completed.stderr)

    # ---------------------------------------------------------------- shape of the table

    def test_every_entry_names_a_file_and_a_key(self) -> None:
        committed = json.loads(self.committed)
        self.assertEqual(committed["schema"], self.tool.SCHEMA)
        self.assertGreater(len(committed["values"]), 400)
        self.assertEqual(list(committed["values"]), sorted(committed["values"]))
        kinds = {"json", "markdown-json", "markdown-line", "markdown-table", "python", "derived", "config-set"}
        for entry_id, record in committed["values"].items():
            with self.subTest(entry=entry_id):
                self.assertRegex(entry_id, ID_RE)
                self.assertEqual(set(record) - {"also"}, {"value", "unit", "what", "source"})
                self.assertIn(record["unit"], self.tool.UNITS)
                self.assertTrue(record["what"].strip().endswith("."), record["what"])
                for place in [record["source"], *record.get("also", [])]:
                    self.assertIn(place["kind"], kinds)
                    self.assertTrue(place["key"].strip())
                    for path in place["file"].split("; "):
                        self.assertFalse(Path(path).is_absolute() or ".." in Path(path).parts, path)
                        self.assertTrue((REPO_ROOT / path).exists(), f"{path} does not exist")
                for place in record.get("also", []):
                    self.assertIn("value", place)

    def test_sources_are_design_files_only(self) -> None:
        # Committed configuration and code: never a runs directory, an archive or a harvest output.
        sources = json.loads(self.committed)["sources"]
        self.assertGreater(len(sources), 20)
        for source in sources:
            with self.subTest(source=source["file"]):
                self.assertIn(Path(source["file"]).parts[0], {"configs", "joulewise", "scripts"})
                self.assertTrue((REPO_ROOT / source["file"]).exists())

    def test_no_two_places_that_state_one_quantity_disagree(self) -> None:
        self.assertEqual(self.document["disagreements"], [])
        for entry_id, record in self.document["values"].items():
            for place in record.get("also", []):
                with self.subTest(entry=entry_id, also=place["key"]):
                    self.assertTrue(self.tool.same_value(record["value"], place["value"]))

    def test_descriptions_carry_no_project_shorthand(self) -> None:
        texts = {f"values.{key}": record["what"] for key, record in self.document["values"].items()}
        for where, text in texts.items():       # the label is glossed once, in the glossary, and used nowhere else
            with self.subTest(where=where, pattern="NEG-8"):
                self.assertNotIn("NEG-8", text)
        texts.update({f"glossary.{item['term']}": item["meaning"] for item in self.document["glossary"]})
        for where, text in texts.items():
            for pattern in SHORTHAND:
                with self.subTest(where=where, pattern=pattern):
                    self.assertIsNone(re.search(pattern, text), text)

    def test_glossary_builds_each_term_before_a_later_meaning_uses_it(self) -> None:
        # Each of these words is defined by one glossary item; no earlier item's meaning may use it.
        reference = ("reference member, reference corpus, triplet, midpoint reference, spare, "
                     "reference drift check, reference drift bound")
        science = "science member, repeat, quad, side, unit"
        clock = "clock anchor, frequency word, residual"
        placement = "half-width, member clock bound"
        span = "programmed span, member allowance, window deadline"
        defined_by = {
            "member": "member", "sampler": "sampler, power record", "phase": "phase, phase energy",
            "workload": "workload; decode workload, prefill workload", "stage": "stage, collection stage",
            "settle": "settle", "cooldown": "cooldown", "pack": "pack; ALPHA, BETA, GAMMA", "chain": "chain",
            "window": "window, attempt", "registration": "measurement block, registration, sealed",
            "sealed": "measurement block, registration, sealed",
            "bracket": "calibration capture, pulse timing bound, bracket, bracket reservation",
            "science": science, "quad": science, "unit": science,
            "reference": reference, "spare": reference, "survive": reference,
            "hazard": "hazard, hazard check, arm, dwell", "arm": "hazard, hazard check, arm, dwell",
            "dwell": "hazard, hazard check, arm, dwell", "agent": "agent session, agent census",
            "anchor": clock, "residual": clock, "half-width": placement, "member clock bound": placement,
            "frequency gate": "frequency gate",
            "registry": "registry, SMC", "SMC": "registry, SMC", "monitor": "monitor", "driver": "driver",
            "flag": "flag, flag catalog, effect", "catalog": "flag, flag catalog, effect", "harvest": "harvest",
            "programmed span": span, "member allowance": span, "window deadline": span,
            "expected chain length": "expected chain length",
        }
        terms = [item["term"] for item in self.document["glossary"]]
        for word, term in defined_by.items():
            position = terms.index(term)
            for earlier in self.document["glossary"][:position]:
                with self.subTest(word=word, used_in=earlier["term"]):
                    self.assertIsNone(re.search(rf"\b{word}s?\b", earlier["meaning"]), earlier["meaning"])

    def test_each_description_stands_alone(self) -> None:
        # Entries are sorted by id and cited one at a time, so a description may not lean on its neighbour.
        leaning = (r"\b[Tt]hat (fraction|charge|value|size|bound|test|block|diagnostic|reproduction|power)\b",
                   r"\bsuch run\b", r"\bsame (decision|way|parts)\b", r"\bversions below\b", r"\bblock[- ]5\b",
                   r"\bdisclosed\b")
        for key, record in self.document["values"].items():
            for pattern in leaning:
                with self.subTest(entry=key, pattern=pattern):
                    self.assertIsNone(re.search(pattern, record["what"]), record["what"])
        # A description that points at another entry names one that exists.
        ids = set(self.document["values"])
        prefixes = sorted({key.split(".")[0] for key in ids})
        pointer = re.compile(r"\b(?:" + "|".join(prefixes) + r")\.[A-Za-z0-9_.*-]*[A-Za-z0-9_*]")
        for key, record in self.document["values"].items():
            for named in pointer.findall(record["what"]):
                with self.subTest(entry=key, names=named):
                    if named.endswith(".*"):
                        self.assertTrue(any(other.startswith(named[:-1]) for other in ids))
                    else:
                        self.assertIn(named, ids)

    # ---------------------------------------------------------------- coverage of the sources

    def _ids(self) -> set[str]:
        return set(self.document["values"])

    def test_every_registered_threshold_has_an_entry(self) -> None:
        text = self.sources.text(self.tool.REGISTRATION)
        arm = self.tool.fenced_json(text, self.tool.ARM_HEADING, where="registration")
        expected = {f"arm.{module}.{key}" for module, block in arm.items() for key in block}
        self.assertEqual(expected, {key for key in self._ids() if key.count(".") == 2 and key.startswith("arm.")
                                    and key.split(".")[1] in arm})
        harvest = self.tool.fenced_json(text, self.tool.HARVEST_HEADING, where="registration")
        self.assertTrue({f"harvest.{key}" for key in harvest} <= self._ids())

    def test_registered_blocks_match_the_code_that_reads_them(self) -> None:
        from joulewise.b5 import harvest
        from joulewise.hazards import arm

        text = self.sources.text(self.tool.REGISTRATION)
        block = self.tool.fenced_json(text, self.tool.ARM_HEADING, where="registration")
        defaults = arm.default_thresholds()
        self.assertEqual(set(block), set(defaults))
        for module in defaults:
            self.assertEqual(set(block[module]), set(defaults[module]), module)
        parsed = harvest.parse_registration_thresholds(self.tree.read(self.tool.REGISTRATION))
        ours = self.tool.fenced_json(text, self.tool.HARVEST_HEADING, where="registration")
        self.assertEqual(set(ours), set(harvest.HARVEST_THRESHOLD_KEYS))
        for key in harvest.HARVEST_THRESHOLD_KEYS:
            self.assertTrue(self.tool.same_value(ours[key], parsed[key]), key)

    def test_every_key_of_the_tables_read_has_an_entry(self) -> None:
        from joulewise.b5 import chain
        from joulewise.hazards import monitor

        ids = self._ids()
        self.assertTrue({f"chain.wall_budget_s.{key}" for key in chain.STAGE_WALL_BUDGET_S} <= ids)
        self.assertTrue({f"monitor.every_s.{key.removesuffix('_s')}" for key in monitor.DEFAULT_CADENCE} <= ids)
        self.assertTrue({f"chain.exit.{key}" for key in chain.STOP_EXITS} <= ids)
        sizing = self.sources.json(self.tool.SIZING)
        self.assertEqual(tuple(sizing["packs"]), self.tool.PACK_LABELS)
        for label, pack in sizing["packs"].items():
            self.assertTrue({f"pack.{label}.span_part_s.{key.removesuffix('_s')}" for key in pack["breakdown"]
                             if key != "programmed_span_s"} <= ids, label)
            self.assertEqual(Path(pack["plan_tree"]["path"]).parent.as_posix(), self.tool.PACK_DIRS[label])
        catalog = self.sources.json(self.tool.CATALOG)
        codes = catalog["codes"].values()
        self.assertTrue({f"catalog.family.{code['family']}" for code in codes} <= ids)
        self.assertTrue({f"catalog.effect.{code['effect']}" for code in codes} <= ids)
        self.assertTrue({f"catalog.class.{code['klass']}" for code in codes} <= ids)
        self.assertTrue({f"catalog.blinding.{code['blinding']}" for code in codes} <= ids)
        pins = self.sources.json(self.tool.PINS)
        self.assertEqual(set(pins["units"]), {key for key, _, _ in self.tool.IDENTITY_UNITS})
        self.assertTrue({f"runtime.package.{name}" for name in pins["runtime_versions"]["packages"]} <= ids)

    def test_catalog_counts_add_up(self) -> None:
        values = {key: record["value"] for key, record in self.document["values"].items()}
        total = values["catalog.codes"]
        for group in ("effect", "class", "family", "blinding"):
            parts = [value for key, value in values.items() if key.startswith(f"catalog.{group}.")]
            self.assertEqual(sum(parts), total, group)
        self.assertEqual(sum(value for key, value in values.items() if key.startswith("catalog.class_effect.")),
                         total)
        for effect in ("EXCLUDE_WINDOW", "EXCLUDE_MEMBER"):
            self.assertEqual(len(values[f"catalog.codes_with_effect.{effect}"]), values[f"catalog.effect.{effect}"])

    def test_pack_counts_add_up(self) -> None:
        values = {key: record["value"] for key, record in self.document["values"].items()}
        for label in self.tool.PACK_LABELS:
            with self.subTest(pack=label):
                pack = f"pack.{label}"
                self.assertEqual(values[f"{pack}.science_members"] + values[f"{pack}.auxiliary_members"],
                                 values[f"{pack}.members"])
                self.assertEqual(values[f"{pack}.members_1p7b_class"] + values[f"{pack}.members_8b"],
                                 values[f"{pack}.members"])
                self.assertEqual(values[f"{pack}.claim_root_members"] + values[f"{pack}.bound_root_members"],
                                 values[f"{pack}.members"])
                self.assertEqual(sum(row["members"] or 0 for row in values[f"{pack}.stage_order"]),
                                 values[f"{pack}.members"])
                self.assertEqual(sum(value for key, value in values.items()
                                     if key.startswith(f"{pack}.span_part_s.")),
                                 values[f"{pack}.programmed_span_s"])
                # WINDOW_MAX_S = 60 * ceil((programmed span + the arm's allowance) / 60)
                self.assertEqual(-(-(values[f"{pack}.programmed_span_s"] + values["arm.allowance_s"]) // 60) * 60,
                                 values[f"{pack}.window_max_s"])
                self.assertEqual(values[f"{pack}.spares"], values["reference.spares.start"]
                                 + values["reference.spares.midpoint"] + values["reference.spares.end"])

    def test_expected_chain_length_is_a_third_of_the_window_deadline_or_less(self) -> None:
        # The window deadline is a stop limit and the programmed span a worst case.  The glossary and the
        # deadline entries say in words that a chain is expected to take a third of the deadline or less; a
        # paper section that took the deadline for a window's length would describe about one window a day.
        # This keeps those words true of the numbers the table holds.
        values = {key: record["value"] for key, record in self.document["values"].items()}
        for label in self.tool.PACK_LABELS:
            with self.subTest(pack=label):
                pack = f"pack.{label}"
                slower = values[f"{pack}.expected_chain_s.measured_basis"]
                faster = values[f"{pack}.expected_chain_s.projected"]
                for figure in (slower, faster):
                    self.assertIs(type(figure), int)
                self.assertLess(0, faster)
                self.assertLess(faster, slower)
                self.assertLess(slower, values[f"{pack}.programmed_span_s"])
                self.assertLessEqual(3 * slower, values[f"{pack}.window_max_s"])
                for entry in (f"{pack}.window_max_s", f"{pack}.programmed_span_s"):
                    what = self.document["values"][entry]["what"]
                    self.assertIn(f"{pack}.expected_chain_s.measured_basis", what)
                    self.assertIn(f"{pack}.expected_chain_s.projected", what)

    # ---------------------------------------------------------------- counterfactuals: sources held in memory

    def _overlay_for(self, ref: Any) -> dict[str, bytes]:
        """Replacement bytes that change the one source value ``ref`` reads."""

        tool = self.tool
        if ref.kind == "json":
            document = copy.deepcopy(self.sources.json(ref.file))
            set_at(document, ref.pointer, changed(get_at(document, ref.pointer)))
            return {ref.file: dump(document)}
        if ref.kind == "markdown-json":
            text = self.sources.text(ref.file)
            start, end = tool.fenced_json_span(text, ref.heading, where=ref.file)
            block = json.loads(text[start:end])
            set_at(block, ref.pointer, changed(get_at(block, ref.pointer)))
            return {ref.file: (text[:start] + json.dumps(block, indent=2) + "\n" + text[end:]).encode("utf-8")}
        if ref.kind == "markdown-line":
            text = self.sources.text(ref.file)
            self.assertEqual(text.count("Status: **"), 1)
            return {ref.file: text.replace("Status: **", "Status: **~", 1).encode("utf-8")}
        if ref.kind == "markdown-table":
            text = self.sources.text(ref.file)
            start, end = tool.table_number_span(text, *ref.args, where=ref.file)
            number = int(text[start:end].replace(",", ""))
            return {ref.file: (text[:start] + str(number + 1) + text[end:]).encode("utf-8")}
        if ref.kind == "config-set":
            configurations = tool.member_configurations(self.sources, ref.dirs, ref.where)
            self.assertTrue(configurations, ref.key)
            if ref.rule == "count":
                return {f"{ref.dirs[0]}/~probe.json": dump(configurations[0][1])}
            overlay = {}
            for relative, original in configurations:     # change every configuration alike: the value moves
                document = copy.deepcopy(original)
                set_at(document, ref.pointer, changed(get_at(document, ref.pointer)))
                overlay[relative] = dump(document)
            return overlay
        self.assertEqual(ref.kind, "derived")
        document = copy.deepcopy(self.sources.json(ref.file))
        args = ref.args
        pointer = tool.pointer_tokens(args[0])
        if ref.rule == "count":
            container = get_at(document, pointer)
            add_member(container, copy.deepcopy(container[-1]) if isinstance(container, list) else {})
        elif ref.rule in {"count_where", "keys_where"}:
            add_member(get_at(document, pointer), {args[1]: args[2]})
        elif ref.rule == "count_where2":
            add_member(get_at(document, pointer), {args[1]: args[2], args[3]: args[4]})
        elif ref.rule == "distinct":
            add_member(get_at(document, pointer), {args[1]: "~probe"})
        elif ref.rule == "sum_where":
            add_member(get_at(document, pointer), {args[2]: args[3], args[1]: 1})
        elif ref.rule == "sum_nested":
            add_member(get_at(document, pointer), {args[1]: {args[2]: 1}})
        elif ref.rule == "value_or_zero":
            parent = get_at(document, pointer[:-1])
            parent[pointer[-1]] = parent.get(pointer[-1], 0) + 1
        elif ref.rule == "common":
            container = get_at(document, pointer)
            first = container[0] if isinstance(container, list) else next(iter(container.values()))
            sub = tool.pointer_tokens(args[1])
            set_at(first, sub, changed(get_at(first, sub)))
        elif ref.rule == "stage_rows":
            first = get_at(document, pointer)[0]
            first["stage_id"] = changed(first["stage_id"])
        elif ref.rule == "first_sentence":
            set_at(document, pointer, "~" + get_at(document, pointer))
        else:
            self.fail(f"no counterfactual defined for rule {ref.rule!r}")
        return {ref.file: dump(document)}

    def _resolve_with(self, ref: Any, overlay: dict[str, bytes]) -> Any:
        sources = self.tool.Sources(self.tool.Tree(REPO_ROOT, overlay), parent=self.sources)
        return self.tool.resolve(ref, sources, self.python_values)

    def test_changing_any_file_source_changes_the_value_read_from_it(self) -> None:
        seen = set()
        for ref in self.refs:
            if ref.kind == "python" or (ref.kind, ref.file, ref.key) in seen:
                continue
            seen.add((ref.kind, ref.file, ref.key))
            with self.subTest(file=ref.file, key=ref.key):
                before = self.tool.resolve(ref, self.sources, self.python_values)
                try:
                    after = self._resolve_with(ref, self._overlay_for(ref))
                except self.tool.ExtractionError:
                    continue        # the extraction fails: nothing would be written
                self.assertFalse(self.tool.same_value(before, after), f"still {before!r}")
        self.assertGreater(len(seen), 250)

    def test_a_shared_setting_that_one_configuration_changes_stops_the_extraction(self) -> None:
        ref = next(entry.ref for entry in self.entries if entry.id == "member.idle_seconds")
        relative, original = self.tool.member_configurations(self.sources, ref.dirs, ref.where)[0]
        document = copy.deepcopy(original)
        document["sampling"]["idle_seconds"] += 1
        with self.assertRaises(self.tool.ExtractionError):
            self._resolve_with(ref, {relative: dump(document)})

    def test_a_changed_source_value_changes_the_table_and_is_named(self) -> None:
        sizing = copy.deepcopy(self.sources.json(self.tool.SIZING))
        sizing["packs"]["BETA"]["window_max_s"] += 60
        tree = self.tool.Tree(REPO_ROOT, {self.tool.SIZING: dump(sizing)})
        produced = self.tool.render(self.tool.build_document(tree, self.python_values, self.entries))
        self.assertNotEqual(produced, self.committed)
        lines = self.tool.describe_difference(self.committed, produced)
        self.assertEqual(len(lines), 1, lines)
        self.assertTrue(lines[0].startswith("pack.BETA.window_max_s: value 104580"), lines)

    def test_a_disagreement_between_two_places_is_listed(self) -> None:
        text = self.sources.text(self.tool.REGISTRATION)
        start, end = self.tool.fenced_json_span(text, self.tool.ARM_HEADING, where="registration")
        block = json.loads(text[start:end])
        block["contention"]["clean_s"] = 600      # the value plans written before revision 5 carried
        changed_text = text[:start] + json.dumps(block, indent=2) + "\n" + text[end:]
        tree = self.tool.Tree(REPO_ROOT, {self.tool.REGISTRATION: changed_text.encode("utf-8")})
        document = self.tool.build_document(tree, self.python_values, self.entries)
        self.assertEqual(document["disagreements"], ["arm.contention.clean_s"])
        self.assertEqual(document["values"]["arm.contention.clean_s"]["value"], 600)

    # ---------------------------------------------------------------- counterfactuals: module constants

    def test_changing_any_module_constant_changes_the_value_read_from_it(self) -> None:
        tool = self.tool
        python_refs = {tool.python_key(ref): ref for ref in self.refs if ref.kind == "python"}
        self.assertGreater(len(python_refs), 100)
        with tempfile.TemporaryDirectory(prefix="paper-b-registered-values-") as scratch_name:
            scratch = Path(scratch_name).resolve()
            ignore = shutil.ignore_patterns("__pycache__", "*.pyc")
            for package in ("joulewise", "scripts"):
                shutil.copytree(REPO_ROOT / package, scratch / package, ignore=ignore)
            # Read-only inputs are linked, never copied or written: only the two copied packages are changed.
            os.symlink(REPO_ROOT / "configs", scratch / "configs")

            unchanged = tool.read_python_constants(scratch, list(python_refs.values()))
            self.assertEqual(unchanged, {key: self.python_values[key] for key in python_refs},
                             "the scratch copy does not give the repository's values")

            def rewrite(relative: str, refs: list[Any]) -> None:
                source = (REPO_ROOT / relative).read_bytes()
                spans = sorted(((python_value_span(source, ref.symbol, ref.pointer), ref) for ref in refs),
                               key=lambda item: item[0][0], reverse=True)
                for index in range(len(spans) - 1):
                    self.assertGreaterEqual(spans[index][0][0], spans[index + 1][0][1],
                                            f"{relative}: two entries read overlapping expressions")
                for (start, end), ref in spans:
                    replacement = python_changed_expression(source[start:end],
                                                            self.python_values[tool.python_key(ref)])
                    source = source[:start] + replacement + source[end:]
                (scratch / relative).write_bytes(source)

            def restore(relative: str) -> None:
                shutil.copyfile(REPO_ROOT / relative, scratch / relative)

            by_file: dict[str, list[Any]] = {}
            for ref in python_refs.values():
                by_file.setdefault(ref.file, []).append(ref)

            # One run with every constant changed at once.
            for relative, refs in by_file.items():
                rewrite(relative, refs)
            together = tool.read_python_constants(scratch, list(python_refs.values()))
            for relative in by_file:
                restore(relative)
            # A constant computed from another one could, in principle, have had the two changes cancel:
            # any such constant is changed again on its own.
            alone = [key for key in python_refs if tool.same_value(together[key], self.python_values[key])]
            for key in alone:
                ref = python_refs[key]
                rewrite(ref.file, [ref])
                together[key] = tool.read_python_constants(scratch, [ref])[key]
                restore(ref.file)
            for key, ref in python_refs.items():
                with self.subTest(file=ref.file, key=ref.key):
                    self.assertFalse(tool.same_value(together[key], self.python_values[key]),
                                     f"still {self.python_values[key]!r}")

            # End to end through the command line: one constant changed, the committed table refused.
            before = subprocess.run([sys.executable, "-B", str(TOOL_PATH), "--root", str(scratch), "--check",
                                     "--against", str(self.committed_path)], capture_output=True, text=True,
                                    cwd=str(scratch), timeout=300, check=False)
            self.assertEqual(before.returncode, 0, before.stderr)
            settle = next(entry.ref for entry in self.entries if entry.id == "chain.settle_s")
            rewrite(settle.file, [settle])
            after = subprocess.run([sys.executable, "-B", str(TOOL_PATH), "--root", str(scratch), "--check",
                                    "--against", str(self.committed_path)], capture_output=True, text=True,
                                   cwd=str(scratch), timeout=300, check=False)
            self.assertEqual(after.returncode, 1, after.stderr)
            self.assertIn("chain.settle_s: value 60 in the committed file, 61 now", after.stderr)
            # The settle also feeds the post-capture reserve and disagrees with the sizing output's copy.
            self.assertIn("chain.horizon.post_reserve_s: value 1430 in the committed file, 1431 now", after.stderr)
            self.assertIn("DISAGREEMENT chain.settle_s", after.stderr)
            self.assertFalse((scratch / tool.OUTPUT_RELATIVE).exists(), "--check must not write the table")

    # ---------------------------------------------------------------- small parts

    def test_pointer_and_value_rules(self) -> None:
        tool = self.tool
        self.assertEqual(tool.pointer_tokens("/units/A~1decode/x~0y"), ("units", "A/decode", "x~y"))
        self.assertEqual(tool.pointer_tokens(""), ())
        with self.assertRaises(tool.ExtractionError):
            tool.pointer_tokens("units")
        self.assertTrue(tool.same_value(120, 120.0))
        self.assertFalse(tool.same_value(True, 1))
        self.assertFalse(tool.same_value("1", 1))
        self.assertTrue(tool.same_value([1, {"a": None}], [1.0, {"a": None}]))

    def test_fenced_block_needs_exactly_one_heading(self) -> None:
        tool = self.tool
        text = "# T\n\n### 4.3 Registered thresholds\n\ntext\n\n```json\n{\"a\": 1}\n```\n\n### 4.4 Next\n"
        self.assertEqual(tool.fenced_json(text, "Registered thresholds", where="t"), {"a": 1})
        with self.assertRaises(tool.ExtractionError):
            tool.fenced_json(text + "\n## Registered thresholds\n", "Registered thresholds", where="t")
        with self.assertRaises(tool.ExtractionError):
            tool.fenced_json(text, "Next", where="t")       # a heading with no json block under it
        with self.assertRaises(tool.ExtractionError):
            tool.fenced_json(text, "Absent", where="t")

    def test_table_number_needs_one_table_one_row_and_a_number_with_its_unit(self) -> None:
        tool = self.tool
        text = ("intro\n\n"
                "  | Pack | Deadline | Expected chain |\n"
                "  |---|---|---|\n"
                "  | ALPHA | 102,180 s (28.4 h) | 19,460 s (5.4 h) |\n"
                "  | BETA | 104580 s | about 5.7 h |\n"
                "\n"
                "| Pack | Other |\n|---|---|\n| ALPHA | 7 s |\n")
        self.assertEqual(tool.table_number(text, "Expected chain", "ALPHA", "s", where="t"), 19460)
        self.assertEqual(tool.table_number(text, "Deadline", "ALPHA", "s", where="t"), 102180)
        self.assertEqual(tool.table_number(text, "Deadline", "BETA", "s", where="t"), 104580)
        self.assertEqual(tool.table_number(text, "Other", "ALPHA", "s", where="t"), 7)
        start, end = tool.table_number_span(text, "Expected chain", "ALPHA", "s", where="t")
        self.assertEqual(text[start:end], "19,460")
        refused = (
            (text, "Absent", "ALPHA", "s"),                 # no table has the column
            (text, "Pack", "ALPHA", "s"),                   # two tables have the column
            (text, "Expected chain", "GAMMA", "s"),         # no such row
            (text, "Expected chain", "BETA", "s"),          # the cell does not open with a number
            (text, "Expected chain", "ALPHA", "h"),         # the number is in another unit
            (text.replace("19,460 s (5.4 h)", "19,460 sec"), "Expected chain", "ALPHA", "s"),  # the unit is whole
            (text.replace("| BETA | 104580 s |", "| ALPHA | 104580 s |"), "Deadline", "ALPHA", "s"),   # two rows
            (text.replace("19,460 s", "19,46 s"), "Expected chain", "ALPHA", "s"),     # digits not in threes
            (text.replace(" | 19,460 s (5.4 h) |", " |"), "Deadline", "ALPHA", "s"),   # a row short of a cell
        )
        for case in refused:
            with self.subTest(column=case[1], row=case[2], unit=case[3]):
                with self.assertRaises(tool.ExtractionError):
                    tool.table_number(*case, where="t")


if __name__ == "__main__":
    unittest.main()
