#!/bin/zsh
# GENERATED by scripts/gen_evidence_night.py; do not edit.
set -euo pipefail
export NIGHT_PAYLOAD_KIND=quiet_predicate_evidence
export PYTHONDONTWRITEBYTECODE=1
export EVIDENCE_PLAN_PATH='/Users/edr/night-custody/qpe01-pilot-n1-20260919/night_plan.json'
export EVIDENCE_MANIFEST_PATH='/Users/edr/night-custody/qpe01-pilot-n1-20260919/evidence_manifest.json'
export EVIDENCE_MANIFEST_SHA256='d01ccc90003239d832f3551de259265c218e8765f1bac278fa6d57ccb110b563'
export EVIDENCE_CHAIN_SOURCE_SHA256='568a2771b28da9d805cd23ff4059bbbc27d6dfad1f8d9603331a412e3751b7ea'
export PY='/Users/edr/JouleWise-measurement-20260919-qpe01-pilot-n1/.venv/bin/python'
export PYTHONPATH='/Users/edr/JouleWise-measurement-20260919-qpe01-pilot-n1'
refuse() { "$PY" -B -m joulewise.quiet_predicate_campaign refuse --reason "$1"; exit 2; }
[[ "${NIGHT_PLAN_ID:-}" == 'qpe01-pilot-n1-20260919' ]] || refuse 'NIGHT_PLAN_ID mismatch'
[[ "${MEASUREMENT_ROOT:-}" == '/Users/edr/JouleWise-measurement-20260919-qpe01-pilot-n1' ]] || refuse 'MEASUREMENT_ROOT mismatch'
[[ "${MEASUREMENT_HEAD:-}" == '4f2aa185e1dc362b8e299353ce357c873c2f97a0' ]] || refuse 'MEASUREMENT_HEAD mismatch'
[[ "$(/usr/bin/shasum -a 256 '/Users/edr/JouleWise-measurement-20260919-qpe01-pilot-n1/scripts/night_chains/quiet_predicate_evidence.zsh' | /usr/bin/awk '{print $1}')" == "$EVIDENCE_CHAIN_SOURCE_SHA256" ]] || refuse chain_source_sha256_mismatch
exec /bin/zsh '/Users/edr/JouleWise-measurement-20260919-qpe01-pilot-n1/scripts/night_chains/quiet_predicate_evidence.zsh'
