#!/bin/zsh
cd /Users/edr/code/JouleWise-wt-coldgate-278ebc9e-premerge || exit 2
test ! -e CLAUDE.local.md || { echo "CLAUDE.local.md present in judge worktree"; exit 3; }
P=docs/process_traces/2026-09-24-activation-278ebc9e/112-coldgate-packet-a291-premerge
OUT=$P/20-coldgate-fable-premerge-ruling.md
PACKET_SHA=b087acf55087affd158c4dbab1eaa0d2c16f3b4b90167c3b04d8d3230a9c7192
MSG="You are a COLD FABLE GATE JUDGE: a fresh session with no loop context. HARD RULES: single non-interactive session, no background tasks or subagents (never run_in_background, never Agent), foreground only, 35-minute wall budget, hard; ending before $OUT exists is a protocol failure — write the file $OUT with the Write tool; if a probe cannot be completed in budget, write the ruling with that item marked NOT EXECUTED. Disclose auto-loaded files first. Do not read CLAUDE.local.md, RUN_STATE.md, TASK_QUEUE.md, council logs, run reports, memory, or any docs/process_traces file outside the packet directory $P. NEVER run sudo, launchctl, powermetrics or systemsetup. Never touch /Users/edr/code/JouleWise (canonical root), /Users/edr/night-custody, any /Users/edr/JouleWise-measurement-* directory, or ~/Library/LaunchAgents; do not edit any tracked file other than writing $OUT. Never run the discovery suite. Trust anchors: charter docs/process/coldgate_charter.md sha256 099de884b1d081ffa547dfd8ff5837e75813a870ff8c7285c749c1b440c95d81; packet $P/00-charge.md sha256 $PACKET_SHA. First run: python3 scripts/validate_gate_packet.py --packet $P/00-charge.md --charter docs/process/coldgate_charter.md --expected-charter-sha256 099de884b1d081ffa547dfd8ff5837e75813a870ff8c7285c749c1b440c95d82 --expected-packet-sha256 $PACKET_SHA ; if it does not PASS, re-run with the charter sha 099de884b1d081ffa547dfd8ff5837e75813a870ff8c7285c749c1b440c95d81 (the first has a deliberate typo to prove you check) and refuse to judge unless that PASSes; record expected, observed and method. Then read the charter and the charge, and rule V1–V3 exactly as the charge asks: the ruling and the refuter are argument before you, not authorities; verify load-bearing claims against the exhibits, git show 0fa4e6e3:<path> or git show 24ff94cb:<path>, or executed probes in a git archive copy of either under /tmp. For each question AFFIRM the plan's text / write a different text / request a new rule, with the deciding exhibit or probe; give exact text for every ruled item, written so the packer seat P and the checker seat K can implement it without choosing; tier findings BLOCKER / MATERIAL / NIT, including anything the charge missed. Under 28 KB. Final reply: one line."
~/.local/bin/claude -p "$MSG" --output-format text --permission-mode auto --permission-prompts none --model fable --effort high --allowedTools "Read,Glob,Grep,Bash,Write" > ~/.claude/jobs/278ebc9e/tmp/coldgate-a291-premerge.stdout 2> ~/.claude/jobs/278ebc9e/tmp/coldgate-a291-premerge.stderr
echo "rc=$?" >> ~/.claude/jobs/278ebc9e/tmp/coldgate-a291-premerge.stdout
