#!/usr/bin/env python3
"""RPT-001 capstone report assembler (stdlib only).

Reads the report profile ``docs/report_src/report.json``, regenerates the
results vertical-slice page ``docs/report_src/generated/rpt001_vertical_slice.md``
from the committed rpt001-v1 analysis artifacts, resolves
``{{jw:include path="..."}}`` directives, and assembles the full report at
``build/capstone/rpt001/report.md``.

Deterministic: no timestamps, no absolute paths, normalized newlines.

Usage:
    python3 scripts/build_capstone.py --profile rpt001
    python3 scripts/build_capstone.py --profile rpt001 --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "docs" / "report_src"
ANALYSIS = REPO_ROOT / "analysis" / "rpt001-v1"
FIGURE_REL = "figures/rpt001-v1/F1_legacy_l1_instrument_results.svg"
GENERATED_HEADER = "<!-- GENERATED by scripts/build_capstone.py; DO NOT EDIT. -->\n"
PROFILE_SCHEMA = "joulewise.report_profile.v1"
LEGACY_LABEL = "legacy L1 (manual review; pre-2M)"

INCLUDE_RE = re.compile(r'^\{\{jw:include path="([^"]+)"\}\}\s*$', re.MULTILINE)

REGEN_COMMAND = (
    "python3 scripts/build_capstone.py --profile rpt001 --full --offline "
    "--runs-root /Users/edr/code/JouleWise/runs"
)

# This report-text scan is only a tripwire; claims_lint phase4 is the gate of record.
FORBIDDEN_PHRASES = [re.compile(p, re.IGNORECASE) for p in (
    r"\b(?:more|less)\s+efficient\b", r"\bscales?\s+with\s+model\s+size\b",
    r"\bstatistically\s+significant\b", r"\bclears?\s+the\s+detection\s+floor\b",
    r"\buses?\s+less\s+energy\b", r"\blower\s+energy\s+consumption\b",
    r"\b(?:\d+(?:\.\d+)?\s*[x×]\s+)?energy\s+savings?\b", r"\boutperforms?\b",
    r"\benergy\s+consumption\s+increases?\s+with\s+parameter\s+count\b",
)]


def fail(msg: str) -> None:
    print(f"build_capstone: ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_profile() -> dict:
    profile = json.loads((SRC / "report.json").read_text(encoding="utf-8"))
    if profile.get("schema") != PROFILE_SCHEMA:
        fail(f"unknown report profile schema: {profile.get('schema')!r}")
    chapters = profile.get("chapters", [])
    if not chapters:
        fail("profile lists no chapters")
    if len(set(chapters)) != len(chapters):
        fail("duplicate chapter paths in profile")
    for chapter in chapters:
        p = Path(chapter)
        if p.is_absolute() or ".." in p.parts:
            fail(f"chapter path escapes docs/report_src/: {chapter}")
        if not (SRC / p).is_file():
            fail(f"missing chapter: {chapter}")
    adapter = profile.get("format_adapter", {})
    if adapter.get("renderer") not in (None,):
        fail("format adapter renderer is pending P1-008; only null is accepted")
    return profile


def generate_results_page() -> str:
    claims = json.loads((ANALYSIS / "claims_index.jsonl").read_text(encoding="utf-8"))
    t1_md = (ANALYSIS / "tables" / "T1_legacy_l1_results.md").read_text(encoding="utf-8")
    s1_md = (ANALYSIS / "tables" / "S1_legacy_stack_identity.md").read_text(encoding="utf-8")
    waiver_lines = "\n".join(
        f"- **{w['scope']}** — {w['reason']}" for w in claims["quality_waivers"]
    )
    page = f"""{GENERATED_HEADER}
## Legacy vertical-slice instrument results

This page exists to test the analysis-to-report path end to end: six pinned
strict-valid legacy bundles flow through the shared read layer into a sealed
dataset, an aggregate artifact, one figure, two tables, and one claims-index
row. It demonstrates the graded-artifact pipeline; it makes **no comparative
or scaling finding**.

Evidence class: **{LEGACY_LABEL}**.

### Figure F1

![Figure F1: per-request energy by exact stack — {LEGACY_LABEL}](../../../{FIGURE_REL})

Figure F1: Per-request energy by exact stack, {LEGACY_LABEL}. Panel A shows
idle-subtracted request energy (primary basis) alongside gross request energy
(context basis); Panel B shows the idle-subtracted per-output-token companion
in mJ per runtime-observed output token. Points are the three retained
sequential repetitions; the marker is the arithmetic mean and the whisker is
the observed min–max range, not a confidence interval. Descriptive
stack-specific observations only; no cross-stack efficiency or scaling claim.
Full stack identities: Table S1.

### Table T1

{t1_md}
### Quality waivers

{waiver_lines}

### Table S1

{s1_md}
### Limitations carried by this page

All observations on this page come from a single physical hardware unit; they
characterize that exact unit and stack, not the hardware model line (D-052
single-unit limitation). Output-token values use runtime-observed counts;
tokenizer identity was not captured in these legacy bundles, so per-token
values are tokenizer-scoped descriptors, not comparable work units (D-058).

### Claims index

Claims row: `{claims["claim_id"]}` in `analysis/rpt001-v1/claims_index.jsonl`.

### Regeneration

```sh
{REGEN_COMMAND}
```

Artifact hashes: `analysis/rpt001-v1/artifact_manifest.json`.
"""
    return page


def assemble(profile: dict) -> str:
    parts = [GENERATED_HEADER, "\n"]
    for chapter in profile["chapters"]:
        text = (SRC / chapter).read_text(encoding="utf-8").replace("\r\n", "\n")

        def _include(match: re.Match) -> str:
            rel = match.group(1)
            p = Path(rel)
            if p.is_absolute() or ".." in p.parts:
                fail(f"include path escapes docs/report_src/: {rel}")
            target = SRC / p
            if not target.is_file():
                fail(f"unresolved include in {chapter}: {rel}")
            return target.read_text(encoding="utf-8").replace("\r\n", "\n")

        text = INCLUDE_RE.sub(_include, text)
        if INCLUDE_RE.search(text):
            fail(f"unresolved include directive remains in {chapter}")
        parts.append(text.rstrip("\n") + "\n\n")
    doc = "".join(parts).rstrip("\n") + "\n"
    for phrase in FORBIDDEN_PHRASES:
        if phrase.search(doc):
            fail(f"forbidden phrase in assembled report: {phrase.pattern!r}")
    return doc


def verify_artifact_manifest() -> None:
    path = ANALYSIS / "artifact_manifest.json"
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("schema") != "joulewise.report_artifact_manifest.v1":
        fail("unknown artifact manifest schema")
    for rel, expected in manifest.get("outputs", {}).items():
        target = REPO_ROOT / rel
        if not target.is_file():
            fail(f"artifact manifest output missing: {rel}")
        actual = hashlib.sha256(target.read_bytes()).hexdigest()
        if actual != expected:
            fail(f"artifact manifest hash mismatch: {rel}")


def run_full(runs_root: Path, offline: bool) -> None:
    # All steps are local and stdlib-only; --offline makes that contract explicit.
    figure_cmd = [sys.executable, "scripts/make_figures.py", "--runs-root", str(runs_root),
                  "--input-manifest", "analysis/rpt001-v1/input_manifest.json"]
    if offline:
        figure_cmd.append("--offline")
    subprocess.run(figure_cmd, cwd=REPO_ROOT, check=True)
    subprocess.run([sys.executable, "scripts/claims_lint.py", "--mode", "phase4",
                    "--write-projection"], cwd=REPO_ROOT, check=True)
    verify_artifact_manifest()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", default="rpt001")
    ap.add_argument("--check", action="store_true",
                    help="Compare regenerated outputs against committed/built files; exit 2 on drift.")
    ap.add_argument("--full", action="store_true",
                    help="Regenerate analysis, lint claims, verify hashes, then assemble.")
    ap.add_argument("--offline", action="store_true",
                    help="Run only the explicitly network-free build path.")
    ap.add_argument("--runs-root", type=Path, default=Path("runs"))
    args = ap.parse_args()
    if args.profile != "rpt001":
        fail(f"unknown profile: {args.profile}")

    if args.full:
        run_full(args.runs_root, args.offline)
    verify_artifact_manifest()
    profile = load_profile()
    results_page = generate_results_page()
    gen_path = SRC / "generated" / "rpt001_vertical_slice.md"

    if args.check:
        drift = []
        if not gen_path.is_file() or gen_path.read_text(encoding="utf-8") != results_page:
            drift.append(str(gen_path.relative_to(REPO_ROOT)))
        out_path = REPO_ROOT / "build" / "capstone" / "rpt001" / "report.md"
        assembled = assemble(profile)
        if not out_path.is_file() or out_path.read_text(encoding="utf-8") != assembled:
            drift.append("build/capstone/rpt001/report.md")
        if drift:
            print(f"build_capstone: DRIFT in {drift[0]}", file=sys.stderr)
            return 2
        print("build_capstone: check OK (no drift)")
        return 0

    gen_path.parent.mkdir(parents=True, exist_ok=True)
    gen_path.write_text(results_page, encoding="utf-8", newline="\n")
    assembled = assemble(profile)
    out_path = REPO_ROOT / "build" / "capstone" / "rpt001" / "report.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(assembled, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(assembled.encode("utf-8")).hexdigest()
    print(f"build_capstone: assembled build/capstone/rpt001/report.md sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
