#!/usr/bin/env python3
"""RPT-001/RPT-002 capstone report assembler (stdlib only).

Reads the report profile ``docs/report_src/report.json``, regenerates the
results vertical-slice page ``docs/report_src/generated/rpt001_vertical_slice.md``
as a voided historical pipeline demonstration, resolves
``{{jw:include path="..."}}`` directives, and assembles the full report at
``build/capstone/rpt001/report.md``.

Deterministic: no timestamps, no absolute paths, normalized newlines.

Usage:
    python3 scripts/build_capstone.py --profile rpt001
    python3 scripts/build_capstone.py --profile rpt001 --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "docs" / "report_src"
ANALYSIS = REPO_ROOT / "analysis" / "rpt001-v2"
GENERATED_HEADER = "<!-- GENERATED by scripts/build_capstone.py; DO NOT EDIT. -->\n"
PROFILE_SCHEMA = "joulewise.report_profile.v1"
SOURCE_MAP_SCHEMA = "joulewise.report_source_map.v1"
LEGACY_LABEL = "VOIDED historical evidence — permanently ineligible for claim use"

INCLUDE_RE = re.compile(r'^\{\{jw:include path="([^"]+)"\}\}\s*$', re.MULTILINE)
CITATION_RE = re.compile(r"@([A-Za-z0-9_.:-]+)")

SEEDED_BIBLIOGRAPHY_IDS = {
    "joulesort2007", "splitwise-isca2024", "distserve", "mooncake",
    "mlperf_power", "zeus", "tokenpowerbench", "mlenergy_benchmark",
    "intelligence_per_watt", "bench360", "chung2026joules",
}
RPT002_SOURCE_IDS = {
    "revisiting-disaggregation-energy-2026", "dualscale-2026",
    "prima-cpp-2025", "splitzip-2026", "systematic-quantization-2025",
    "sustainable-edge-ai-2025", "silicon-showdown-2026",
}
VERIFICATION_STATUSES = {"UNVERIFIED_BY_SESSION", "VERIFIED_AGAINST_PRIMARY"}

CHECK_COMMAND = (
    "python3 scripts/build_capstone.py --profile rpt001 --offline --check"
)

# This report-text scan is only a tripwire; claims_lint phase4 is the gate of record.
FORBIDDEN_PHRASES = [re.compile(p, re.IGNORECASE) for p in (
    r"\b(?:more|less)\s+efficient\b", r"\bscales?\s+with\s+model\s+size\b",
    r"\bstatistically\s+significant\b", r"\bclears?\s+the\s+detection\s+floor\b",
    r"\buses?\s+less\s+energy\b", r"\blower\s+energy\s+consumption\b",
    r"\b(?:\d+(?:\.\d+)?\s*[x×]\s+)?energy\s+savings?\b", r"\boutperforms?\b",
    r"\benergy\s+consumption\s+increases?\s+with\s+parameter\s+count\b",
)]


def fail(msg: str) -> None:
    print(f"build_capstone: ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_profile() -> dict:
    profile = json.loads((SRC / "report.json").read_text(encoding="utf-8"))
    if profile.get("schema") != PROFILE_SCHEMA:
        fail(f"unknown report profile schema: {profile.get('schema')!r}")
    chapters = profile.get("chapters", [])
    if not chapters:
        fail("profile lists no chapters")
    if len(set(chapters)) != len(chapters):
        fail("duplicate chapter paths in profile")
    for chapter in chapters:
        p = Path(chapter)
        if p.is_absolute() or ".." in p.parts:
            fail(f"chapter path escapes docs/report_src/: {chapter}")
        if not (SRC / p).is_file():
            fail(f"missing chapter: {chapter}")
    adapter = profile.get("format_adapter", {})
    if adapter.get("renderer") not in (None,):
        fail("format adapter renderer is pending P1-008; only null is accepted")
    return profile


def _profile_file(profile: dict, field: str) -> Path:
    rel = profile.get(field)
    if not isinstance(rel, str) or not rel:
        fail(f"profile has no {field!r} path")
    path = Path(rel)
    if path.is_absolute() or ".." in path.parts:
        fail(f"{field} path escapes docs/report_src/: {rel}")
    target = SRC / path
    if not target.is_file():
        fail(f"missing {field}: {rel}")
    return target


def validate_bibliography(profile: dict) -> None:
    """Validate canonical citation metadata and the RPT-002 source map offline."""
    bibliography_path = _profile_file(profile, "bibliography")
    try:
        bibliography = json.loads(bibliography_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"invalid bibliography JSON: {exc}")
    if not isinstance(bibliography, list) or not bibliography:
        fail("bibliography must be a non-empty CSL JSON array")

    by_id = {}
    for index, item in enumerate(bibliography):
        if not isinstance(item, dict):
            fail(f"bibliography item {index} is not an object")
        citation_id = item.get("id")
        if not isinstance(citation_id, str) or not citation_id.strip():
            fail(f"bibliography item {index} has no non-empty id")
        if citation_id in by_id:
            fail(f"duplicate bibliography id: {citation_id}")
        for field in ("type", "title"):
            if not isinstance(item.get(field), str) or not item[field].strip():
                fail(f"bibliography item {citation_id} has no non-empty {field}")
        for field in ("DOI", "URL"):
            if field in item and not isinstance(item[field], str):
                fail(f"bibliography item {citation_id} {field} must be a string")
        by_id[citation_id] = item

    missing_seeded = sorted((SEEDED_BIBLIOGRAPHY_IDS | RPT002_SOURCE_IDS) - by_id.keys())
    if missing_seeded:
        fail(f"bibliography is missing required id: {missing_seeded[0]}")

    source_map_path = _profile_file(profile, "source_map")
    try:
        source_map = json.loads(source_map_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"invalid source-map JSON: {exc}")
    if source_map.get("schema") != SOURCE_MAP_SCHEMA:
        fail(f"unknown source-map schema: {source_map.get('schema')!r}")
    sources = source_map.get("sources")
    if not isinstance(sources, list):
        fail("source map sources must be an array")
    mapped_ids = [source.get("id") for source in sources if isinstance(source, dict)]
    if len(mapped_ids) != len(sources) or len(set(mapped_ids)) != len(mapped_ids):
        fail("source map ids must be unique non-empty object fields")
    if set(mapped_ids) != RPT002_SOURCE_IDS:
        fail("source map must contain exactly the seven RPT-002 source ids")
    for source in sources:
        source_id = source["id"]
        if source.get("verification_status") not in VERIFICATION_STATUSES:
            fail(f"source {source_id} has unknown verification_status")
        if source.get("primary_url") != by_id[source_id].get("URL"):
            fail(f"source {source_id} primary_url differs from bibliography URL")
        if not isinstance(source.get("retrieval_date"), str) or not source["retrieval_date"]:
            fail(f"source {source_id} has no retrieval-date placeholder")
        for field in ("claim_role", "evidence_locations", "feeds",
                      "lead_verification_required"):
            value = source.get(field)
            if not value or not isinstance(value, (str, list)):
                fail(f"source {source_id} has no {field}")

    cited = set()
    for chapter in profile["chapters"]:
        cited.update(CITATION_RE.findall((SRC / chapter).read_text(encoding="utf-8")))
    unresolved = sorted(cited - by_id.keys())
    if unresolved:
        fail(f"unresolved citation key: {unresolved[0]}")
    unused = sorted(by_id.keys() - cited)
    if unused:
        print(f"build_capstone: WARNING: unused bibliography id: {unused[0]}", file=sys.stderr)


def generate_results_page() -> str:
    page = f"""{GENERATED_HEADER}
## VOIDED historical pipeline demonstration

This page exists only to demonstrate the historical analysis-to-report path.
The legacy corpus passed evidence-path checks, but its energy outputs are
permanently voided for claim use because the pre-repair time anchor made the
physical time attribution invalid.

Evidence class: **{LEGACY_LABEL}**, per the
[root README void disposition](../../../README.md#current-state).

No energy-result table or energy values from that corpus are reproduced here.

The v2 figure path contains only a void placeholder; it is not rendered here.

### Demonstration check

The source-only check reproducibly confirms this void disposition and report
assembly from a pristine clone:

```sh
{CHECK_COMMAND}
```

The regenerated paths under `analysis/rpt001-v2/` and `figures/rpt001-v2/`
carry only the void disposition and no legacy-corpus measurement values.
"""
    return page


def assemble(profile: dict) -> str:
    parts = [GENERATED_HEADER, "\n"]
    for chapter in profile["chapters"]:
        text = (SRC / chapter).read_text(encoding="utf-8").replace("\r\n", "\n")

        def _include(match: re.Match) -> str:
            rel = match.group(1)
            p = Path(rel)
            if p.is_absolute() or ".." in p.parts:
                fail(f"include path escapes docs/report_src/: {rel}")
            target = SRC / p
            if not target.is_file():
                fail(f"unresolved include in {chapter}: {rel}")
            return target.read_text(encoding="utf-8").replace("\r\n", "\n")

        text = INCLUDE_RE.sub(_include, text)
        if INCLUDE_RE.search(text):
            fail(f"unresolved include directive remains in {chapter}")
        parts.append(text.rstrip("\n") + "\n\n")
    doc = "".join(parts).rstrip("\n") + "\n"
    for phrase in FORBIDDEN_PHRASES:
        if phrase.search(doc):
            fail(f"forbidden phrase in assembled report: {phrase.pattern!r}")
    return doc


def verify_artifact_manifest() -> None:
    path = ANALYSIS / "artifact_manifest.json"
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("schema") != "joulewise.report_artifact_manifest.v1":
        fail("unknown artifact manifest schema")
    for rel, expected in manifest.get("outputs", {}).items():
        target = REPO_ROOT / rel
        if not target.is_file():
            fail(f"artifact manifest output missing: {rel}")
        actual = hashlib.sha256(target.read_bytes()).hexdigest()
        if actual != expected:
            fail(f"artifact manifest hash mismatch: {rel}")


def run_full(runs_root: Path, offline: bool) -> None:
    # All steps are local and stdlib-only; --offline makes that contract explicit.
    figure_cmd = [sys.executable, "scripts/make_figures.py", "--runs-root", str(runs_root),
                  "--input-manifest", "analysis/rpt001-v2/input_manifest.json"]
    if offline:
        figure_cmd.append("--offline")
    subprocess.run(figure_cmd, cwd=REPO_ROOT, check=True)
    subprocess.run([sys.executable, "scripts/claims_lint.py", "--mode", "phase4",
                    "--write-projection"], cwd=REPO_ROOT, check=True)
    verify_artifact_manifest()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", default="rpt001")
    ap.add_argument("--check", action="store_true",
                    help="Compare regenerated outputs against tracked sources; exit 2 on drift.")
    ap.add_argument("--full", action="store_true",
                    help="Authenticate inputs, regenerate void artifacts, lint claims, then assemble.")
    ap.add_argument("--offline", action="store_true",
                    help="Run only the explicitly network-free build path.")
    ap.add_argument("--runs-root", type=Path, default=Path("runs"))
    args = ap.parse_args()
    if args.profile != "rpt001":
        fail(f"unknown profile: {args.profile}")

    if args.full:
        run_full(args.runs_root, args.offline)
    verify_artifact_manifest()
    profile = load_profile()
    validate_bibliography(profile)
    results_page = generate_results_page()
    gen_path = SRC / "generated" / "rpt001_vertical_slice.md"

    if args.check:
        drift = []
        if not gen_path.is_file() or gen_path.read_text(encoding="utf-8") != results_page:
            drift.append(str(gen_path.relative_to(REPO_ROOT)))
        # Validate assembly from tracked source without treating the untracked
        # build product as a reference. This keeps --check clean-clone safe.
        assemble(profile)
        if drift:
            print(f"build_capstone: DRIFT in {drift[0]}", file=sys.stderr)
            return 2
        print("build_capstone: check OK (no drift)")
        return 0

    gen_path.parent.mkdir(parents=True, exist_ok=True)
    gen_path.write_text(results_page, encoding="utf-8", newline="\n")
    assembled = assemble(profile)
    out_path = REPO_ROOT / "build" / "capstone" / "rpt001" / "report.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(assembled, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(assembled.encode("utf-8")).hexdigest()
    print(f"build_capstone: assembled build/capstone/rpt001/report.md sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
