#!/usr/bin/env python3
"""Registered dependence sensitivity for one ten-block ABBA contrast.

The command takes an authenticated JSON list of ten ordered B-minus-A block
deltas, the registered resolution floor, the stochastic-metrology standard
error carried by the analysis-engine artifact, and the deterministic-bound
total carried by that artifact.  It recomputes the registered composition
under three fixed dependence models.  It does not decide the two-contrast
Holm family procedure.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
import re
import shlex
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from string import Template
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from joulewise.analysis_engine.distributions import (
    student_t_quantile,
    two_sided_student_t_p_value,
)


SCHEMA_VERSION = "joulewise.dependence_sensitivity.v1"
REGISTERED_ALPHA = 0.05
REGISTERED_N_BLOCKS = 10
EXAMPLE_FLOOR_J = 3.5
# These two values are invented solely for the arithmetic example.  Their
# field names match PairedEstimate.se_metrology and
# PairedEstimate.deterministic_bound_total in analysis_engine/estimators.py.
EXAMPLE_SE_METROLOGY_J = 0.2
EXAMPLE_DETERMINISTIC_BOUND_TOTAL_J = 4.0
# Mean 5 J, sample standard deviation 1.4 J, and centred lag-one slope 0.3
# exactly.
EXAMPLE_BLOCK_DELTAS_J = [
    5.0,
    7.6,
    5.5,
    4.2,
    4.7,
    6.8,
    5.5,
    3.6,
    3.9,
    3.2,
]
DISAGREEMENT_DETERMINISTIC_BOUND_TOTAL_J = 3.5
REGISTERED_MULTIPLICITY = 2
SENSITIVITY_RHOS = (0.5, 0.9)

SHEET_TEMPLATE_PATH = (
    REPO_ROOT / "docs" / "paper" / "round7" / "dependence-sensitivity.md.in"
)
SHEET_OUTPUT_PATH = (
    REPO_ROOT / "docs" / "paper" / "round7" / "dependence-sensitivity.md"
)
DRAFT_PATH = REPO_ROOT / "docs" / "paper" / "draft-v1.md"
RETENSING_PLAN_PATH = REPO_ROOT / "docs" / "paper" / "round7" / "retensing-plan.md"
CONFIG_GENERATOR_PATH = (
    REPO_ROOT / "configs" / "campaigns" / "d117_contrast_v5" / "generate_configs.py"
)
GENERATED_HEADER = (
    "<!-- GENERATED by scripts/dependence_sensitivity.py --render-sheet from "
    "dependence-sensitivity.md.in; DO NOT EDIT. -->\n"
)
CONFIG_FIELD_NAMES = frozenset({"family_alpha", "multiplicity", "method", "alpha", "m"})
DRAFT_LINE_SLOT_BY_SITE = {
    "DS-SENS-01": "ds_table_anchor_line",
    "DS-SENS-02": "ds_limitation_anchor_line",
    "PG-SENS-01": "pg_table_anchor_line",
    "PG-SENS-02": "pg_limitation_anchor_line",
}
AST_CITATION_SPECS = {
    "citation_two_sided_student_t_p_value": (
        REPO_ROOT / "joulewise" / "analysis_engine" / "distributions.py",
        "two_sided_student_t_p_value",
    ),
    "citation_student_t_quantile": (
        REPO_ROOT / "joulewise" / "analysis_engine" / "distributions.py",
        "student_t_quantile",
    ),
    "citation_beta_continued_fraction": (
        REPO_ROOT / "joulewise" / "analysis_engine" / "distributions.py",
        "_beta_continued_fraction",
    ),
    "citation_ci_t_critical": (
        REPO_ROOT / "joulewise" / "analysis_engine" / "estimators.py",
        "_ci_t_critical",
    ),
    "citation_evaluate_claim": (
        REPO_ROOT / "joulewise" / "analysis_engine" / "claims.py",
        "evaluate_claim",
    ),
    "citation_estimate_paired_blocks": (
        REPO_ROOT / "joulewise" / "analysis_engine" / "estimators.py",
        "estimate_paired_blocks",
    ),
    "citation_model_result": (Path(__file__).resolve(), "_model_result"),
}


class SheetRenderError(RuntimeError):
    """Raised when a generated-sheet source cannot be resolved exactly."""


def _repo_relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError as exc:
        raise SheetRenderError(f"sheet source is outside the repository: {path}") from exc


def _format_decimal(value: int | float, precision: int) -> str:
    return f"{float(value):.{precision}f}"


def _format_compact(value: int | float) -> str:
    return str(int(value)) if float(value).is_integer() else str(float(value))


def _format_interval(interval: dict[str, float]) -> str:
    return f"[{interval['lower']:.6f}, {interval['upper']:.6f}]"


def _function_citation(path: Path, name: str) -> str:
    try:
        source = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise SheetRenderError(f"cannot read citation source {_repo_relative(path)}: {exc}") from exc
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        raise SheetRenderError(f"cannot parse citation source {_repo_relative(path)}: {exc}") from exc
    definitions = [
        node
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name
    ]
    if len(definitions) != 1:
        raise SheetRenderError(
            f"expected exactly one definition of {name!r} in {_repo_relative(path)}; "
            f"found {len(definitions)}"
        )
    return f"`{name}` (`{_repo_relative(path)}`, line {definitions[0].lineno})"


def _validate_config_field_names() -> None:
    try:
        tree = ast.parse(
            CONFIG_GENERATOR_PATH.read_text(encoding="utf-8"),
            filename=str(CONFIG_GENERATOR_PATH),
        )
    except (OSError, SyntaxError) as exc:
        raise SheetRenderError(f"cannot inspect config generator: {exc}") from exc
    string_literals = {
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    }
    missing = sorted(CONFIG_FIELD_NAMES - string_literals)
    if missing:
        raise SheetRenderError(
            "config generator is missing registered field name(s): " + ", ".join(missing)
        )


def _markdown_heading_anchor(heading: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_ -]", "", heading).strip().lower()
    return slug.replace(" ", "-")


def _h30_slots() -> dict[str, str]:
    try:
        text = RETENSING_PLAN_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        raise SheetRenderError(f"cannot read retensing plan: {exc}") from exc
    sections = re.findall(r"^### (H30\b[^\n]*)\n(?P<body>.*?)(?=^### |\Z)", text, re.MULTILINE | re.DOTALL)
    if len(sections) != 1:
        raise SheetRenderError(f"expected exactly one H30 section; found {len(sections)}")
    heading, body = sections[0]
    replacements = re.findall(r"^\*\*Replacement:\*\* (.+)$", body, re.MULTILINE)
    if len(replacements) != 1:
        raise SheetRenderError(
            f"expected exactly one H30 replacement paragraph; found {len(replacements)}"
        )
    return {
        "h30_replacement": replacements[0],
        "h30_link": (
            f"{RETENSING_PLAN_PATH.name}#{_markdown_heading_anchor(heading)}"
        ),
    }


def _anchor_quote_pattern(quote_template: str) -> tuple[re.Pattern[str], tuple[str, ...]]:
    pieces: list[str] = ["^"]
    slot_names: list[str] = []
    cursor = 0
    for match in Template.pattern.finditer(quote_template):
        pieces.append(re.escape(quote_template[cursor : match.start()]))
        name = match.group("named") or match.group("braced")
        if name is None:
            raise SheetRenderError(f"unsupported draft-anchor template token: {match.group(0)!r}")
        if name in slot_names:
            raise SheetRenderError(f"duplicate draft-anchor slot: {name}")
        slot_names.append(name)
        pieces.append(f"(?P<{name}>[0-9]+)")
        cursor = match.end()
    pieces.append(re.escape(quote_template[cursor:]))
    return re.compile("".join(pieces)), tuple(slot_names)


def _draft_anchor_slots(template_text: str) -> dict[str, str]:
    placement_pattern = re.compile(
        r"^\| (?P<site>(?:DS|PG)-SENS-[0-9]+) [^|\n]*\| `(?P<quote>[^`\n]+)`",
        re.MULTILINE,
    )
    placements = tuple(placement_pattern.finditer(template_text))
    observed_sites = {match.group("site") for match in placements}
    if observed_sites != set(DRAFT_LINE_SLOT_BY_SITE) or len(placements) != len(observed_sites):
        raise SheetRenderError(
            "template draft-anchor sites differ from the registered placement set"
        )
    try:
        draft_lines = DRAFT_PATH.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise SheetRenderError(f"cannot read frozen draft: {exc}") from exc
    slots: dict[str, str] = {}
    for placement in placements:
        site = placement.group("site")
        quote_pattern, quote_slots = _anchor_quote_pattern(placement.group("quote"))
        matches = [
            (line_number, match)
            for line_number, line in enumerate(draft_lines, start=1)
            if (match := quote_pattern.match(line)) is not None
        ]
        if len(matches) != 1:
            raise SheetRenderError(
                f"draft anchor for {site} must occur exactly once; found {len(matches)}"
            )
        line_number, quote_match = matches[0]
        slots[DRAFT_LINE_SLOT_BY_SITE[site]] = str(line_number)
        for name in quote_slots:
            value = quote_match.group(name)
            if name in slots and slots[name] != value:
                raise SheetRenderError(f"draft-anchor slot {name} resolves inconsistently")
            slots[name] = value
    return slots


def _sheet_commands() -> tuple[str, str]:
    script_path = _repo_relative(Path(__file__).resolve())
    deltas = json.dumps(EXAMPLE_BLOCK_DELTAS_J)
    example = f"python3 {script_path} --example"
    disagreement = (
        f"python3 {script_path} --block-deltas {shlex.quote(deltas)} "
        f"--floor {_format_compact(EXAMPLE_FLOOR_J)} "
        f"--se-metrology {_format_compact(EXAMPLE_SE_METROLOGY_J)} "
        "--deterministic-bound-total "
        f"{_format_compact(DISAGREEMENT_DETERMINISTIC_BOUND_TOTAL_J)}"
    )
    return example, disagreement


def _execute_sheet_command(command: str) -> tuple[dict[str, Any], str, str]:
    completed = subprocess.run(
        shlex.split(command),
        cwd=REPO_ROOT,
        check=False,
        text=True,
        capture_output=True,
    )
    if completed.returncode != 0:
        raise SheetRenderError(
            f"documented command exited {completed.returncode}: {completed.stderr.strip()}"
        )
    try:
        payload = json.loads(completed.stdout)
        agreement = payload["comparison"]["direction_gate_outcomes_agree"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        raise SheetRenderError("documented command did not emit the expected JSON payload") from exc
    if not isinstance(agreement, bool):
        raise SheetRenderError("documented command emitted a non-boolean agreement field")
    fragment = f'"direction_gate_outcomes_agree": {str(agreement).lower()}'
    if fragment not in completed.stdout:
        raise SheetRenderError("documented command stdout does not contain its agreement fragment")
    return payload, fragment, "agree" if agreement else "disagree"


def _gate_prose(passes: object) -> str:
    return "passes" if passes is True else "fails"


def _gate_table(passes: object) -> str:
    return "pass" if passes is True else "fail"


def _model_slots(prefix: str, model: dict[str, Any]) -> dict[str, str]:
    return {
        f"{prefix}_variance_inflation_factor": _format_decimal(
            model["variance_inflation_factor"], 6
        ),
        f"{prefix}_effective_n": _format_decimal(model["effective_n"], 6),
        f"{prefix}_degrees_of_freedom": str(model["degrees_of_freedom"]),
        f"{prefix}_se_repeat_j": _format_decimal(model["se_repeat_j"], 6),
        f"{prefix}_repeat_only_interval_j": _format_interval(
            model["repeat_only_interval_j"]
        ),
        f"{prefix}_se_total_j": _format_decimal(model["se_total_j"], 6),
        f"{prefix}_t_critical_95": _format_decimal(model["t_critical_95"], 6),
        f"{prefix}_half_width_j": _format_decimal(model["half_width_j"], 6),
        f"{prefix}_metrology_aware_interval_j": _format_interval(
            model["metrology_aware_interval_j"]
        ),
        f"{prefix}_decision_interval_j": _format_interval(model["decision_interval_j"]),
        f"{prefix}_t_statistic": _format_decimal(model["t_statistic"], 6),
        f"{prefix}_p_replay_x": _format_decimal(
            model["raw_two_sided_p_replay"]["x"], 12
        ),
        f"{prefix}_raw_two_sided_p": _format_decimal(model["raw_two_sided_p"], 9),
        f"{prefix}_floor_gate_prose": _gate_prose(model["floor_gate"]["passes"]),
        f"{prefix}_direction_gate_prose": _gate_prose(
            model["direction_gate"]["passes"]
        ),
        f"{prefix}_floor_gate_table": _gate_table(model["floor_gate"]["passes"]),
        f"{prefix}_direction_gate_table": _gate_table(
            model["direction_gate"]["passes"]
        ),
    }


def sheet_slots(template_text: str | None = None) -> dict[str, str]:
    """Resolve every generated-sheet slot from code, source documents, or execution."""

    if template_text is None:
        try:
            template_text = SHEET_TEMPLATE_PATH.read_text(encoding="utf-8")
        except OSError as exc:
            raise SheetRenderError(f"cannot read sheet template: {exc}") from exc
    _validate_config_field_names()
    slots = _draft_anchor_slots(template_text)
    slots.update(_h30_slots())
    for slot_name, (path, function_name) in AST_CITATION_SPECS.items():
        slots[slot_name] = _function_citation(path, function_name)

    example_command, disagreement_command = _sheet_commands()
    example, example_stdout_fragment, example_agreement_word = _execute_sheet_command(
        example_command
    )
    disagreement, disagreement_stdout_fragment, _ = _execute_sheet_command(
        disagreement_command
    )
    summary = example["summary"]
    rho = example["ar1_rho_estimator"]
    models = example["models"]
    independent = models["independent_blocks"]
    ar1 = models["ar1_estimated_rho"]
    halving = models["fixed_effective_n_halving"]
    disagreement_models = disagreement["models"]

    slots.update(
        {
            "registered_alpha": _format_compact(REGISTERED_ALPHA),
            "registered_multiplicity": str(REGISTERED_MULTIPLICITY),
            "procedure_one": str(1),
            "procedure_two": str(2),
            "procedure_three": str(3),
            "alpha_over_two": _format_decimal(REGISTERED_ALPHA / 2.0, 3),
            "one_minus_alpha_over_two": _format_decimal(
                1.0 - REGISTERED_ALPHA / 2.0, 3
            ),
            "registered_n_blocks": str(REGISTERED_N_BLOCKS),
            "correlation_abs_limit": _format_compact(1.0),
            "zero_rho": _format_compact(0.0),
            "independent_v_integer": _format_compact(
                independent["variance_inflation_factor"]
            ),
            "independent_effective_n_integer": _format_compact(independent["effective_n"]),
            "independent_degrees_integer": str(independent["degrees_of_freedom"]),
            "halving_effective_n_integer": _format_compact(halving["effective_n"]),
            "halving_v_integer": _format_compact(halving["variance_inflation_factor"]),
            "halving_degrees_integer": str(halving["degrees_of_freedom"]),
            "rho_half": _format_compact(SENSITIVITY_RHOS[0]),
            "rho_half_variance_inflation": _format_decimal(
                ar1_variance_inflation_factor(REGISTERED_N_BLOCKS, SENSITIVITY_RHOS[0]), 6
            ),
            "rho_half_effective_n": _format_decimal(
                REGISTERED_N_BLOCKS
                / ar1_variance_inflation_factor(
                    REGISTERED_N_BLOCKS, SENSITIVITY_RHOS[0]
                ),
                6,
            ),
            "rho_nine_tenths": _format_compact(SENSITIVITY_RHOS[1]),
            "rho_nine_tenths_effective_n": _format_decimal(
                REGISTERED_N_BLOCKS
                / ar1_variance_inflation_factor(
                    REGISTERED_N_BLOCKS, SENSITIVITY_RHOS[1]
                ),
                6,
            ),
            "example_floor_j": _format_decimal(EXAMPLE_FLOOR_J, 6),
            "example_se_metrology_j": _format_decimal(EXAMPLE_SE_METROLOGY_J, 6),
            "example_deterministic_bound_total_j": _format_decimal(
                EXAMPLE_DETERMINISTIC_BOUND_TOTAL_J, 6
            ),
            "example_block_deltas": json.dumps(EXAMPLE_BLOCK_DELTAS_J),
            "example_sum_j": _format_decimal(summary["sum_j"], 6),
            "example_mean_j": _format_decimal(summary["mean_j"], 6),
            "example_squared_deviations_sum_j2": _format_decimal(
                summary["squared_deviations_sum_j2"], 6
            ),
            "example_sample_stddev_j": _format_decimal(summary["sample_stddev_j"], 6),
            "example_ar1_numerator": _format_decimal(rho["numerator"], 6),
            "example_ar1_denominator": _format_decimal(rho["denominator"], 6),
            "example_rho_hat": _format_decimal(rho["rho_hat"], 6),
            "example_ar1_terms": ", ".join(
                _format_decimal(row["term"], 6) for row in example["ar1_variance_terms"]
            ),
            "example_ar1_terms_sum": _format_decimal(
                math.fsum(row["term"] for row in example["ar1_variance_terms"]), 6
            ),
            "example_command": example_command,
            "example_agreement_word": example_agreement_word,
            "example_stdout_fragment": example_stdout_fragment,
            "disagreement_deterministic_bound_total_j": _format_decimal(
                DISAGREEMENT_DETERMINISTIC_BOUND_TOTAL_J, 6
            ),
            "disagreement_command": disagreement_command,
            "disagreement_stdout_fragment": disagreement_stdout_fragment,
            "disagreement_independent_direction_participle": (
                "passing"
                if disagreement_models["independent_blocks"]["direction_gate"]["passes"]
                else "failing"
            ),
            "disagreement_nonregistered_direction_plural": (
                "pass"
                if all(
                    disagreement_models[name]["direction_gate"]["passes"]
                    for name in ("ar1_estimated_rho", "fixed_effective_n_halving")
                )
                else "fail"
            ),
            "registered_direction_outcome_placeholder": "[passed/failed]",
            "model_one_label": "model-1",
            "ds31_disagreement_reason": (
                "SENSITIVITY_MODEL_1_OUTCOME_DISAGREES_WITH_REGISTERED_DS31"
            ),
            "pg07_disagreement_reason": (
                "SENSITIVITY_MODEL_1_OUTCOME_DISAGREES_WITH_REGISTERED_PG07"
            ),
            "schema_version": SCHEMA_VERSION,
            "sha256_hex_characters": str(hashlib.sha256().digest_size * 2),
            "field_t_critical_95": next(
                key for key in independent if key == "t_critical_95"
            ),
            "field_block_deltas_json_sha256": "input_authentication."
            + next(
                key
                for key in example["input_authentication"]
                if key == "block_deltas_json_sha256"
            ),
            "field_metrology_inputs_json_sha256": "input_authentication."
            + next(
                key
                for key in example["input_authentication"]
                if key == "metrology_inputs_json_sha256"
            ),
            "field_ar1_rho_estimator_rho_hat": "ar1_rho_estimator."
            + next(key for key in example["ar1_rho_estimator"] if key == "rho_hat"),
            "field_ar1_variance_terms": next(
                key for key in example if key == "ar1_variance_terms"
            ),
            "config_generator_path": _repo_relative(CONFIG_GENERATOR_PATH),
            "calculator_path": _repo_relative(Path(__file__).resolve()),
            "draft_path": _repo_relative(DRAFT_PATH),
        }
    )
    slots.update(_model_slots("independent", independent))
    slots.update(_model_slots("ar1", ar1))
    slots.update(_model_slots("halving", halving))
    slots["independent_t_critical_three_dp"] = _format_decimal(
        independent["t_critical_95"], 3
    )
    slots["ar1_t_critical_three_dp"] = _format_decimal(ar1["t_critical_95"], 3)
    if not all(isinstance(value, str) for value in slots.values()):
        raise SheetRenderError("every sheet slot must be pre-formatted as a string")
    return slots


def render_sheet() -> str:
    """Render the generated dependence-sensitivity sheet from its sole authoring surface."""

    try:
        template_text = SHEET_TEMPLATE_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        raise SheetRenderError(f"cannot read sheet template: {exc}") from exc
    rendered = Template(template_text).substitute(sheet_slots(template_text))
    return GENERATED_HEADER + rendered


def _finite_number(value: object, name: str) -> float:
    """Return one finite real number, rejecting booleans and text."""

    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{name} must be a finite number")
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"{name} must be a finite number")
    return number


def _nonnegative_number(value: object, name: str) -> float:
    """Return one finite non-negative real number."""

    number = _finite_number(value, name)
    if number < 0.0:
        raise ValueError(f"{name} must be non-negative")
    return number


def _validated_deltas(block_deltas_j: object) -> list[float]:
    """Validate the registered ten-delta JSON payload before calculating."""

    if isinstance(block_deltas_j, (str, bytes)) or not isinstance(
        block_deltas_j, Sequence
    ):
        raise ValueError("block_deltas_j must be a JSON list")
    deltas = [
        _finite_number(value, f"block_deltas_j[{index}]")
        for index, value in enumerate(block_deltas_j)
    ]
    if len(deltas) != REGISTERED_N_BLOCKS:
        raise ValueError("exactly ten complete block deltas are required")
    return deltas


def estimate_ar1_rho(block_deltas_j: Sequence[float], mean_j: float) -> dict[str, float]:
    """Estimate adjacent-block relation with a centred preceding-to-following slope."""

    centred = [value - mean_j for value in block_deltas_j]
    numerator = math.fsum(
        centred[index] * centred[index - 1] for index in range(1, len(centred))
    )
    denominator = math.fsum(value * value for value in centred[:-1])
    if (
        not math.isfinite(numerator)
        or not math.isfinite(denominator)
        or denominator <= 0.0
    ):
        raise ValueError("AR(1) rho is undefined for this block-delta sequence")
    rho_hat = numerator / denominator
    if not math.isfinite(rho_hat) or abs(rho_hat) >= 1.0:
        raise ValueError("AR(1) rho must be finite and satisfy abs(rho) < 1")
    return {
        "numerator": numerator,
        "denominator": denominator,
        "rho_hat": rho_hat,
    }


def _ar1_variance_terms(n_blocks: int, rho: float) -> list[dict[str, float | int]]:
    """Return the finite-series terms that multiply the repeat variance."""

    if n_blocks < 2:
        raise ValueError("at least two blocks are required for an AR(1) multiplier")
    numeric_rho = _finite_number(rho, "rho")
    if abs(numeric_rho) >= 1.0:
        raise ValueError("AR(1) rho must be finite and satisfy abs(rho) < 1")
    return [
        {
            "lag": lag,
            "term": (1.0 - lag / n_blocks) * numeric_rho**lag,
        }
        for lag in range(1, n_blocks)
    ]


def ar1_variance_inflation_factor(n_blocks: int, rho: float) -> float:
    """Return the finite-n variance multiplier for an AR(1) sample mean."""

    terms = _ar1_variance_terms(n_blocks, rho)
    multiplier = 1.0 + 2.0 * math.fsum(float(row["term"]) for row in terms)
    # V*n = 1ᵀR1 > 0 because R is positive definite for |rho| < 1.
    return multiplier


def _degrees_of_freedom(n_blocks: int, effective_n: float) -> int:
    """Choose the registered conservative integral Student-t degree count."""

    if not math.isfinite(effective_n) or effective_n <= 0.0:
        raise ValueError("effective sample size is not positive and finite")
    degrees = min(n_blocks - 1, math.floor(effective_n) - 1)
    if degrees < 1:
        raise ValueError("effective sample size leaves fewer than two usable blocks")
    return degrees


def _interval(center: float, standard_error: float, critical: float) -> dict[str, float]:
    """Return one finite closed interval using the registered rounded critical."""

    half_width = critical * standard_error
    lower = center - half_width
    upper = center + half_width
    if not all(math.isfinite(value) for value in (half_width, lower, upper)):
        raise ValueError("interval is not finite")
    return {"lower": lower, "upper": upper}


def _strict_direction(interval: dict[str, float]) -> str | None:
    """Return the strict common sign of both endpoints, if either has one."""

    if interval["lower"] > 0.0 and interval["upper"] > 0.0:
        return "positive"
    if interval["lower"] < 0.0 and interval["upper"] < 0.0:
        return "negative"
    return None


def _model_result(
    *,
    name: str,
    description: str,
    mean_j: float,
    sample_stddev_j: float,
    n_blocks: int,
    effective_n: float,
    variance_inflation_factor: float,
    se_metrology_j: float,
    deterministic_bound_total_j: float,
    floor_j: float,
) -> dict[str, Any]:
    """Build one fully composed registered interval under one repeat model."""

    degrees = _degrees_of_freedom(n_blocks, effective_n)
    se_repeat = sample_stddev_j / math.sqrt(effective_n)
    se_total = math.hypot(se_repeat, se_metrology_j)
    critical = round(student_t_quantile(1.0 - REGISTERED_ALPHA / 2.0, degrees), 3)
    repeat_only_interval = _interval(mean_j, se_repeat, critical)
    metrology_aware_interval = _interval(mean_j, se_total, critical)
    decision_interval = {
        "lower": metrology_aware_interval["lower"] - deterministic_bound_total_j,
        "upper": metrology_aware_interval["upper"] + deterministic_bound_total_j,
    }
    if not all(math.isfinite(value) for value in decision_interval.values()):
        raise ValueError(f"{name} decision interval is not finite")
    half_width = critical * se_total
    if se_total <= 0.0:
        raise ValueError("total standard error must be positive")
    statistic = mean_j / se_total
    raw_p = two_sided_student_t_p_value(statistic, degrees)
    tail_x = degrees / (degrees + statistic**2)
    metrology_direction = _strict_direction(metrology_aware_interval)
    decision_direction = _strict_direction(decision_interval)
    return {
        "model": name,
        "description": description,
        "effective_n": effective_n,
        "degrees_of_freedom": degrees,
        "variance_inflation_factor": variance_inflation_factor,
        "se_repeat_j": se_repeat,
        "repeat_only_interval_j": repeat_only_interval,
        "se_metrology_j": se_metrology_j,
        "se_total_j": se_total,
        "t_critical_95": critical,
        "half_width_j": half_width,
        "metrology_aware_interval_j": metrology_aware_interval,
        "deterministic_bound_total_j": deterministic_bound_total_j,
        "decision_interval_j": decision_interval,
        "t_statistic": statistic,
        "raw_two_sided_p": raw_p,
        "raw_two_sided_p_replay": {
            "formula": "p = I_x(ν/2, 1/2)",
            "x_formula": "x = ν/(ν + t²)",
            "x": tail_x,
        },
        "floor_gate": {
            "rule": "abs(mean_j) > registered_floor_j",
            "registered_floor_j": floor_j,
            "passes": abs(mean_j) > floor_j,
        },
        "direction_gate": {
            "rule": "both endpoints of both fully composed intervals have the same strict sign",
            "metrology_aware_direction": metrology_direction,
            "decision_direction": decision_direction,
            "passes": metrology_direction is not None
            and metrology_direction == decision_direction,
        },
    }


def _canonical_json(value: object) -> str:
    """Return the artifact's fixed UTF-8 JSON representation for hashing."""

    return json.dumps(value, ensure_ascii=False, allow_nan=False, separators=(",", ":"))


def _sha256_text(value: str) -> str:
    """Return the hexadecimal SHA-256 digest of one UTF-8 string."""

    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def analyze_deltas(
    block_deltas_j: object,
    *,
    floor_j: object,
    se_metrology_j: object,
    deterministic_bound_total_j: object,
) -> dict[str, Any]:
    """Compute the three registered dependence models for exactly ten blocks."""

    deltas = _validated_deltas(block_deltas_j)
    registered_floor = _nonnegative_number(floor_j, "floor_j")
    se_metrology = _nonnegative_number(se_metrology_j, "se_metrology_j")
    deterministic_total = _nonnegative_number(
        deterministic_bound_total_j, "deterministic_bound_total_j"
    )

    n_blocks = len(deltas)
    total_j = math.fsum(deltas)
    mean_j = total_j / n_blocks
    squared_deviations_sum_j2 = math.fsum((value - mean_j) ** 2 for value in deltas)
    sample_stddev_j = math.sqrt(squared_deviations_sum_j2 / (n_blocks - 1))
    if not math.isfinite(sample_stddev_j):
        raise ValueError("sample standard deviation is not finite")
    rho = estimate_ar1_rho(deltas, mean_j)
    ar1_terms = _ar1_variance_terms(n_blocks, rho["rho_hat"])
    variance_inflation = ar1_variance_inflation_factor(n_blocks, rho["rho_hat"])
    ar1_effective_n = n_blocks / variance_inflation
    half_effective_n = n_blocks / 2.0

    models = {
        "independent_blocks": _model_result(
            name="independent_blocks",
            description="registered composition with n_eff = n",
            mean_j=mean_j,
            sample_stddev_j=sample_stddev_j,
            n_blocks=n_blocks,
            effective_n=float(n_blocks),
            variance_inflation_factor=1.0,
            se_metrology_j=se_metrology,
            deterministic_bound_total_j=deterministic_total,
            floor_j=registered_floor,
        ),
        "ar1_estimated_rho": _model_result(
            name="ar1_estimated_rho",
            description="finite-n AR(1) repeat-variance sensitivity",
            mean_j=mean_j,
            sample_stddev_j=sample_stddev_j,
            n_blocks=n_blocks,
            effective_n=ar1_effective_n,
            variance_inflation_factor=variance_inflation,
            se_metrology_j=se_metrology,
            deterministic_bound_total_j=deterministic_total,
            floor_j=registered_floor,
        ),
        "fixed_effective_n_halving": _model_result(
            name="fixed_effective_n_halving",
            description="fixed effective-n halving (a named pessimistic scenario, not a bound)",
            mean_j=mean_j,
            sample_stddev_j=sample_stddev_j,
            n_blocks=n_blocks,
            effective_n=half_effective_n,
            variance_inflation_factor=2.0,
            se_metrology_j=se_metrology,
            deterministic_bound_total_j=deterministic_total,
            floor_j=registered_floor,
        ),
    }
    direction_outcomes = [row["direction_gate"]["passes"] for row in models.values()]
    block_deltas_json = _canonical_json(deltas)
    metrology_inputs = {
        "se_metrology_j": se_metrology,
        "deterministic_bound_total_j": deterministic_total,
    }
    metrology_inputs_json = _canonical_json(metrology_inputs)
    return {
        "schema_version": SCHEMA_VERSION,
        "artifact_type": "registered_dependence_sensitivity",
        "input_authentication": {
            "canonical_json": "UTF-8 JSON with ensure_ascii=false and separators=(',', ':')",
            "block_deltas_json_sha256": _sha256_text(block_deltas_json),
            "metrology_inputs": metrology_inputs,
            "metrology_inputs_json_sha256": _sha256_text(metrology_inputs_json),
        },
        "input": {
            "block_deltas_j": deltas,
            "registered_floor_j": registered_floor,
            "registered_alpha": REGISTERED_ALPHA,
            **metrology_inputs,
        },
        "summary": {
            "n_blocks": n_blocks,
            "sum_j": total_j,
            "mean_j": mean_j,
            "squared_deviations_sum_j2": squared_deviations_sum_j2,
            "sample_stddev_j": sample_stddev_j,
        },
        "ar1_rho_estimator": {
            "method": "centred_conditional_least_squares_lag1_v1",
            "formula": "sum((d_i-mean)*(d_i_minus_1-mean), i=2..n) / sum((d_i_minus_1-mean)^2, i=2..n)",
            **rho,
        },
        "ar1_variance_terms": ar1_terms,
        "models": models,
        "comparison": {
            "direction_gate_outcomes_agree": len(set(direction_outcomes)) == 1,
        },
    }


def _json_list_from_text(text: str, source: str) -> object:
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"{source} is not valid JSON: {exc.msg}") from exc
    return value


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group()
    source.add_argument(
        "--block-deltas", help="JSON list of ten complete ABBA block deltas in joules"
    )
    source.add_argument(
        "--block-deltas-file", type=Path, help="UTF-8 file containing that JSON list"
    )
    parser.add_argument("--floor", type=float, help="registered non-negative floor in joules")
    parser.add_argument(
        "--se-metrology",
        type=float,
        help="registered stochastic-metrology standard error in joules",
    )
    parser.add_argument(
        "--deterministic-bound-total",
        type=float,
        help="registered deterministic-bound total in joules",
    )
    source.add_argument("--example", action="store_true", help="print the worked example")
    source.add_argument(
        "--render-sheet",
        action="store_true",
        help="render dependence-sensitivity.md from its template to stdout",
    )
    source.add_argument(
        "--check-sheet",
        action="store_true",
        help="exit 2 if dependence-sensitivity.md differs from a fresh render",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    if args.render_sheet or args.check_sheet:
        if (
            args.floor is not None
            or args.se_metrology is not None
            or args.deterministic_bound_total is not None
        ):
            print(
                "dependence_sensitivity: ERROR: sheet modes do not accept calculator inputs",
                file=sys.stderr,
            )
            return 2
        try:
            rendered_sheet = render_sheet()
        except (OSError, KeyError, SheetRenderError, subprocess.SubprocessError) as exc:
            print(f"dependence_sensitivity: ERROR: cannot render sheet: {exc}", file=sys.stderr)
            return 2
        if args.render_sheet:
            sys.stdout.write(rendered_sheet)
            return 0
        try:
            tracked_sheet = SHEET_OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError as exc:
            print(
                f"dependence_sensitivity: DRIFT: cannot read {_repo_relative(SHEET_OUTPUT_PATH)}: {exc}",
                file=sys.stderr,
            )
            return 2
        if tracked_sheet != rendered_sheet:
            print(
                f"dependence_sensitivity: DRIFT in {_repo_relative(SHEET_OUTPUT_PATH)}",
                file=sys.stderr,
            )
            return 2
        return 0
    if args.example:
        if (
            args.block_deltas is not None
            or args.block_deltas_file is not None
            or args.floor is not None
            or args.se_metrology is not None
            or args.deterministic_bound_total is not None
        ):
            parser.error(
                "--example cannot be combined with input, --floor, --se-metrology, "
                "or --deterministic-bound-total"
            )
        deltas: object = EXAMPLE_BLOCK_DELTAS_J
        floor = EXAMPLE_FLOOR_J
        se_metrology = EXAMPLE_SE_METROLOGY_J
        deterministic_total = EXAMPLE_DETERMINISTIC_BOUND_TOTAL_J
    else:
        if args.block_deltas is None and args.block_deltas_file is None:
            parser.error(
                "one of --block-deltas or --block-deltas-file is required unless --example is used"
            )
        if (
            args.floor is None
            or args.se_metrology is None
            or args.deterministic_bound_total is None
        ):
            parser.error(
                "--floor, --se-metrology, and --deterministic-bound-total are required unless --example is used"
            )
        try:
            if args.block_deltas_file is not None:
                deltas = _json_list_from_text(
                    args.block_deltas_file.read_text(encoding="utf-8"),
                    str(args.block_deltas_file),
                )
            else:
                assert args.block_deltas is not None
                deltas = _json_list_from_text(args.block_deltas, "--block-deltas")
        except OSError as exc:
            parser.error(f"cannot read block-delta JSON: {exc}")
        except (ValueError, OverflowError) as exc:
            parser.error(str(exc))
        floor = args.floor
        se_metrology = args.se_metrology
        deterministic_total = args.deterministic_bound_total
    try:
        result = analyze_deltas(
            deltas,
            floor_j=floor,
            se_metrology_j=se_metrology,
            deterministic_bound_total_j=deterministic_total,
        )
    except (ValueError, OverflowError) as exc:
        parser.error(str(exc))
    print(json.dumps(result, indent=2, ensure_ascii=False, allow_nan=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
