#!/usr/bin/env python3
"""Render a sealed QPE-01 evidence wrapper and manifest. Never install or collect."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from joulewise.night_gate import NightPlan, chain_literal, probe_payload_kind
from joulewise.night_kinds import NIGHT_KINDS, kind_row
from joulewise.quiet_predicate_campaign import CHAIN_PATH, manifest_for
from scripts.gen_derivation_night import GenerationRefusal, _quote, _census_clean, _require_absolute


def generate(plan_path, *, out=None, chain_template=CHAIN_PATH):
    plan_path = Path(plan_path).absolute()
    plan = NightPlan.from_mapping(json.loads(plan_path.read_text()))
    matches = [item for item in NIGHT_KINDS.values()
               if item.chain_source_path == chain_template and item.payload_kind]
    row = matches[0] if len(matches) == 1 else kind_row("quiet_predicate_evidence")
    if plan.receipt_class != row.receipt_class or plan.quiet_admission is not None:
        raise GenerationRefusal("evidence requires v2 DIAGNOSTIC_NO_PACK")
    if len(matches) != 1:
        raise GenerationRefusal("calibration/derivation or alternate chain refused")
    if (row.handler != "evidence" or not row.manifest_for
            or not row.executor_module or not row.manifest_name or not row.wrapper_prefix):
        raise GenerationRefusal("calibration/derivation or alternate chain refused")
    # Match the basename stem as the original refusal did, including suffix variants.
    calibration_basename = Path(kind_row("calibration").chain_source_path).stem
    target = Path(out).absolute() if out else Path(plan.chain_path)
    if str(target) != plan.chain_path or plan.chain_sha256_path != str(target) + ".sha256":
        raise GenerationRefusal("output and sidecar must match the sealed plan")
    if target.exists():
        text = target.read_text()
        if ("CALIBRATION_LEDGER" in text or "LEDGER_HEAD_PIN" in text or
                calibration_basename in text):
            raise GenerationRefusal("calibration/derivation chain refused")
        raise GenerationRefusal("chain already exists; author a fresh plan")
    chain_source = row.chain_source_path
    for value in (plan.plan_id, plan.measurement_root, plan.custody_root, str(target),
                  str(plan_path), str(Path(plan.measurement_root) / chain_source)):
        _census_clean("chain argv/custody/plan", value)
        _quote(value)
    manifest = row.manifest_for(plan)
    source = (Path(plan.measurement_root) / chain_source).read_text()
    if (probe_payload_kind(source) != row.kind or
            any(token in source for token in ("CALIBRATION_LEDGER", "LEDGER_HEAD_PIN", calibration_basename))):
        raise GenerationRefusal("calibration/derivation chain refused")
    manifest_path = target.with_name(row.manifest_name)
    manifest_bytes = (json.dumps(manifest, sort_keys=True, indent=2) + "\n").encode()
    sha = hashlib.sha256(manifest_bytes).hexdigest()
    # Runbook §1.1b invariant: wrapper bytes depend on plan content, never its staging path.
    # A relative custody root would seal a relative plan path (Opus 90 S2): refuse at the desk.
    published_plan_path = Path(_require_absolute("night custody root", plan.custody_root)) / "night_plan.json"
    prefix = row.wrapper_prefix
    exports = {f"{prefix}_PLAN_PATH": str(published_plan_path), f"{prefix}_MANIFEST_PATH": str(manifest_path),
               f"{prefix}_MANIFEST_SHA256": sha, f"{prefix}_CHAIN_SOURCE_SHA256": manifest["files"][chain_source]}
    lines = ["#!/bin/zsh", "# GENERATED by scripts/gen_evidence_night.py; do not edit.",
             "set -euo pipefail", f"export NIGHT_PAYLOAD_KIND={row.kind}",
             "export PYTHONDONTWRITEBYTECODE=1"]
    lines += [f"export {key}={_quote(value)}" for key, value in exports.items()]
    lines += [f"export PY={_quote(plan.measurement_root + '/.venv/bin/python')}",
              f"export PYTHONPATH={_quote(plan.measurement_root)}",
              f'refuse() {{ "$PY" -B -m {row.executor_module} refuse --reason "$1"; exit 2; }}']
    for name, value in (("NIGHT_PLAN_ID", plan.plan_id), ("MEASUREMENT_ROOT", plan.measurement_root),
                        ("MEASUREMENT_HEAD", plan.measurement_head)):
        lines.append(f'[[ "${{{name}:-}}" == {_quote(value)} ]] || refuse {_quote(name + " mismatch")}')
    lines += [f'[[ "$(/usr/bin/shasum -a 256 {_quote(plan.measurement_root + "/" + chain_source)} | /usr/bin/awk \'{{print $1}}\')" == "${prefix}_CHAIN_SOURCE_SHA256" ]] || refuse chain_source_sha256_mismatch',
              f'exec /bin/zsh {_quote(plan.measurement_root + "/" + chain_source)}']
    wrapper = ("\n".join(lines) + "\n").encode()
    artifacts = {manifest_path: manifest_bytes, target: wrapper,
                 Path(plan.chain_sha256_path): (hashlib.sha256(wrapper).hexdigest() + "  " + target.name + "\n").encode(),
                 Path(str(target) + ".chain-source.sha256"): (manifest["files"][chain_source] + "  " + Path(chain_source).name + "\n").encode()}
    if any(path.exists() for path in artifacts):
        raise GenerationRefusal("evidence artifact exists; refusing overwrite")
    target.parent.mkdir(parents=True, exist_ok=True)
    for path, data in artifacts.items():
        with path.open("xb") as stream:
            stream.write(data)
    target.chmod(0o755)
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", required=True)
    parser.add_argument("--out")
    parser.add_argument("--chain-template", default=CHAIN_PATH)
    parser.add_argument("--render-only", action="store_true", required=True)
    args = parser.parse_args(argv)  # Unknown timing/count/cadence options refuse.
    try:
        print(generate(args.plan, out=args.out, chain_template=args.chain_template))
        return 0
    except (OSError, ValueError, GenerationRefusal, subprocess.SubprocessError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
