#!/usr/bin/env python3
"""Render a sealed QPE-01 evidence wrapper and manifest. Never install or collect."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from joulewise.night_gate import NightPlan, chain_literal, probe_payload_kind
from joulewise.quiet_predicate_campaign import CHAIN_PATH, manifest_for
from scripts.gen_derivation_night import GenerationRefusal, _quote, _census_clean, _require_absolute


def generate(plan_path, *, out=None, chain_template=CHAIN_PATH):
    plan_path = Path(plan_path).absolute()
    plan = NightPlan.from_mapping(json.loads(plan_path.read_text()))
    if plan.receipt_class != "DIAGNOSTIC_NO_PACK" or plan.quiet_admission is not None:
        raise GenerationRefusal("evidence requires v2 DIAGNOSTIC_NO_PACK")
    if chain_template != CHAIN_PATH:
        raise GenerationRefusal("calibration/derivation or alternate chain refused")
    target = Path(out).absolute() if out else Path(plan.chain_path)
    if str(target) != plan.chain_path or plan.chain_sha256_path != str(target) + ".sha256":
        raise GenerationRefusal("output and sidecar must match the sealed plan")
    if target.exists():
        text = target.read_text()
        if ("CALIBRATION_LEDGER" in text or "LEDGER_HEAD_PIN" in text or
                "calibration_derivation_only" in text):
            raise GenerationRefusal("calibration/derivation chain refused")
        raise GenerationRefusal("chain already exists; author a fresh plan")
    for value in (plan.plan_id, plan.measurement_root, plan.custody_root, str(target),
                  str(plan_path), str(Path(plan.measurement_root) / CHAIN_PATH)):
        _census_clean("chain argv/custody/plan", value)
        _quote(value)
    manifest = manifest_for(plan)
    source = (Path(plan.measurement_root) / CHAIN_PATH).read_text()
    if (probe_payload_kind(source) != "quiet_predicate_evidence" or
            any(token in source for token in ("CALIBRATION_LEDGER", "LEDGER_HEAD_PIN", "calibration_derivation_only"))):
        raise GenerationRefusal("calibration/derivation chain refused")
    manifest_path = target.with_name("evidence_manifest.json")
    manifest_bytes = (json.dumps(manifest, sort_keys=True, indent=2) + "\n").encode()
    sha = hashlib.sha256(manifest_bytes).hexdigest()
    # Runbook §1.1b invariant: wrapper bytes depend on plan content, never its staging path.
    # A relative custody root would seal a relative plan path (Opus 90 S2): refuse at the desk.
    published_plan_path = Path(_require_absolute("night custody root", plan.custody_root)) / "night_plan.json"
    exports = {"EVIDENCE_PLAN_PATH": str(published_plan_path), "EVIDENCE_MANIFEST_PATH": str(manifest_path),
               "EVIDENCE_MANIFEST_SHA256": sha, "EVIDENCE_CHAIN_SOURCE_SHA256": manifest["files"][CHAIN_PATH]}
    lines = ["#!/bin/zsh", "# GENERATED by scripts/gen_evidence_night.py; do not edit.",
             "set -euo pipefail", "export NIGHT_PAYLOAD_KIND=quiet_predicate_evidence",
             "export PYTHONDONTWRITEBYTECODE=1"]
    lines += [f"export {key}={_quote(value)}" for key, value in exports.items()]
    lines += [f"export PY={_quote(plan.measurement_root + '/.venv/bin/python')}",
              f"export PYTHONPATH={_quote(plan.measurement_root)}",
              'refuse() { "$PY" -B -m joulewise.quiet_predicate_campaign refuse --reason "$1"; exit 2; }']
    for name, value in (("NIGHT_PLAN_ID", plan.plan_id), ("MEASUREMENT_ROOT", plan.measurement_root),
                        ("MEASUREMENT_HEAD", plan.measurement_head)):
        lines.append(f'[[ "${{{name}:-}}" == {_quote(value)} ]] || refuse {_quote(name + " mismatch")}')
    lines += [f'[[ "$(/usr/bin/shasum -a 256 {_quote(plan.measurement_root + "/" + CHAIN_PATH)} | /usr/bin/awk \'{{print $1}}\')" == "$EVIDENCE_CHAIN_SOURCE_SHA256" ]] || refuse chain_source_sha256_mismatch',
              f'exec /bin/zsh {_quote(plan.measurement_root + "/" + CHAIN_PATH)}']
    wrapper = ("\n".join(lines) + "\n").encode()
    artifacts = {manifest_path: manifest_bytes, target: wrapper,
                 Path(plan.chain_sha256_path): (hashlib.sha256(wrapper).hexdigest() + "  " + target.name + "\n").encode(),
                 Path(str(target) + ".chain-source.sha256"): (manifest["files"][CHAIN_PATH] + "  " + Path(CHAIN_PATH).name + "\n").encode()}
    if any(path.exists() for path in artifacts):
        raise GenerationRefusal("evidence artifact exists; refusing overwrite")
    target.parent.mkdir(parents=True, exist_ok=True)
    for path, data in artifacts.items():
        with path.open("xb") as stream:
            stream.write(data)
    target.chmod(0o755)
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", required=True)
    parser.add_argument("--out")
    parser.add_argument("--chain-template", default=CHAIN_PATH)
    parser.add_argument("--render-only", action="store_true", required=True)
    args = parser.parse_args(argv)  # Unknown timing/count/cadence options refuse.
    try:
        print(generate(args.plan, out=args.out, chain_template=args.chain_template))
        return 0
    except (OSError, ValueError, GenerationRefusal, subprocess.SubprocessError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
